// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewAccessService creates a new instance of AccessService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccessService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccessService {
	mock := &AccessService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AccessService is an autogenerated mock type for the AccessService type
type AccessService struct {
	mock.Mock
}

type AccessService_Expecter struct {
	mock *mock.Mock
}

func (_m *AccessService) EXPECT() *AccessService_Expecter {
	return &AccessService_Expecter{mock: &_m.Mock}
}

// AssertNotSelf provides a mock function for the type AccessService
func (_mock *AccessService) AssertNotSelf(ctx context.Context, hirer domain.HirerID, target domain.UserID) error {
	ret := _mock.Called(ctx, hirer, target)

	if len(ret) == 0 {
		panic("no return value specified for AssertNotSelf")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.HirerID, domain.UserID) error); ok {
		r0 = returnFunc(ctx, hirer, target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AccessService_AssertNotSelf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssertNotSelf'
type AccessService_AssertNotSelf_Call struct {
	*mock.Call
}

// AssertNotSelf is a helper method to define mock.On call
//   - ctx context.Context
//   - hirer domain.HirerID
//   - target domain.UserID
func (_e *AccessService_Expecter) AssertNotSelf(ctx interface{}, hirer interface{}, target interface{}) *AccessService_AssertNotSelf_Call {
	return &AccessService_AssertNotSelf_Call{Call: _e.mock.On("AssertNotSelf", ctx, hirer, target)}
}

func (_c *AccessService_AssertNotSelf_Call) Run(run func(ctx context.Context, hirer domain.HirerID, target domain.UserID)) *AccessService_AssertNotSelf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.HirerID
		if args[1] != nil {
			arg1 = args[1].(domain.HirerID)
		}
		var arg2 domain.UserID
		if args[2] != nil {
			arg2 = args[2].(domain.UserID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AccessService_AssertNotSelf_Call) Return(err error) *AccessService_AssertNotSelf_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AccessService_AssertNotSelf_Call) RunAndReturn(run func(ctx context.Context, hirer domain.HirerID, target domain.UserID) error) *AccessService_AssertNotSelf_Call {
	_c.Call.Return(run)
	return _c
}

// RequireHiringCapability provides a mock function for the type AccessService
func (_mock *AccessService) RequireHiringCapability(ctx context.Context, p domain.Principal) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for RequireHiringCapability")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AccessService_RequireHiringCapability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireHiringCapability'
type AccessService_RequireHiringCapability_Call struct {
	*mock.Call
}

// RequireHiringCapability is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
func (_e *AccessService_Expecter) RequireHiringCapability(ctx interface{}, p interface{}) *AccessService_RequireHiringCapability_Call {
	return &AccessService_RequireHiringCapability_Call{Call: _e.mock.On("RequireHiringCapability", ctx, p)}
}

func (_c *AccessService_RequireHiringCapability_Call) Run(run func(ctx context.Context, p domain.Principal)) *AccessService_RequireHiringCapability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AccessService_RequireHiringCapability_Call) Return(err error) *AccessService_RequireHiringCapability_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AccessService_RequireHiringCapability_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal) error) *AccessService_RequireHiringCapability_Call {
	_c.Call.Return(run)
	return _c
}
