// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewAdminRepository creates a new instance of AdminRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminRepository {
	mock := &AdminRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AdminRepository is an autogenerated mock type for the AdminRepository type
type AdminRepository struct {
	mock.Mock
}

type AdminRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AdminRepository) EXPECT() *AdminRepository_Expecter {
	return &AdminRepository_Expecter{mock: &_m.Mock}
}

// ByEmail provides a mock function for the type AdminRepository
func (_mock *AdminRepository) ByEmail(ctx context.Context, email string) (*domain.Admin, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ByEmail")
	}

	var r0 *domain.Admin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Admin, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Admin); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Admin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AdminRepository_ByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByEmail'
type AdminRepository_ByEmail_Call struct {
	*mock.Call
}

// ByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *AdminRepository_Expecter) ByEmail(ctx interface{}, email interface{}) *AdminRepository_ByEmail_Call {
	return &AdminRepository_ByEmail_Call{Call: _e.mock.On("ByEmail", ctx, email)}
}

func (_c *AdminRepository_ByEmail_Call) Run(run func(ctx context.Context, email string)) *AdminRepository_ByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AdminRepository_ByEmail_Call) Return(admin *domain.Admin, err error) *AdminRepository_ByEmail_Call {
	_c.Call.Return(admin, err)
	return _c
}

func (_c *AdminRepository_ByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*domain.Admin, error)) *AdminRepository_ByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ByID provides a mock function for the type AdminRepository
func (_mock *AdminRepository) ByID(ctx context.Context, id domain.AdminID) (*domain.Admin, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 *domain.Admin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AdminID) (*domain.Admin, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AdminID) *domain.Admin); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Admin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.AdminID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AdminRepository_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type AdminRepository_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.AdminID
func (_e *AdminRepository_Expecter) ByID(ctx interface{}, id interface{}) *AdminRepository_ByID_Call {
	return &AdminRepository_ByID_Call{Call: _e.mock.On("ByID", ctx, id)}
}

func (_c *AdminRepository_ByID_Call) Run(run func(ctx context.Context, id domain.AdminID)) *AdminRepository_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AdminID
		if args[1] != nil {
			arg1 = args[1].(domain.AdminID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AdminRepository_ByID_Call) Return(admin *domain.Admin, err error) *AdminRepository_ByID_Call {
	_c.Call.Return(admin, err)
	return _c
}

func (_c *AdminRepository_ByID_Call) RunAndReturn(run func(ctx context.Context, id domain.AdminID) (*domain.Admin, error)) *AdminRepository_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// DecideVerification provides a mock function for the type AdminRepository
func (_mock *AdminRepository) DecideVerification(ctx context.Context, tx port.Tx, id domain.RequestID, by domain.AdminID, d domain.VerificationDecision) error {
	ret := _mock.Called(ctx, tx, id, by, d)

	if len(ret) == 0 {
		panic("no return value specified for DecideVerification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.RequestID, domain.AdminID, domain.VerificationDecision) error); ok {
		r0 = returnFunc(ctx, tx, id, by, d)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AdminRepository_DecideVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecideVerification'
type AdminRepository_DecideVerification_Call struct {
	*mock.Call
}

// DecideVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - id domain.RequestID
//   - by domain.AdminID
//   - d domain.VerificationDecision
func (_e *AdminRepository_Expecter) DecideVerification(ctx interface{}, tx interface{}, id interface{}, by interface{}, d interface{}) *AdminRepository_DecideVerification_Call {
	return &AdminRepository_DecideVerification_Call{Call: _e.mock.On("DecideVerification", ctx, tx, id, by, d)}
}

func (_c *AdminRepository_DecideVerification_Call) Run(run func(ctx context.Context, tx port.Tx, id domain.RequestID, by domain.AdminID, d domain.VerificationDecision)) *AdminRepository_DecideVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 domain.RequestID
		if args[2] != nil {
			arg2 = args[2].(domain.RequestID)
		}
		var arg3 domain.AdminID
		if args[3] != nil {
			arg3 = args[3].(domain.AdminID)
		}
		var arg4 domain.VerificationDecision
		if args[4] != nil {
			arg4 = args[4].(domain.VerificationDecision)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *AdminRepository_DecideVerification_Call) Return(err error) *AdminRepository_DecideVerification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AdminRepository_DecideVerification_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, id domain.RequestID, by domain.AdminID, d domain.VerificationDecision) error) *AdminRepository_DecideVerification_Call {
	_c.Call.Return(run)
	return _c
}

// PasswordHash provides a mock function for the type AdminRepository
func (_mock *AdminRepository) PasswordHash(ctx context.Context, id domain.AdminID) ([]byte, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for PasswordHash")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AdminID) ([]byte, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AdminID) []byte); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.AdminID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AdminRepository_PasswordHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasswordHash'
type AdminRepository_PasswordHash_Call struct {
	*mock.Call
}

// PasswordHash is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.AdminID
func (_e *AdminRepository_Expecter) PasswordHash(ctx interface{}, id interface{}) *AdminRepository_PasswordHash_Call {
	return &AdminRepository_PasswordHash_Call{Call: _e.mock.On("PasswordHash", ctx, id)}
}

func (_c *AdminRepository_PasswordHash_Call) Run(run func(ctx context.Context, id domain.AdminID)) *AdminRepository_PasswordHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AdminID
		if args[1] != nil {
			arg1 = args[1].(domain.AdminID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AdminRepository_PasswordHash_Call) Return(bytes []byte, err error) *AdminRepository_PasswordHash_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *AdminRepository_PasswordHash_Call) RunAndReturn(run func(ctx context.Context, id domain.AdminID) ([]byte, error)) *AdminRepository_PasswordHash_Call {
	_c.Call.Return(run)
	return _c
}

// PendingVerifications provides a mock function for the type AdminRepository
func (_mock *AdminRepository) PendingVerifications(ctx context.Context) ([]port.VerificationRequest, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PendingVerifications")
	}

	var r0 []port.VerificationRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]port.VerificationRequest, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []port.VerificationRequest); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.VerificationRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AdminRepository_PendingVerifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PendingVerifications'
type AdminRepository_PendingVerifications_Call struct {
	*mock.Call
}

// PendingVerifications is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AdminRepository_Expecter) PendingVerifications(ctx interface{}) *AdminRepository_PendingVerifications_Call {
	return &AdminRepository_PendingVerifications_Call{Call: _e.mock.On("PendingVerifications", ctx)}
}

func (_c *AdminRepository_PendingVerifications_Call) Run(run func(ctx context.Context)) *AdminRepository_PendingVerifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AdminRepository_PendingVerifications_Call) Return(verificationRequests []port.VerificationRequest, err error) *AdminRepository_PendingVerifications_Call {
	_c.Call.Return(verificationRequests, err)
	return _c
}

func (_c *AdminRepository_PendingVerifications_Call) RunAndReturn(run func(ctx context.Context) ([]port.VerificationRequest, error)) *AdminRepository_PendingVerifications_Call {
	_c.Call.Return(run)
	return _c
}

// SeedAdmin provides a mock function for the type AdminRepository
func (_mock *AdminRepository) SeedAdmin(ctx context.Context, email string, passwordHash []byte) (bool, error) {
	ret := _mock.Called(ctx, email, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for SeedAdmin")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) (bool, error)); ok {
		return returnFunc(ctx, email, passwordHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) bool); ok {
		r0 = returnFunc(ctx, email, passwordHash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, email, passwordHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AdminRepository_SeedAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SeedAdmin'
type AdminRepository_SeedAdmin_Call struct {
	*mock.Call
}

// SeedAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - passwordHash []byte
func (_e *AdminRepository_Expecter) SeedAdmin(ctx interface{}, email interface{}, passwordHash interface{}) *AdminRepository_SeedAdmin_Call {
	return &AdminRepository_SeedAdmin_Call{Call: _e.mock.On("SeedAdmin", ctx, email, passwordHash)}
}

func (_c *AdminRepository_SeedAdmin_Call) Run(run func(ctx context.Context, email string, passwordHash []byte)) *AdminRepository_SeedAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AdminRepository_SeedAdmin_Call) Return(b bool, err error) *AdminRepository_SeedAdmin_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *AdminRepository_SeedAdmin_Call) RunAndReturn(run func(ctx context.Context, email string, passwordHash []byte) (bool, error)) *AdminRepository_SeedAdmin_Call {
	_c.Call.Return(run)
	return _c
}
