// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewAdminService creates a new instance of AdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminService {
	mock := &AdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AdminService is an autogenerated mock type for the AdminService type
type AdminService struct {
	mock.Mock
}

type AdminService_Expecter struct {
	mock *mock.Mock
}

func (_m *AdminService) EXPECT() *AdminService_Expecter {
	return &AdminService_Expecter{mock: &_m.Mock}
}

// DecideReevaluation provides a mock function for the type AdminService
func (_mock *AdminService) DecideReevaluation(ctx context.Context, p domain.Principal, id domain.RequestID, accept bool, reason string) error {
	ret := _mock.Called(ctx, p, id, accept, reason)

	if len(ret) == 0 {
		panic("no return value specified for DecideReevaluation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.RequestID, bool, string) error); ok {
		r0 = returnFunc(ctx, p, id, accept, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AdminService_DecideReevaluation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecideReevaluation'
type AdminService_DecideReevaluation_Call struct {
	*mock.Call
}

// DecideReevaluation is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - id domain.RequestID
//   - accept bool
//   - reason string
func (_e *AdminService_Expecter) DecideReevaluation(ctx interface{}, p interface{}, id interface{}, accept interface{}, reason interface{}) *AdminService_DecideReevaluation_Call {
	return &AdminService_DecideReevaluation_Call{Call: _e.mock.On("DecideReevaluation", ctx, p, id, accept, reason)}
}

func (_c *AdminService_DecideReevaluation_Call) Run(run func(ctx context.Context, p domain.Principal, id domain.RequestID, accept bool, reason string)) *AdminService_DecideReevaluation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 domain.RequestID
		if args[2] != nil {
			arg2 = args[2].(domain.RequestID)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *AdminService_DecideReevaluation_Call) Return(err error) *AdminService_DecideReevaluation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AdminService_DecideReevaluation_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, id domain.RequestID, accept bool, reason string) error) *AdminService_DecideReevaluation_Call {
	_c.Call.Return(run)
	return _c
}

// DecideSkillRequest provides a mock function for the type AdminService
func (_mock *AdminService) DecideSkillRequest(ctx context.Context, p domain.Principal, id domain.RequestID, approve bool, skill *domain.Skill, reason string) (*domain.Skill, error) {
	ret := _mock.Called(ctx, p, id, approve, skill, reason)

	if len(ret) == 0 {
		panic("no return value specified for DecideSkillRequest")
	}

	var r0 *domain.Skill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.RequestID, bool, *domain.Skill, string) (*domain.Skill, error)); ok {
		return returnFunc(ctx, p, id, approve, skill, reason)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.RequestID, bool, *domain.Skill, string) *domain.Skill); ok {
		r0 = returnFunc(ctx, p, id, approve, skill, reason)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Skill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal, domain.RequestID, bool, *domain.Skill, string) error); ok {
		r1 = returnFunc(ctx, p, id, approve, skill, reason)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AdminService_DecideSkillRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecideSkillRequest'
type AdminService_DecideSkillRequest_Call struct {
	*mock.Call
}

// DecideSkillRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - id domain.RequestID
//   - approve bool
//   - skill *domain.Skill
//   - reason string
func (_e *AdminService_Expecter) DecideSkillRequest(ctx interface{}, p interface{}, id interface{}, approve interface{}, skill interface{}, reason interface{}) *AdminService_DecideSkillRequest_Call {
	return &AdminService_DecideSkillRequest_Call{Call: _e.mock.On("DecideSkillRequest", ctx, p, id, approve, skill, reason)}
}

func (_c *AdminService_DecideSkillRequest_Call) Run(run func(ctx context.Context, p domain.Principal, id domain.RequestID, approve bool, skill *domain.Skill, reason string)) *AdminService_DecideSkillRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 domain.RequestID
		if args[2] != nil {
			arg2 = args[2].(domain.RequestID)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 *domain.Skill
		if args[4] != nil {
			arg4 = args[4].(*domain.Skill)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *AdminService_DecideSkillRequest_Call) Return(skill1 *domain.Skill, err error) *AdminService_DecideSkillRequest_Call {
	_c.Call.Return(skill1, err)
	return _c
}

func (_c *AdminService_DecideSkillRequest_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, id domain.RequestID, approve bool, skill *domain.Skill, reason string) (*domain.Skill, error)) *AdminService_DecideSkillRequest_Call {
	_c.Call.Return(run)
	return _c
}

// DecideVerification provides a mock function for the type AdminService
func (_mock *AdminService) DecideVerification(ctx context.Context, p domain.Principal, id domain.RequestID, approve bool, reason string) error {
	ret := _mock.Called(ctx, p, id, approve, reason)

	if len(ret) == 0 {
		panic("no return value specified for DecideVerification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.RequestID, bool, string) error); ok {
		r0 = returnFunc(ctx, p, id, approve, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AdminService_DecideVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecideVerification'
type AdminService_DecideVerification_Call struct {
	*mock.Call
}

// DecideVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - id domain.RequestID
//   - approve bool
//   - reason string
func (_e *AdminService_Expecter) DecideVerification(ctx interface{}, p interface{}, id interface{}, approve interface{}, reason interface{}) *AdminService_DecideVerification_Call {
	return &AdminService_DecideVerification_Call{Call: _e.mock.On("DecideVerification", ctx, p, id, approve, reason)}
}

func (_c *AdminService_DecideVerification_Call) Run(run func(ctx context.Context, p domain.Principal, id domain.RequestID, approve bool, reason string)) *AdminService_DecideVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 domain.RequestID
		if args[2] != nil {
			arg2 = args[2].(domain.RequestID)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *AdminService_DecideVerification_Call) Return(err error) *AdminService_DecideVerification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AdminService_DecideVerification_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, id domain.RequestID, approve bool, reason string) error) *AdminService_DecideVerification_Call {
	_c.Call.Return(run)
	return _c
}

// PendingReevaluations provides a mock function for the type AdminService
func (_mock *AdminService) PendingReevaluations(ctx context.Context, p domain.Principal) ([]domain.ReevaluationRequest, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for PendingReevaluations")
	}

	var r0 []domain.ReevaluationRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal) ([]domain.ReevaluationRequest, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal) []domain.ReevaluationRequest); ok {
		r0 = returnFunc(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReevaluationRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AdminService_PendingReevaluations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PendingReevaluations'
type AdminService_PendingReevaluations_Call struct {
	*mock.Call
}

// PendingReevaluations is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
func (_e *AdminService_Expecter) PendingReevaluations(ctx interface{}, p interface{}) *AdminService_PendingReevaluations_Call {
	return &AdminService_PendingReevaluations_Call{Call: _e.mock.On("PendingReevaluations", ctx, p)}
}

func (_c *AdminService_PendingReevaluations_Call) Run(run func(ctx context.Context, p domain.Principal)) *AdminService_PendingReevaluations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AdminService_PendingReevaluations_Call) Return(reevaluationRequests []domain.ReevaluationRequest, err error) *AdminService_PendingReevaluations_Call {
	_c.Call.Return(reevaluationRequests, err)
	return _c
}

func (_c *AdminService_PendingReevaluations_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal) ([]domain.ReevaluationRequest, error)) *AdminService_PendingReevaluations_Call {
	_c.Call.Return(run)
	return _c
}

// PendingSkillRequests provides a mock function for the type AdminService
func (_mock *AdminService) PendingSkillRequests(ctx context.Context, p domain.Principal, status string) ([]port.SkillRequest, error) {
	ret := _mock.Called(ctx, p, status)

	if len(ret) == 0 {
		panic("no return value specified for PendingSkillRequests")
	}

	var r0 []port.SkillRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, string) ([]port.SkillRequest, error)); ok {
		return returnFunc(ctx, p, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, string) []port.SkillRequest); ok {
		r0 = returnFunc(ctx, p, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.SkillRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal, string) error); ok {
		r1 = returnFunc(ctx, p, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AdminService_PendingSkillRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PendingSkillRequests'
type AdminService_PendingSkillRequests_Call struct {
	*mock.Call
}

// PendingSkillRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - status string
func (_e *AdminService_Expecter) PendingSkillRequests(ctx interface{}, p interface{}, status interface{}) *AdminService_PendingSkillRequests_Call {
	return &AdminService_PendingSkillRequests_Call{Call: _e.mock.On("PendingSkillRequests", ctx, p, status)}
}

func (_c *AdminService_PendingSkillRequests_Call) Run(run func(ctx context.Context, p domain.Principal, status string)) *AdminService_PendingSkillRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AdminService_PendingSkillRequests_Call) Return(skillRequests []port.SkillRequest, err error) *AdminService_PendingSkillRequests_Call {
	_c.Call.Return(skillRequests, err)
	return _c
}

func (_c *AdminService_PendingSkillRequests_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, status string) ([]port.SkillRequest, error)) *AdminService_PendingSkillRequests_Call {
	_c.Call.Return(run)
	return _c
}

// PendingVerifications provides a mock function for the type AdminService
func (_mock *AdminService) PendingVerifications(ctx context.Context, p domain.Principal) ([]port.VerificationRequest, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for PendingVerifications")
	}

	var r0 []port.VerificationRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal) ([]port.VerificationRequest, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal) []port.VerificationRequest); ok {
		r0 = returnFunc(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.VerificationRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AdminService_PendingVerifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PendingVerifications'
type AdminService_PendingVerifications_Call struct {
	*mock.Call
}

// PendingVerifications is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
func (_e *AdminService_Expecter) PendingVerifications(ctx interface{}, p interface{}) *AdminService_PendingVerifications_Call {
	return &AdminService_PendingVerifications_Call{Call: _e.mock.On("PendingVerifications", ctx, p)}
}

func (_c *AdminService_PendingVerifications_Call) Run(run func(ctx context.Context, p domain.Principal)) *AdminService_PendingVerifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AdminService_PendingVerifications_Call) Return(verificationRequests []port.VerificationRequest, err error) *AdminService_PendingVerifications_Call {
	_c.Call.Return(verificationRequests, err)
	return _c
}

func (_c *AdminService_PendingVerifications_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal) ([]port.VerificationRequest, error)) *AdminService_PendingVerifications_Call {
	_c.Call.Return(run)
	return _c
}
