// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewAIClient creates a new instance of AIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AIClient {
	mock := &AIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AIClient is an autogenerated mock type for the AIClient type
type AIClient struct {
	mock.Mock
}

type AIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *AIClient) EXPECT() *AIClient_Expecter {
	return &AIClient_Expecter{mock: &_m.Mock}
}

// Judge provides a mock function for the type AIClient
func (_mock *AIClient) Judge(ctx context.Context, req port.JudgeRequest) (*port.JudgeResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Judge")
	}

	var r0 *port.JudgeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.JudgeRequest) (*port.JudgeResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.JudgeRequest) *port.JudgeResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.JudgeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, port.JudgeRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AIClient_Judge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Judge'
type AIClient_Judge_Call struct {
	*mock.Call
}

// Judge is a helper method to define mock.On call
//   - ctx context.Context
//   - req port.JudgeRequest
func (_e *AIClient_Expecter) Judge(ctx interface{}, req interface{}) *AIClient_Judge_Call {
	return &AIClient_Judge_Call{Call: _e.mock.On("Judge", ctx, req)}
}

func (_c *AIClient_Judge_Call) Run(run func(ctx context.Context, req port.JudgeRequest)) *AIClient_Judge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.JudgeRequest
		if args[1] != nil {
			arg1 = args[1].(port.JudgeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AIClient_Judge_Call) Return(judgeResponse *port.JudgeResponse, err error) *AIClient_Judge_Call {
	_c.Call.Return(judgeResponse, err)
	return _c
}

func (_c *AIClient_Judge_Call) RunAndReturn(run func(ctx context.Context, req port.JudgeRequest) (*port.JudgeResponse, error)) *AIClient_Judge_Call {
	_c.Call.Return(run)
	return _c
}
