// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewBroker creates a new instance of Broker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBroker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Broker {
	mock := &Broker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Broker is an autogenerated mock type for the Broker type
type Broker struct {
	mock.Mock
}

type Broker_Expecter struct {
	mock *mock.Mock
}

func (_m *Broker) EXPECT() *Broker_Expecter {
	return &Broker_Expecter{mock: &_m.Mock}
}

// Ack provides a mock function for the type Broker
func (_mock *Broker) Ack(ctx context.Context, tx port.Tx, id domain.JobID) error {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Ack")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.JobID) error); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Broker_Ack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ack'
type Broker_Ack_Call struct {
	*mock.Call
}

// Ack is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - id domain.JobID
func (_e *Broker_Expecter) Ack(ctx interface{}, tx interface{}, id interface{}) *Broker_Ack_Call {
	return &Broker_Ack_Call{Call: _e.mock.On("Ack", ctx, tx, id)}
}

func (_c *Broker_Ack_Call) Run(run func(ctx context.Context, tx port.Tx, id domain.JobID)) *Broker_Ack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 domain.JobID
		if args[2] != nil {
			arg2 = args[2].(domain.JobID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Broker_Ack_Call) Return(err error) *Broker_Ack_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Broker_Ack_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, id domain.JobID) error) *Broker_Ack_Call {
	_c.Call.Return(run)
	return _c
}

// Consume provides a mock function for the type Broker
func (_mock *Broker) Consume(ctx context.Context, lease time.Duration, limit int) ([]port.Message, error) {
	ret := _mock.Called(ctx, lease, limit)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 []port.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, int) ([]port.Message, error)); ok {
		return returnFunc(ctx, lease, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, int) []port.Message); ok {
		r0 = returnFunc(ctx, lease, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration, int) error); ok {
		r1 = returnFunc(ctx, lease, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Broker_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type Broker_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - lease time.Duration
//   - limit int
func (_e *Broker_Expecter) Consume(ctx interface{}, lease interface{}, limit interface{}) *Broker_Consume_Call {
	return &Broker_Consume_Call{Call: _e.mock.On("Consume", ctx, lease, limit)}
}

func (_c *Broker_Consume_Call) Run(run func(ctx context.Context, lease time.Duration, limit int)) *Broker_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Broker_Consume_Call) Return(messages []port.Message, err error) *Broker_Consume_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *Broker_Consume_Call) RunAndReturn(run func(ctx context.Context, lease time.Duration, limit int) ([]port.Message, error)) *Broker_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// ExtendLease provides a mock function for the type Broker
func (_mock *Broker) ExtendLease(ctx context.Context, id domain.JobID, by time.Duration) error {
	ret := _mock.Called(ctx, id, by)

	if len(ret) == 0 {
		panic("no return value specified for ExtendLease")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.JobID, time.Duration) error); ok {
		r0 = returnFunc(ctx, id, by)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Broker_ExtendLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtendLease'
type Broker_ExtendLease_Call struct {
	*mock.Call
}

// ExtendLease is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.JobID
//   - by time.Duration
func (_e *Broker_Expecter) ExtendLease(ctx interface{}, id interface{}, by interface{}) *Broker_ExtendLease_Call {
	return &Broker_ExtendLease_Call{Call: _e.mock.On("ExtendLease", ctx, id, by)}
}

func (_c *Broker_ExtendLease_Call) Run(run func(ctx context.Context, id domain.JobID, by time.Duration)) *Broker_ExtendLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.JobID
		if args[1] != nil {
			arg1 = args[1].(domain.JobID)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Broker_ExtendLease_Call) Return(err error) *Broker_ExtendLease_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Broker_ExtendLease_Call) RunAndReturn(run func(ctx context.Context, id domain.JobID, by time.Duration) error) *Broker_ExtendLease_Call {
	_c.Call.Return(run)
	return _c
}

// Nack provides a mock function for the type Broker
func (_mock *Broker) Nack(ctx context.Context, id domain.JobID, reason string) error {
	ret := _mock.Called(ctx, id, reason)

	if len(ret) == 0 {
		panic("no return value specified for Nack")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.JobID, string) error); ok {
		r0 = returnFunc(ctx, id, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Broker_Nack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Nack'
type Broker_Nack_Call struct {
	*mock.Call
}

// Nack is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.JobID
//   - reason string
func (_e *Broker_Expecter) Nack(ctx interface{}, id interface{}, reason interface{}) *Broker_Nack_Call {
	return &Broker_Nack_Call{Call: _e.mock.On("Nack", ctx, id, reason)}
}

func (_c *Broker_Nack_Call) Run(run func(ctx context.Context, id domain.JobID, reason string)) *Broker_Nack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.JobID
		if args[1] != nil {
			arg1 = args[1].(domain.JobID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Broker_Nack_Call) Return(err error) *Broker_Nack_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Broker_Nack_Call) RunAndReturn(run func(ctx context.Context, id domain.JobID, reason string) error) *Broker_Nack_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type Broker
func (_mock *Broker) Publish(ctx context.Context, tx port.Tx, msg port.Message) error {
	ret := _mock.Called(ctx, tx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, port.Message) error); ok {
		r0 = returnFunc(ctx, tx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Broker_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type Broker_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - msg port.Message
func (_e *Broker_Expecter) Publish(ctx interface{}, tx interface{}, msg interface{}) *Broker_Publish_Call {
	return &Broker_Publish_Call{Call: _e.mock.On("Publish", ctx, tx, msg)}
}

func (_c *Broker_Publish_Call) Run(run func(ctx context.Context, tx port.Tx, msg port.Message)) *Broker_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 port.Message
		if args[2] != nil {
			arg2 = args[2].(port.Message)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Broker_Publish_Call) Return(err error) *Broker_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Broker_Publish_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, msg port.Message) error) *Broker_Publish_Call {
	_c.Call.Return(run)
	return _c
}
