// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewContactRepository creates a new instance of ContactRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContactRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContactRepository {
	mock := &ContactRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ContactRepository is an autogenerated mock type for the ContactRepository type
type ContactRepository struct {
	mock.Mock
}

type ContactRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ContactRepository) EXPECT() *ContactRepository_Expecter {
	return &ContactRepository_Expecter{mock: &_m.Mock}
}

// ByID provides a mock function for the type ContactRepository
func (_mock *ContactRepository) ByID(ctx context.Context, id domain.ContactID) (*domain.ContactRequest, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 *domain.ContactRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ContactID) (*domain.ContactRequest, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ContactID) *domain.ContactRequest); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ContactRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ContactID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ContactRepository_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type ContactRepository_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ContactID
func (_e *ContactRepository_Expecter) ByID(ctx interface{}, id interface{}) *ContactRepository_ByID_Call {
	return &ContactRepository_ByID_Call{Call: _e.mock.On("ByID", ctx, id)}
}

func (_c *ContactRepository_ByID_Call) Run(run func(ctx context.Context, id domain.ContactID)) *ContactRepository_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ContactID
		if args[1] != nil {
			arg1 = args[1].(domain.ContactID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ContactRepository_ByID_Call) Return(contactRequest *domain.ContactRequest, err error) *ContactRepository_ByID_Call {
	_c.Call.Return(contactRequest, err)
	return _c
}

func (_c *ContactRepository_ByID_Call) RunAndReturn(run func(ctx context.Context, id domain.ContactID) (*domain.ContactRequest, error)) *ContactRepository_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// ExpireStale provides a mock function for the type ContactRepository
func (_mock *ContactRepository) ExpireStale(ctx context.Context, now time.Time) (int, error) {
	ret := _mock.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for ExpireStale")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (int, error)); ok {
		return returnFunc(ctx, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) int); ok {
		r0 = returnFunc(ctx, now)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ContactRepository_ExpireStale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpireStale'
type ContactRepository_ExpireStale_Call struct {
	*mock.Call
}

// ExpireStale is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
func (_e *ContactRepository_Expecter) ExpireStale(ctx interface{}, now interface{}) *ContactRepository_ExpireStale_Call {
	return &ContactRepository_ExpireStale_Call{Call: _e.mock.On("ExpireStale", ctx, now)}
}

func (_c *ContactRepository_ExpireStale_Call) Run(run func(ctx context.Context, now time.Time)) *ContactRepository_ExpireStale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ContactRepository_ExpireStale_Call) Return(n int, err error) *ContactRepository_ExpireStale_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *ContactRepository_ExpireStale_Call) RunAndReturn(run func(ctx context.Context, now time.Time) (int, error)) *ContactRepository_ExpireStale_Call {
	_c.Call.Return(run)
	return _c
}

// ListForShortlist provides a mock function for the type ContactRepository
func (_mock *ContactRepository) ListForShortlist(ctx context.Context, id domain.ShortlistID) ([]domain.ContactRequest, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ListForShortlist")
	}

	var r0 []domain.ContactRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ShortlistID) ([]domain.ContactRequest, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ShortlistID) []domain.ContactRequest); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ContactRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ShortlistID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ContactRepository_ListForShortlist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListForShortlist'
type ContactRepository_ListForShortlist_Call struct {
	*mock.Call
}

// ListForShortlist is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ShortlistID
func (_e *ContactRepository_Expecter) ListForShortlist(ctx interface{}, id interface{}) *ContactRepository_ListForShortlist_Call {
	return &ContactRepository_ListForShortlist_Call{Call: _e.mock.On("ListForShortlist", ctx, id)}
}

func (_c *ContactRepository_ListForShortlist_Call) Run(run func(ctx context.Context, id domain.ShortlistID)) *ContactRepository_ListForShortlist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ShortlistID
		if args[1] != nil {
			arg1 = args[1].(domain.ShortlistID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ContactRepository_ListForShortlist_Call) Return(contactRequests []domain.ContactRequest, err error) *ContactRepository_ListForShortlist_Call {
	_c.Call.Return(contactRequests, err)
	return _c
}

func (_c *ContactRepository_ListForShortlist_Call) RunAndReturn(run func(ctx context.Context, id domain.ShortlistID) ([]domain.ContactRequest, error)) *ContactRepository_ListForShortlist_Call {
	_c.Call.Return(run)
	return _c
}

// ListForUser provides a mock function for the type ContactRepository
func (_mock *ContactRepository) ListForUser(ctx context.Context, id domain.UserID, status *domain.ContactRequestStatus) ([]domain.ContactRequest, error) {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for ListForUser")
	}

	var r0 []domain.ContactRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, *domain.ContactRequestStatus) ([]domain.ContactRequest, error)); ok {
		return returnFunc(ctx, id, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, *domain.ContactRequestStatus) []domain.ContactRequest); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ContactRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, *domain.ContactRequestStatus) error); ok {
		r1 = returnFunc(ctx, id, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ContactRepository_ListForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListForUser'
type ContactRepository_ListForUser_Call struct {
	*mock.Call
}

// ListForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.UserID
//   - status *domain.ContactRequestStatus
func (_e *ContactRepository_Expecter) ListForUser(ctx interface{}, id interface{}, status interface{}) *ContactRepository_ListForUser_Call {
	return &ContactRepository_ListForUser_Call{Call: _e.mock.On("ListForUser", ctx, id, status)}
}

func (_c *ContactRepository_ListForUser_Call) Run(run func(ctx context.Context, id domain.UserID, status *domain.ContactRequestStatus)) *ContactRepository_ListForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 *domain.ContactRequestStatus
		if args[2] != nil {
			arg2 = args[2].(*domain.ContactRequestStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ContactRepository_ListForUser_Call) Return(contactRequests []domain.ContactRequest, err error) *ContactRepository_ListForUser_Call {
	_c.Call.Return(contactRequests, err)
	return _c
}

func (_c *ContactRepository_ListForUser_Call) RunAndReturn(run func(ctx context.Context, id domain.UserID, status *domain.ContactRequestStatus) ([]domain.ContactRequest, error)) *ContactRepository_ListForUser_Call {
	_c.Call.Return(run)
	return _c
}

// Respond provides a mock function for the type ContactRepository
func (_mock *ContactRepository) Respond(ctx context.Context, tx port.Tx, id domain.ContactID, accept bool, at time.Time) (*domain.ContactRequest, error) {
	ret := _mock.Called(ctx, tx, id, accept, at)

	if len(ret) == 0 {
		panic("no return value specified for Respond")
	}

	var r0 *domain.ContactRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.ContactID, bool, time.Time) (*domain.ContactRequest, error)); ok {
		return returnFunc(ctx, tx, id, accept, at)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.ContactID, bool, time.Time) *domain.ContactRequest); ok {
		r0 = returnFunc(ctx, tx, id, accept, at)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ContactRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, port.Tx, domain.ContactID, bool, time.Time) error); ok {
		r1 = returnFunc(ctx, tx, id, accept, at)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ContactRepository_Respond_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Respond'
type ContactRepository_Respond_Call struct {
	*mock.Call
}

// Respond is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - id domain.ContactID
//   - accept bool
//   - at time.Time
func (_e *ContactRepository_Expecter) Respond(ctx interface{}, tx interface{}, id interface{}, accept interface{}, at interface{}) *ContactRepository_Respond_Call {
	return &ContactRepository_Respond_Call{Call: _e.mock.On("Respond", ctx, tx, id, accept, at)}
}

func (_c *ContactRepository_Respond_Call) Run(run func(ctx context.Context, tx port.Tx, id domain.ContactID, accept bool, at time.Time)) *ContactRepository_Respond_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 domain.ContactID
		if args[2] != nil {
			arg2 = args[2].(domain.ContactID)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ContactRepository_Respond_Call) Return(contactRequest *domain.ContactRequest, err error) *ContactRepository_Respond_Call {
	_c.Call.Return(contactRequest, err)
	return _c
}

func (_c *ContactRepository_Respond_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, id domain.ContactID, accept bool, at time.Time) (*domain.ContactRequest, error)) *ContactRepository_Respond_Call {
	_c.Call.Return(run)
	return _c
}
