// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// Routes provides a mock function for the type Controller
func (_mock *Controller) Routes() (string, http.Handler) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Routes")
	}

	var r0 string
	var r1 http.Handler
	if returnFunc, ok := ret.Get(0).(func() (string, http.Handler)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() http.Handler); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(http.Handler)
		}
	}
	return r0, r1
}

// Controller_Routes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Routes'
type Controller_Routes_Call struct {
	*mock.Call
}

// Routes is a helper method to define mock.On call
func (_e *Controller_Expecter) Routes() *Controller_Routes_Call {
	return &Controller_Routes_Call{Call: _e.mock.On("Routes")}
}

func (_c *Controller_Routes_Call) Run(run func()) *Controller_Routes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_Routes_Call) Return(prefix string, handler http.Handler) *Controller_Routes_Call {
	_c.Call.Return(prefix, handler)
	return _c
}

func (_c *Controller_Routes_Call) RunAndReturn(run func() (string, http.Handler)) *Controller_Routes_Call {
	_c.Call.Return(run)
	return _c
}
