// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewControlPlane creates a new instance of ControlPlane. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewControlPlane(t interface {
	mock.TestingT
	Cleanup(func())
}) *ControlPlane {
	mock := &ControlPlane{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ControlPlane is an autogenerated mock type for the ControlPlane type
type ControlPlane struct {
	mock.Mock
}

type ControlPlane_Expecter struct {
	mock *mock.Mock
}

func (_m *ControlPlane) EXPECT() *ControlPlane_Expecter {
	return &ControlPlane_Expecter{mock: &_m.Mock}
}

// ListenAndServe provides a mock function for the type ControlPlane
func (_mock *ControlPlane) ListenAndServe(addr string) error {
	ret := _mock.Called(addr)

	if len(ret) == 0 {
		panic("no return value specified for ListenAndServe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(addr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ControlPlane_ListenAndServe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListenAndServe'
type ControlPlane_ListenAndServe_Call struct {
	*mock.Call
}

// ListenAndServe is a helper method to define mock.On call
//   - addr string
func (_e *ControlPlane_Expecter) ListenAndServe(addr interface{}) *ControlPlane_ListenAndServe_Call {
	return &ControlPlane_ListenAndServe_Call{Call: _e.mock.On("ListenAndServe", addr)}
}

func (_c *ControlPlane_ListenAndServe_Call) Run(run func(addr string)) *ControlPlane_ListenAndServe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ControlPlane_ListenAndServe_Call) Return(err error) *ControlPlane_ListenAndServe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ControlPlane_ListenAndServe_Call) RunAndReturn(run func(addr string) error) *ControlPlane_ListenAndServe_Call {
	_c.Call.Return(run)
	return _c
}

// PrimeFake provides a mock function for the type ControlPlane
func (_mock *ControlPlane) PrimeFake(kind string, payload []byte) error {
	ret := _mock.Called(kind, payload)

	if len(ret) == 0 {
		panic("no return value specified for PrimeFake")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(kind, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ControlPlane_PrimeFake_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrimeFake'
type ControlPlane_PrimeFake_Call struct {
	*mock.Call
}

// PrimeFake is a helper method to define mock.On call
//   - kind string
//   - payload []byte
func (_e *ControlPlane_Expecter) PrimeFake(kind interface{}, payload interface{}) *ControlPlane_PrimeFake_Call {
	return &ControlPlane_PrimeFake_Call{Call: _e.mock.On("PrimeFake", kind, payload)}
}

func (_c *ControlPlane_PrimeFake_Call) Run(run func(kind string, payload []byte)) *ControlPlane_PrimeFake_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ControlPlane_PrimeFake_Call) Return(err error) *ControlPlane_PrimeFake_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ControlPlane_PrimeFake_Call) RunAndReturn(run func(kind string, payload []byte) error) *ControlPlane_PrimeFake_Call {
	_c.Call.Return(run)
	return _c
}

// RunAction provides a mock function for the type ControlPlane
func (_mock *ControlPlane) RunAction(name string, payload []byte) ([]byte, error) {
	ret := _mock.Called(name, payload)

	if len(ret) == 0 {
		panic("no return value specified for RunAction")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) ([]byte, error)); ok {
		return returnFunc(name, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []byte) []byte); ok {
		r0 = returnFunc(name, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = returnFunc(name, payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ControlPlane_RunAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunAction'
type ControlPlane_RunAction_Call struct {
	*mock.Call
}

// RunAction is a helper method to define mock.On call
//   - name string
//   - payload []byte
func (_e *ControlPlane_Expecter) RunAction(name interface{}, payload interface{}) *ControlPlane_RunAction_Call {
	return &ControlPlane_RunAction_Call{Call: _e.mock.On("RunAction", name, payload)}
}

func (_c *ControlPlane_RunAction_Call) Run(run func(name string, payload []byte)) *ControlPlane_RunAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ControlPlane_RunAction_Call) Return(bytes []byte, err error) *ControlPlane_RunAction_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *ControlPlane_RunAction_Call) RunAndReturn(run func(name string, payload []byte) ([]byte, error)) *ControlPlane_RunAction_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type ControlPlane
func (_mock *ControlPlane) Shutdown() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ControlPlane_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type ControlPlane_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *ControlPlane_Expecter) Shutdown() *ControlPlane_Shutdown_Call {
	return &ControlPlane_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *ControlPlane_Shutdown_Call) Run(run func()) *ControlPlane_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ControlPlane_Shutdown_Call) Return(err error) *ControlPlane_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ControlPlane_Shutdown_Call) RunAndReturn(run func() error) *ControlPlane_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}
