// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewContactService creates a new instance of ContactService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContactService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContactService {
	mock := &ContactService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ContactService is an autogenerated mock type for the ContactService type
type ContactService struct {
	mock.Mock
}

type ContactService_Expecter struct {
	mock *mock.Mock
}

func (_m *ContactService) EXPECT() *ContactService_Expecter {
	return &ContactService_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type ContactService
func (_mock *ContactService) List(ctx context.Context, id domain.UserID, status *domain.ContactRequestStatus) ([]domain.ContactRequest, error) {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.ContactRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, *domain.ContactRequestStatus) ([]domain.ContactRequest, error)); ok {
		return returnFunc(ctx, id, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, *domain.ContactRequestStatus) []domain.ContactRequest); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ContactRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, *domain.ContactRequestStatus) error); ok {
		r1 = returnFunc(ctx, id, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ContactService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ContactService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.UserID
//   - status *domain.ContactRequestStatus
func (_e *ContactService_Expecter) List(ctx interface{}, id interface{}, status interface{}) *ContactService_List_Call {
	return &ContactService_List_Call{Call: _e.mock.On("List", ctx, id, status)}
}

func (_c *ContactService_List_Call) Run(run func(ctx context.Context, id domain.UserID, status *domain.ContactRequestStatus)) *ContactService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 *domain.ContactRequestStatus
		if args[2] != nil {
			arg2 = args[2].(*domain.ContactRequestStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ContactService_List_Call) Return(contactRequests []domain.ContactRequest, err error) *ContactService_List_Call {
	_c.Call.Return(contactRequests, err)
	return _c
}

func (_c *ContactService_List_Call) RunAndReturn(run func(ctx context.Context, id domain.UserID, status *domain.ContactRequestStatus) ([]domain.ContactRequest, error)) *ContactService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Respond provides a mock function for the type ContactService
func (_mock *ContactService) Respond(ctx context.Context, id domain.UserID, contact domain.ContactID, accept bool) (*domain.ContactRequest, error) {
	ret := _mock.Called(ctx, id, contact, accept)

	if len(ret) == 0 {
		panic("no return value specified for Respond")
	}

	var r0 *domain.ContactRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, domain.ContactID, bool) (*domain.ContactRequest, error)); ok {
		return returnFunc(ctx, id, contact, accept)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, domain.ContactID, bool) *domain.ContactRequest); ok {
		r0 = returnFunc(ctx, id, contact, accept)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ContactRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, domain.ContactID, bool) error); ok {
		r1 = returnFunc(ctx, id, contact, accept)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ContactService_Respond_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Respond'
type ContactService_Respond_Call struct {
	*mock.Call
}

// Respond is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.UserID
//   - contact domain.ContactID
//   - accept bool
func (_e *ContactService_Expecter) Respond(ctx interface{}, id interface{}, contact interface{}, accept interface{}) *ContactService_Respond_Call {
	return &ContactService_Respond_Call{Call: _e.mock.On("Respond", ctx, id, contact, accept)}
}

func (_c *ContactService_Respond_Call) Run(run func(ctx context.Context, id domain.UserID, contact domain.ContactID, accept bool)) *ContactService_Respond_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 domain.ContactID
		if args[2] != nil {
			arg2 = args[2].(domain.ContactID)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ContactService_Respond_Call) Return(contactRequest *domain.ContactRequest, err error) *ContactService_Respond_Call {
	_c.Call.Return(contactRequest, err)
	return _c
}

func (_c *ContactService_Respond_Call) RunAndReturn(run func(ctx context.Context, id domain.UserID, contact domain.ContactID, accept bool) (*domain.ContactRequest, error)) *ContactService_Respond_Call {
	_c.Call.Return(run)
	return _c
}
