// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewDiscoveryService creates a new instance of DiscoveryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDiscoveryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DiscoveryService {
	mock := &DiscoveryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DiscoveryService is an autogenerated mock type for the DiscoveryService type
type DiscoveryService struct {
	mock.Mock
}

type DiscoveryService_Expecter struct {
	mock *mock.Mock
}

func (_m *DiscoveryService) EXPECT() *DiscoveryService_Expecter {
	return &DiscoveryService_Expecter{mock: &_m.Mock}
}

// DeleteSavedSearch provides a mock function for the type DiscoveryService
func (_mock *DiscoveryService) DeleteSavedSearch(ctx context.Context, p domain.Principal, id domain.SavedSearchID) error {
	ret := _mock.Called(ctx, p, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSavedSearch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.SavedSearchID) error); ok {
		r0 = returnFunc(ctx, p, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DiscoveryService_DeleteSavedSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSavedSearch'
type DiscoveryService_DeleteSavedSearch_Call struct {
	*mock.Call
}

// DeleteSavedSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - id domain.SavedSearchID
func (_e *DiscoveryService_Expecter) DeleteSavedSearch(ctx interface{}, p interface{}, id interface{}) *DiscoveryService_DeleteSavedSearch_Call {
	return &DiscoveryService_DeleteSavedSearch_Call{Call: _e.mock.On("DeleteSavedSearch", ctx, p, id)}
}

func (_c *DiscoveryService_DeleteSavedSearch_Call) Run(run func(ctx context.Context, p domain.Principal, id domain.SavedSearchID)) *DiscoveryService_DeleteSavedSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 domain.SavedSearchID
		if args[2] != nil {
			arg2 = args[2].(domain.SavedSearchID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DiscoveryService_DeleteSavedSearch_Call) Return(err error) *DiscoveryService_DeleteSavedSearch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DiscoveryService_DeleteSavedSearch_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, id domain.SavedSearchID) error) *DiscoveryService_DeleteSavedSearch_Call {
	_c.Call.Return(run)
	return _c
}

// Leaderboard provides a mock function for the type DiscoveryService
func (_mock *DiscoveryService) Leaderboard(ctx context.Context, p domain.Principal, kind domain.LeaderboardKind, skill string) (*domain.Leaderboard, error) {
	ret := _mock.Called(ctx, p, kind, skill)

	if len(ret) == 0 {
		panic("no return value specified for Leaderboard")
	}

	var r0 *domain.Leaderboard
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.LeaderboardKind, string) (*domain.Leaderboard, error)); ok {
		return returnFunc(ctx, p, kind, skill)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.LeaderboardKind, string) *domain.Leaderboard); ok {
		r0 = returnFunc(ctx, p, kind, skill)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Leaderboard)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal, domain.LeaderboardKind, string) error); ok {
		r1 = returnFunc(ctx, p, kind, skill)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DiscoveryService_Leaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Leaderboard'
type DiscoveryService_Leaderboard_Call struct {
	*mock.Call
}

// Leaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - kind domain.LeaderboardKind
//   - skill string
func (_e *DiscoveryService_Expecter) Leaderboard(ctx interface{}, p interface{}, kind interface{}, skill interface{}) *DiscoveryService_Leaderboard_Call {
	return &DiscoveryService_Leaderboard_Call{Call: _e.mock.On("Leaderboard", ctx, p, kind, skill)}
}

func (_c *DiscoveryService_Leaderboard_Call) Run(run func(ctx context.Context, p domain.Principal, kind domain.LeaderboardKind, skill string)) *DiscoveryService_Leaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 domain.LeaderboardKind
		if args[2] != nil {
			arg2 = args[2].(domain.LeaderboardKind)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *DiscoveryService_Leaderboard_Call) Return(leaderboard *domain.Leaderboard, err error) *DiscoveryService_Leaderboard_Call {
	_c.Call.Return(leaderboard, err)
	return _c
}

func (_c *DiscoveryService_Leaderboard_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, kind domain.LeaderboardKind, skill string) (*domain.Leaderboard, error)) *DiscoveryService_Leaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// MyRank provides a mock function for the type DiscoveryService
func (_mock *DiscoveryService) MyRank(ctx context.Context, id domain.UserID) (*domain.Rank, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MyRank")
	}

	var r0 *domain.Rank
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) (*domain.Rank, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) *domain.Rank); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Rank)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DiscoveryService_MyRank_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MyRank'
type DiscoveryService_MyRank_Call struct {
	*mock.Call
}

// MyRank is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.UserID
func (_e *DiscoveryService_Expecter) MyRank(ctx interface{}, id interface{}) *DiscoveryService_MyRank_Call {
	return &DiscoveryService_MyRank_Call{Call: _e.mock.On("MyRank", ctx, id)}
}

func (_c *DiscoveryService_MyRank_Call) Run(run func(ctx context.Context, id domain.UserID)) *DiscoveryService_MyRank_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DiscoveryService_MyRank_Call) Return(rank *domain.Rank, err error) *DiscoveryService_MyRank_Call {
	_c.Call.Return(rank, err)
	return _c
}

func (_c *DiscoveryService_MyRank_Call) RunAndReturn(run func(ctx context.Context, id domain.UserID) (*domain.Rank, error)) *DiscoveryService_MyRank_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaySavedSearch provides a mock function for the type DiscoveryService
func (_mock *DiscoveryService) ReplaySavedSearch(ctx context.Context, p domain.Principal, id domain.SavedSearchID) (*domain.SearchResults, error) {
	ret := _mock.Called(ctx, p, id)

	if len(ret) == 0 {
		panic("no return value specified for ReplaySavedSearch")
	}

	var r0 *domain.SearchResults
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.SavedSearchID) (*domain.SearchResults, error)); ok {
		return returnFunc(ctx, p, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.SavedSearchID) *domain.SearchResults); ok {
		r0 = returnFunc(ctx, p, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SearchResults)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal, domain.SavedSearchID) error); ok {
		r1 = returnFunc(ctx, p, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DiscoveryService_ReplaySavedSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaySavedSearch'
type DiscoveryService_ReplaySavedSearch_Call struct {
	*mock.Call
}

// ReplaySavedSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - id domain.SavedSearchID
func (_e *DiscoveryService_Expecter) ReplaySavedSearch(ctx interface{}, p interface{}, id interface{}) *DiscoveryService_ReplaySavedSearch_Call {
	return &DiscoveryService_ReplaySavedSearch_Call{Call: _e.mock.On("ReplaySavedSearch", ctx, p, id)}
}

func (_c *DiscoveryService_ReplaySavedSearch_Call) Run(run func(ctx context.Context, p domain.Principal, id domain.SavedSearchID)) *DiscoveryService_ReplaySavedSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 domain.SavedSearchID
		if args[2] != nil {
			arg2 = args[2].(domain.SavedSearchID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DiscoveryService_ReplaySavedSearch_Call) Return(searchResults *domain.SearchResults, err error) *DiscoveryService_ReplaySavedSearch_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *DiscoveryService_ReplaySavedSearch_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, id domain.SavedSearchID) (*domain.SearchResults, error)) *DiscoveryService_ReplaySavedSearch_Call {
	_c.Call.Return(run)
	return _c
}

// SaveSearch provides a mock function for the type DiscoveryService
func (_mock *DiscoveryService) SaveSearch(ctx context.Context, p domain.Principal, name string, q domain.SearchQuery) (*domain.SavedSearch, error) {
	ret := _mock.Called(ctx, p, name, q)

	if len(ret) == 0 {
		panic("no return value specified for SaveSearch")
	}

	var r0 *domain.SavedSearch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, string, domain.SearchQuery) (*domain.SavedSearch, error)); ok {
		return returnFunc(ctx, p, name, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, string, domain.SearchQuery) *domain.SavedSearch); ok {
		r0 = returnFunc(ctx, p, name, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SavedSearch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal, string, domain.SearchQuery) error); ok {
		r1 = returnFunc(ctx, p, name, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DiscoveryService_SaveSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSearch'
type DiscoveryService_SaveSearch_Call struct {
	*mock.Call
}

// SaveSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - name string
//   - q domain.SearchQuery
func (_e *DiscoveryService_Expecter) SaveSearch(ctx interface{}, p interface{}, name interface{}, q interface{}) *DiscoveryService_SaveSearch_Call {
	return &DiscoveryService_SaveSearch_Call{Call: _e.mock.On("SaveSearch", ctx, p, name, q)}
}

func (_c *DiscoveryService_SaveSearch_Call) Run(run func(ctx context.Context, p domain.Principal, name string, q domain.SearchQuery)) *DiscoveryService_SaveSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 domain.SearchQuery
		if args[3] != nil {
			arg3 = args[3].(domain.SearchQuery)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *DiscoveryService_SaveSearch_Call) Return(savedSearch *domain.SavedSearch, err error) *DiscoveryService_SaveSearch_Call {
	_c.Call.Return(savedSearch, err)
	return _c
}

func (_c *DiscoveryService_SaveSearch_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, name string, q domain.SearchQuery) (*domain.SavedSearch, error)) *DiscoveryService_SaveSearch_Call {
	_c.Call.Return(run)
	return _c
}

// SavedSearches provides a mock function for the type DiscoveryService
func (_mock *DiscoveryService) SavedSearches(ctx context.Context, p domain.Principal) ([]domain.SavedSearch, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for SavedSearches")
	}

	var r0 []domain.SavedSearch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal) ([]domain.SavedSearch, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal) []domain.SavedSearch); ok {
		r0 = returnFunc(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SavedSearch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DiscoveryService_SavedSearches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SavedSearches'
type DiscoveryService_SavedSearches_Call struct {
	*mock.Call
}

// SavedSearches is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
func (_e *DiscoveryService_Expecter) SavedSearches(ctx interface{}, p interface{}) *DiscoveryService_SavedSearches_Call {
	return &DiscoveryService_SavedSearches_Call{Call: _e.mock.On("SavedSearches", ctx, p)}
}

func (_c *DiscoveryService_SavedSearches_Call) Run(run func(ctx context.Context, p domain.Principal)) *DiscoveryService_SavedSearches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DiscoveryService_SavedSearches_Call) Return(savedSearchs []domain.SavedSearch, err error) *DiscoveryService_SavedSearches_Call {
	_c.Call.Return(savedSearchs, err)
	return _c
}

func (_c *DiscoveryService_SavedSearches_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal) ([]domain.SavedSearch, error)) *DiscoveryService_SavedSearches_Call {
	_c.Call.Return(run)
	return _c
}

// Scorecard provides a mock function for the type DiscoveryService
func (_mock *DiscoveryService) Scorecard(ctx context.Context, p domain.Principal, target domain.UserID) (*domain.Scorecard, error) {
	ret := _mock.Called(ctx, p, target)

	if len(ret) == 0 {
		panic("no return value specified for Scorecard")
	}

	var r0 *domain.Scorecard
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.UserID) (*domain.Scorecard, error)); ok {
		return returnFunc(ctx, p, target)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.UserID) *domain.Scorecard); ok {
		r0 = returnFunc(ctx, p, target)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Scorecard)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal, domain.UserID) error); ok {
		r1 = returnFunc(ctx, p, target)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DiscoveryService_Scorecard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scorecard'
type DiscoveryService_Scorecard_Call struct {
	*mock.Call
}

// Scorecard is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - target domain.UserID
func (_e *DiscoveryService_Expecter) Scorecard(ctx interface{}, p interface{}, target interface{}) *DiscoveryService_Scorecard_Call {
	return &DiscoveryService_Scorecard_Call{Call: _e.mock.On("Scorecard", ctx, p, target)}
}

func (_c *DiscoveryService_Scorecard_Call) Run(run func(ctx context.Context, p domain.Principal, target domain.UserID)) *DiscoveryService_Scorecard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 domain.UserID
		if args[2] != nil {
			arg2 = args[2].(domain.UserID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DiscoveryService_Scorecard_Call) Return(scorecard *domain.Scorecard, err error) *DiscoveryService_Scorecard_Call {
	_c.Call.Return(scorecard, err)
	return _c
}

func (_c *DiscoveryService_Scorecard_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, target domain.UserID) (*domain.Scorecard, error)) *DiscoveryService_Scorecard_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type DiscoveryService
func (_mock *DiscoveryService) Search(ctx context.Context, p domain.Principal, q domain.SearchQuery) (*domain.SearchResults, error) {
	ret := _mock.Called(ctx, p, q)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *domain.SearchResults
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.SearchQuery) (*domain.SearchResults, error)); ok {
		return returnFunc(ctx, p, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.SearchQuery) *domain.SearchResults); ok {
		r0 = returnFunc(ctx, p, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SearchResults)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal, domain.SearchQuery) error); ok {
		r1 = returnFunc(ctx, p, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DiscoveryService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type DiscoveryService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - q domain.SearchQuery
func (_e *DiscoveryService_Expecter) Search(ctx interface{}, p interface{}, q interface{}) *DiscoveryService_Search_Call {
	return &DiscoveryService_Search_Call{Call: _e.mock.On("Search", ctx, p, q)}
}

func (_c *DiscoveryService_Search_Call) Run(run func(ctx context.Context, p domain.Principal, q domain.SearchQuery)) *DiscoveryService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 domain.SearchQuery
		if args[2] != nil {
			arg2 = args[2].(domain.SearchQuery)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DiscoveryService_Search_Call) Return(searchResults *domain.SearchResults, err error) *DiscoveryService_Search_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *DiscoveryService_Search_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, q domain.SearchQuery) (*domain.SearchResults, error)) *DiscoveryService_Search_Call {
	_c.Call.Return(run)
	return _c
}
