// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewEvaluationService creates a new instance of EvaluationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEvaluationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *EvaluationService {
	mock := &EvaluationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EvaluationService is an autogenerated mock type for the EvaluationService type
type EvaluationService struct {
	mock.Mock
}

type EvaluationService_Expecter struct {
	mock *mock.Mock
}

func (_m *EvaluationService) EXPECT() *EvaluationService_Expecter {
	return &EvaluationService_Expecter{mock: &_m.Mock}
}

// Process provides a mock function for the type EvaluationService
func (_mock *EvaluationService) Process(ctx context.Context, msg port.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EvaluationService_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type EvaluationService_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - msg port.Message
func (_e *EvaluationService_Expecter) Process(ctx interface{}, msg interface{}) *EvaluationService_Process_Call {
	return &EvaluationService_Process_Call{Call: _e.mock.On("Process", ctx, msg)}
}

func (_c *EvaluationService_Process_Call) Run(run func(ctx context.Context, msg port.Message)) *EvaluationService_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Message
		if args[1] != nil {
			arg1 = args[1].(port.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EvaluationService_Process_Call) Return(err error) *EvaluationService_Process_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EvaluationService_Process_Call) RunAndReturn(run func(ctx context.Context, msg port.Message) error) *EvaluationService_Process_Call {
	_c.Call.Return(run)
	return _c
}

// Sweep provides a mock function for the type EvaluationService
func (_mock *EvaluationService) Sweep(ctx context.Context, p domain.Principal, toVersion string, reason string) (int, error) {
	ret := _mock.Called(ctx, p, toVersion, reason)

	if len(ret) == 0 {
		panic("no return value specified for Sweep")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, string, string) (int, error)); ok {
		return returnFunc(ctx, p, toVersion, reason)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, string, string) int); ok {
		r0 = returnFunc(ctx, p, toVersion, reason)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal, string, string) error); ok {
		r1 = returnFunc(ctx, p, toVersion, reason)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EvaluationService_Sweep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sweep'
type EvaluationService_Sweep_Call struct {
	*mock.Call
}

// Sweep is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - toVersion string
//   - reason string
func (_e *EvaluationService_Expecter) Sweep(ctx interface{}, p interface{}, toVersion interface{}, reason interface{}) *EvaluationService_Sweep_Call {
	return &EvaluationService_Sweep_Call{Call: _e.mock.On("Sweep", ctx, p, toVersion, reason)}
}

func (_c *EvaluationService_Sweep_Call) Run(run func(ctx context.Context, p domain.Principal, toVersion string, reason string)) *EvaluationService_Sweep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EvaluationService_Sweep_Call) Return(enqueued int, err error) *EvaluationService_Sweep_Call {
	_c.Call.Return(enqueued, err)
	return _c
}

func (_c *EvaluationService_Sweep_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, toVersion string, reason string) (int, error)) *EvaluationService_Sweep_Call {
	_c.Call.Return(run)
	return _c
}
