// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewGitHubClient creates a new instance of GitHubClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGitHubClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *GitHubClient {
	mock := &GitHubClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GitHubClient is an autogenerated mock type for the GitHubClient type
type GitHubClient struct {
	mock.Mock
}

type GitHubClient_Expecter struct {
	mock *mock.Mock
}

func (_m *GitHubClient) EXPECT() *GitHubClient_Expecter {
	return &GitHubClient_Expecter{mock: &_m.Mock}
}

// AuthorizeURL provides a mock function for the type GitHubClient
func (_mock *GitHubClient) AuthorizeURL(state string) string {
	ret := _mock.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for AuthorizeURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(state)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// GitHubClient_AuthorizeURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizeURL'
type GitHubClient_AuthorizeURL_Call struct {
	*mock.Call
}

// AuthorizeURL is a helper method to define mock.On call
//   - state string
func (_e *GitHubClient_Expecter) AuthorizeURL(state interface{}) *GitHubClient_AuthorizeURL_Call {
	return &GitHubClient_AuthorizeURL_Call{Call: _e.mock.On("AuthorizeURL", state)}
}

func (_c *GitHubClient_AuthorizeURL_Call) Run(run func(state string)) *GitHubClient_AuthorizeURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GitHubClient_AuthorizeURL_Call) Return(s string) *GitHubClient_AuthorizeURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *GitHubClient_AuthorizeURL_Call) RunAndReturn(run func(state string) string) *GitHubClient_AuthorizeURL_Call {
	_c.Call.Return(run)
	return _c
}

// ExchangeCode provides a mock function for the type GitHubClient
func (_mock *GitHubClient) ExchangeCode(ctx context.Context, code string) (*port.GitHubIdentity, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeCode")
	}

	var r0 *port.GitHubIdentity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*port.GitHubIdentity, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *port.GitHubIdentity); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.GitHubIdentity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GitHubClient_ExchangeCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeCode'
type GitHubClient_ExchangeCode_Call struct {
	*mock.Call
}

// ExchangeCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *GitHubClient_Expecter) ExchangeCode(ctx interface{}, code interface{}) *GitHubClient_ExchangeCode_Call {
	return &GitHubClient_ExchangeCode_Call{Call: _e.mock.On("ExchangeCode", ctx, code)}
}

func (_c *GitHubClient_ExchangeCode_Call) Run(run func(ctx context.Context, code string)) *GitHubClient_ExchangeCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GitHubClient_ExchangeCode_Call) Return(gitHubIdentity *port.GitHubIdentity, err error) *GitHubClient_ExchangeCode_Call {
	_c.Call.Return(gitHubIdentity, err)
	return _c
}

func (_c *GitHubClient_ExchangeCode_Call) RunAndReturn(run func(ctx context.Context, code string) (*port.GitHubIdentity, error)) *GitHubClient_ExchangeCode_Call {
	_c.Call.Return(run)
	return _c
}

// PullRequest provides a mock function for the type GitHubClient
func (_mock *GitHubClient) PullRequest(ctx context.Context, owner string, repo string, number int) (*domain.PRFacts, error) {
	ret := _mock.Called(ctx, owner, repo, number)

	if len(ret) == 0 {
		panic("no return value specified for PullRequest")
	}

	var r0 *domain.PRFacts
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) (*domain.PRFacts, error)); ok {
		return returnFunc(ctx, owner, repo, number)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) *domain.PRFacts); ok {
		r0 = returnFunc(ctx, owner, repo, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PRFacts)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = returnFunc(ctx, owner, repo, number)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GitHubClient_PullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullRequest'
type GitHubClient_PullRequest_Call struct {
	*mock.Call
}

// PullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - number int
func (_e *GitHubClient_Expecter) PullRequest(ctx interface{}, owner interface{}, repo interface{}, number interface{}) *GitHubClient_PullRequest_Call {
	return &GitHubClient_PullRequest_Call{Call: _e.mock.On("PullRequest", ctx, owner, repo, number)}
}

func (_c *GitHubClient_PullRequest_Call) Run(run func(ctx context.Context, owner string, repo string, number int)) *GitHubClient_PullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *GitHubClient_PullRequest_Call) Return(pRFacts *domain.PRFacts, err error) *GitHubClient_PullRequest_Call {
	_c.Call.Return(pRFacts, err)
	return _c
}

func (_c *GitHubClient_PullRequest_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, number int) (*domain.PRFacts, error)) *GitHubClient_PullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// Repository provides a mock function for the type GitHubClient
func (_mock *GitHubClient) Repository(ctx context.Context, owner string, repo string) (*domain.RepoFacts, error) {
	ret := _mock.Called(ctx, owner, repo)

	if len(ret) == 0 {
		panic("no return value specified for Repository")
	}

	var r0 *domain.RepoFacts
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.RepoFacts, error)); ok {
		return returnFunc(ctx, owner, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.RepoFacts); ok {
		r0 = returnFunc(ctx, owner, repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RepoFacts)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GitHubClient_Repository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Repository'
type GitHubClient_Repository_Call struct {
	*mock.Call
}

// Repository is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
func (_e *GitHubClient_Expecter) Repository(ctx interface{}, owner interface{}, repo interface{}) *GitHubClient_Repository_Call {
	return &GitHubClient_Repository_Call{Call: _e.mock.On("Repository", ctx, owner, repo)}
}

func (_c *GitHubClient_Repository_Call) Run(run func(ctx context.Context, owner string, repo string)) *GitHubClient_Repository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GitHubClient_Repository_Call) Return(repoFacts *domain.RepoFacts, err error) *GitHubClient_Repository_Call {
	_c.Call.Return(repoFacts, err)
	return _c
}

func (_c *GitHubClient_Repository_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string) (*domain.RepoFacts, error)) *GitHubClient_Repository_Call {
	_c.Call.Return(run)
	return _c
}

// Reviews provides a mock function for the type GitHubClient
func (_mock *GitHubClient) Reviews(ctx context.Context, owner string, repo string, number int) ([]port.Review, error) {
	ret := _mock.Called(ctx, owner, repo, number)

	if len(ret) == 0 {
		panic("no return value specified for Reviews")
	}

	var r0 []port.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) ([]port.Review, error)); ok {
		return returnFunc(ctx, owner, repo, number)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) []port.Review); ok {
		r0 = returnFunc(ctx, owner, repo, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = returnFunc(ctx, owner, repo, number)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GitHubClient_Reviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reviews'
type GitHubClient_Reviews_Call struct {
	*mock.Call
}

// Reviews is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - number int
func (_e *GitHubClient_Expecter) Reviews(ctx interface{}, owner interface{}, repo interface{}, number interface{}) *GitHubClient_Reviews_Call {
	return &GitHubClient_Reviews_Call{Call: _e.mock.On("Reviews", ctx, owner, repo, number)}
}

func (_c *GitHubClient_Reviews_Call) Run(run func(ctx context.Context, owner string, repo string, number int)) *GitHubClient_Reviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *GitHubClient_Reviews_Call) Return(reviews []port.Review, err error) *GitHubClient_Reviews_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *GitHubClient_Reviews_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, number int) ([]port.Review, error)) *GitHubClient_Reviews_Call {
	_c.Call.Return(run)
	return _c
}
