// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewHirerRepository creates a new instance of HirerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHirerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *HirerRepository {
	mock := &HirerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HirerRepository is an autogenerated mock type for the HirerRepository type
type HirerRepository struct {
	mock.Mock
}

type HirerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *HirerRepository) EXPECT() *HirerRepository_Expecter {
	return &HirerRepository_Expecter{mock: &_m.Mock}
}

// ByEmail provides a mock function for the type HirerRepository
func (_mock *HirerRepository) ByEmail(ctx context.Context, email string) (*domain.Hirer, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ByEmail")
	}

	var r0 *domain.Hirer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Hirer, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Hirer); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Hirer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HirerRepository_ByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByEmail'
type HirerRepository_ByEmail_Call struct {
	*mock.Call
}

// ByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *HirerRepository_Expecter) ByEmail(ctx interface{}, email interface{}) *HirerRepository_ByEmail_Call {
	return &HirerRepository_ByEmail_Call{Call: _e.mock.On("ByEmail", ctx, email)}
}

func (_c *HirerRepository_ByEmail_Call) Run(run func(ctx context.Context, email string)) *HirerRepository_ByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HirerRepository_ByEmail_Call) Return(hirer *domain.Hirer, err error) *HirerRepository_ByEmail_Call {
	_c.Call.Return(hirer, err)
	return _c
}

func (_c *HirerRepository_ByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*domain.Hirer, error)) *HirerRepository_ByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ByGitHubUserID provides a mock function for the type HirerRepository
func (_mock *HirerRepository) ByGitHubUserID(ctx context.Context, githubUserID int64) (*domain.Hirer, error) {
	ret := _mock.Called(ctx, githubUserID)

	if len(ret) == 0 {
		panic("no return value specified for ByGitHubUserID")
	}

	var r0 *domain.Hirer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.Hirer, error)); ok {
		return returnFunc(ctx, githubUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.Hirer); ok {
		r0 = returnFunc(ctx, githubUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Hirer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, githubUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HirerRepository_ByGitHubUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByGitHubUserID'
type HirerRepository_ByGitHubUserID_Call struct {
	*mock.Call
}

// ByGitHubUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - githubUserID int64
func (_e *HirerRepository_Expecter) ByGitHubUserID(ctx interface{}, githubUserID interface{}) *HirerRepository_ByGitHubUserID_Call {
	return &HirerRepository_ByGitHubUserID_Call{Call: _e.mock.On("ByGitHubUserID", ctx, githubUserID)}
}

func (_c *HirerRepository_ByGitHubUserID_Call) Run(run func(ctx context.Context, githubUserID int64)) *HirerRepository_ByGitHubUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HirerRepository_ByGitHubUserID_Call) Return(hirer *domain.Hirer, err error) *HirerRepository_ByGitHubUserID_Call {
	_c.Call.Return(hirer, err)
	return _c
}

func (_c *HirerRepository_ByGitHubUserID_Call) RunAndReturn(run func(ctx context.Context, githubUserID int64) (*domain.Hirer, error)) *HirerRepository_ByGitHubUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ByID provides a mock function for the type HirerRepository
func (_mock *HirerRepository) ByID(ctx context.Context, id domain.HirerID) (*domain.Hirer, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 *domain.Hirer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.HirerID) (*domain.Hirer, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.HirerID) *domain.Hirer); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Hirer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.HirerID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HirerRepository_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type HirerRepository_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.HirerID
func (_e *HirerRepository_Expecter) ByID(ctx interface{}, id interface{}) *HirerRepository_ByID_Call {
	return &HirerRepository_ByID_Call{Call: _e.mock.On("ByID", ctx, id)}
}

func (_c *HirerRepository_ByID_Call) Run(run func(ctx context.Context, id domain.HirerID)) *HirerRepository_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.HirerID
		if args[1] != nil {
			arg1 = args[1].(domain.HirerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HirerRepository_ByID_Call) Return(hirer *domain.Hirer, err error) *HirerRepository_ByID_Call {
	_c.Call.Return(hirer, err)
	return _c
}

func (_c *HirerRepository_ByID_Call) RunAndReturn(run func(ctx context.Context, id domain.HirerID) (*domain.Hirer, error)) *HirerRepository_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// ByUsername provides a mock function for the type HirerRepository
func (_mock *HirerRepository) ByUsername(ctx context.Context, username string) (*domain.Hirer, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for ByUsername")
	}

	var r0 *domain.Hirer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Hirer, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Hirer); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Hirer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HirerRepository_ByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByUsername'
type HirerRepository_ByUsername_Call struct {
	*mock.Call
}

// ByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *HirerRepository_Expecter) ByUsername(ctx interface{}, username interface{}) *HirerRepository_ByUsername_Call {
	return &HirerRepository_ByUsername_Call{Call: _e.mock.On("ByUsername", ctx, username)}
}

func (_c *HirerRepository_ByUsername_Call) Run(run func(ctx context.Context, username string)) *HirerRepository_ByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HirerRepository_ByUsername_Call) Return(hirer *domain.Hirer, err error) *HirerRepository_ByUsername_Call {
	_c.Call.Return(hirer, err)
	return _c
}

func (_c *HirerRepository_ByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*domain.Hirer, error)) *HirerRepository_ByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Disable provides a mock function for the type HirerRepository
func (_mock *HirerRepository) Disable(ctx context.Context, tx port.Tx, id domain.HirerID, by domain.HirerID, now time.Time) error {
	ret := _mock.Called(ctx, tx, id, by, now)

	if len(ret) == 0 {
		panic("no return value specified for Disable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.HirerID, domain.HirerID, time.Time) error); ok {
		r0 = returnFunc(ctx, tx, id, by, now)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// HirerRepository_Disable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disable'
type HirerRepository_Disable_Call struct {
	*mock.Call
}

// Disable is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - id domain.HirerID
//   - by domain.HirerID
//   - now time.Time
func (_e *HirerRepository_Expecter) Disable(ctx interface{}, tx interface{}, id interface{}, by interface{}, now interface{}) *HirerRepository_Disable_Call {
	return &HirerRepository_Disable_Call{Call: _e.mock.On("Disable", ctx, tx, id, by, now)}
}

func (_c *HirerRepository_Disable_Call) Run(run func(ctx context.Context, tx port.Tx, id domain.HirerID, by domain.HirerID, now time.Time)) *HirerRepository_Disable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 domain.HirerID
		if args[2] != nil {
			arg2 = args[2].(domain.HirerID)
		}
		var arg3 domain.HirerID
		if args[3] != nil {
			arg3 = args[3].(domain.HirerID)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *HirerRepository_Disable_Call) Return(err error) *HirerRepository_Disable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *HirerRepository_Disable_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, id domain.HirerID, by domain.HirerID, now time.Time) error) *HirerRepository_Disable_Call {
	_c.Call.Return(run)
	return _c
}

// ListSeats provides a mock function for the type HirerRepository
func (_mock *HirerRepository) ListSeats(ctx context.Context, orgID domain.OrganizationID) ([]domain.Hirer, error) {
	ret := _mock.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListSeats")
	}

	var r0 []domain.Hirer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) ([]domain.Hirer, error)); ok {
		return returnFunc(ctx, orgID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) []domain.Hirer); ok {
		r0 = returnFunc(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Hirer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.OrganizationID) error); ok {
		r1 = returnFunc(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HirerRepository_ListSeats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSeats'
type HirerRepository_ListSeats_Call struct {
	*mock.Call
}

// ListSeats is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID domain.OrganizationID
func (_e *HirerRepository_Expecter) ListSeats(ctx interface{}, orgID interface{}) *HirerRepository_ListSeats_Call {
	return &HirerRepository_ListSeats_Call{Call: _e.mock.On("ListSeats", ctx, orgID)}
}

func (_c *HirerRepository_ListSeats_Call) Run(run func(ctx context.Context, orgID domain.OrganizationID)) *HirerRepository_ListSeats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.OrganizationID
		if args[1] != nil {
			arg1 = args[1].(domain.OrganizationID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HirerRepository_ListSeats_Call) Return(hirers []domain.Hirer, err error) *HirerRepository_ListSeats_Call {
	_c.Call.Return(hirers, err)
	return _c
}

func (_c *HirerRepository_ListSeats_Call) RunAndReturn(run func(ctx context.Context, orgID domain.OrganizationID) ([]domain.Hirer, error)) *HirerRepository_ListSeats_Call {
	_c.Call.Return(run)
	return _c
}

// ListVerifiedOrganizations provides a mock function for the type HirerRepository
func (_mock *HirerRepository) ListVerifiedOrganizations(ctx context.Context) ([]domain.Organization, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListVerifiedOrganizations")
	}

	var r0 []domain.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Organization, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Organization); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HirerRepository_ListVerifiedOrganizations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVerifiedOrganizations'
type HirerRepository_ListVerifiedOrganizations_Call struct {
	*mock.Call
}

// ListVerifiedOrganizations is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HirerRepository_Expecter) ListVerifiedOrganizations(ctx interface{}) *HirerRepository_ListVerifiedOrganizations_Call {
	return &HirerRepository_ListVerifiedOrganizations_Call{Call: _e.mock.On("ListVerifiedOrganizations", ctx)}
}

func (_c *HirerRepository_ListVerifiedOrganizations_Call) Run(run func(ctx context.Context)) *HirerRepository_ListVerifiedOrganizations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HirerRepository_ListVerifiedOrganizations_Call) Return(organizations []domain.Organization, err error) *HirerRepository_ListVerifiedOrganizations_Call {
	_c.Call.Return(organizations, err)
	return _c
}

func (_c *HirerRepository_ListVerifiedOrganizations_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Organization, error)) *HirerRepository_ListVerifiedOrganizations_Call {
	_c.Call.Return(run)
	return _c
}

// Members provides a mock function for the type HirerRepository
func (_mock *HirerRepository) Members(ctx context.Context, id domain.OrganizationID) ([]domain.Hirer, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Members")
	}

	var r0 []domain.Hirer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) ([]domain.Hirer, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) []domain.Hirer); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Hirer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.OrganizationID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HirerRepository_Members_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Members'
type HirerRepository_Members_Call struct {
	*mock.Call
}

// Members is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.OrganizationID
func (_e *HirerRepository_Expecter) Members(ctx interface{}, id interface{}) *HirerRepository_Members_Call {
	return &HirerRepository_Members_Call{Call: _e.mock.On("Members", ctx, id)}
}

func (_c *HirerRepository_Members_Call) Run(run func(ctx context.Context, id domain.OrganizationID)) *HirerRepository_Members_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.OrganizationID
		if args[1] != nil {
			arg1 = args[1].(domain.OrganizationID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HirerRepository_Members_Call) Return(hirers []domain.Hirer, err error) *HirerRepository_Members_Call {
	_c.Call.Return(hirers, err)
	return _c
}

func (_c *HirerRepository_Members_Call) RunAndReturn(run func(ctx context.Context, id domain.OrganizationID) ([]domain.Hirer, error)) *HirerRepository_Members_Call {
	_c.Call.Return(run)
	return _c
}

// Organization provides a mock function for the type HirerRepository
func (_mock *HirerRepository) Organization(ctx context.Context, id domain.OrganizationID) (*domain.Organization, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Organization")
	}

	var r0 *domain.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) (*domain.Organization, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) *domain.Organization); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.OrganizationID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HirerRepository_Organization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Organization'
type HirerRepository_Organization_Call struct {
	*mock.Call
}

// Organization is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.OrganizationID
func (_e *HirerRepository_Expecter) Organization(ctx interface{}, id interface{}) *HirerRepository_Organization_Call {
	return &HirerRepository_Organization_Call{Call: _e.mock.On("Organization", ctx, id)}
}

func (_c *HirerRepository_Organization_Call) Run(run func(ctx context.Context, id domain.OrganizationID)) *HirerRepository_Organization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.OrganizationID
		if args[1] != nil {
			arg1 = args[1].(domain.OrganizationID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HirerRepository_Organization_Call) Return(organization *domain.Organization, err error) *HirerRepository_Organization_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *HirerRepository_Organization_Call) RunAndReturn(run func(ctx context.Context, id domain.OrganizationID) (*domain.Organization, error)) *HirerRepository_Organization_Call {
	_c.Call.Return(run)
	return _c
}

// OrganizationBySlug provides a mock function for the type HirerRepository
func (_mock *HirerRepository) OrganizationBySlug(ctx context.Context, slug string) (*domain.Organization, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for OrganizationBySlug")
	}

	var r0 *domain.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Organization, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Organization); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HirerRepository_OrganizationBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrganizationBySlug'
type HirerRepository_OrganizationBySlug_Call struct {
	*mock.Call
}

// OrganizationBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *HirerRepository_Expecter) OrganizationBySlug(ctx interface{}, slug interface{}) *HirerRepository_OrganizationBySlug_Call {
	return &HirerRepository_OrganizationBySlug_Call{Call: _e.mock.On("OrganizationBySlug", ctx, slug)}
}

func (_c *HirerRepository_OrganizationBySlug_Call) Run(run func(ctx context.Context, slug string)) *HirerRepository_OrganizationBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HirerRepository_OrganizationBySlug_Call) Return(organization *domain.Organization, err error) *HirerRepository_OrganizationBySlug_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *HirerRepository_OrganizationBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*domain.Organization, error)) *HirerRepository_OrganizationBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// PasswordHash provides a mock function for the type HirerRepository
func (_mock *HirerRepository) PasswordHash(ctx context.Context, id domain.HirerID) ([]byte, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for PasswordHash")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.HirerID) ([]byte, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.HirerID) []byte); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.HirerID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HirerRepository_PasswordHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasswordHash'
type HirerRepository_PasswordHash_Call struct {
	*mock.Call
}

// PasswordHash is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.HirerID
func (_e *HirerRepository_Expecter) PasswordHash(ctx interface{}, id interface{}) *HirerRepository_PasswordHash_Call {
	return &HirerRepository_PasswordHash_Call{Call: _e.mock.On("PasswordHash", ctx, id)}
}

func (_c *HirerRepository_PasswordHash_Call) Run(run func(ctx context.Context, id domain.HirerID)) *HirerRepository_PasswordHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.HirerID
		if args[1] != nil {
			arg1 = args[1].(domain.HirerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HirerRepository_PasswordHash_Call) Return(bytes []byte, err error) *HirerRepository_PasswordHash_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *HirerRepository_PasswordHash_Call) RunAndReturn(run func(ctx context.Context, id domain.HirerID) ([]byte, error)) *HirerRepository_PasswordHash_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type HirerRepository
func (_mock *HirerRepository) Register(ctx context.Context, tx port.Tx, in port.NewHirerAccount) (*port.HirerRegistration, error) {
	ret := _mock.Called(ctx, tx, in)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *port.HirerRegistration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, port.NewHirerAccount) (*port.HirerRegistration, error)); ok {
		return returnFunc(ctx, tx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, port.NewHirerAccount) *port.HirerRegistration); ok {
		r0 = returnFunc(ctx, tx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.HirerRegistration)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, port.Tx, port.NewHirerAccount) error); ok {
		r1 = returnFunc(ctx, tx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HirerRepository_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type HirerRepository_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - in port.NewHirerAccount
func (_e *HirerRepository_Expecter) Register(ctx interface{}, tx interface{}, in interface{}) *HirerRepository_Register_Call {
	return &HirerRepository_Register_Call{Call: _e.mock.On("Register", ctx, tx, in)}
}

func (_c *HirerRepository_Register_Call) Run(run func(ctx context.Context, tx port.Tx, in port.NewHirerAccount)) *HirerRepository_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 port.NewHirerAccount
		if args[2] != nil {
			arg2 = args[2].(port.NewHirerAccount)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *HirerRepository_Register_Call) Return(hirerRegistration *port.HirerRegistration, err error) *HirerRepository_Register_Call {
	_c.Call.Return(hirerRegistration, err)
	return _c
}

func (_c *HirerRepository_Register_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, in port.NewHirerAccount) (*port.HirerRegistration, error)) *HirerRepository_Register_Call {
	_c.Call.Return(run)
	return _c
}

// SharesGitHubIdentity provides a mock function for the type HirerRepository
func (_mock *HirerRepository) SharesGitHubIdentity(ctx context.Context, hirer domain.HirerID, target domain.UserID) (bool, error) {
	ret := _mock.Called(ctx, hirer, target)

	if len(ret) == 0 {
		panic("no return value specified for SharesGitHubIdentity")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.HirerID, domain.UserID) (bool, error)); ok {
		return returnFunc(ctx, hirer, target)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.HirerID, domain.UserID) bool); ok {
		r0 = returnFunc(ctx, hirer, target)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.HirerID, domain.UserID) error); ok {
		r1 = returnFunc(ctx, hirer, target)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HirerRepository_SharesGitHubIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SharesGitHubIdentity'
type HirerRepository_SharesGitHubIdentity_Call struct {
	*mock.Call
}

// SharesGitHubIdentity is a helper method to define mock.On call
//   - ctx context.Context
//   - hirer domain.HirerID
//   - target domain.UserID
func (_e *HirerRepository_Expecter) SharesGitHubIdentity(ctx interface{}, hirer interface{}, target interface{}) *HirerRepository_SharesGitHubIdentity_Call {
	return &HirerRepository_SharesGitHubIdentity_Call{Call: _e.mock.On("SharesGitHubIdentity", ctx, hirer, target)}
}

func (_c *HirerRepository_SharesGitHubIdentity_Call) Run(run func(ctx context.Context, hirer domain.HirerID, target domain.UserID)) *HirerRepository_SharesGitHubIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.HirerID
		if args[1] != nil {
			arg1 = args[1].(domain.HirerID)
		}
		var arg2 domain.UserID
		if args[2] != nil {
			arg2 = args[2].(domain.UserID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *HirerRepository_SharesGitHubIdentity_Call) Return(b bool, err error) *HirerRepository_SharesGitHubIdentity_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *HirerRepository_SharesGitHubIdentity_Call) RunAndReturn(run func(ctx context.Context, hirer domain.HirerID, target domain.UserID) (bool, error)) *HirerRepository_SharesGitHubIdentity_Call {
	_c.Call.Return(run)
	return _c
}
