// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewHirerRepository creates a new instance of HirerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHirerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *HirerRepository {
	mock := &HirerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HirerRepository is an autogenerated mock type for the HirerRepository type
type HirerRepository struct {
	mock.Mock
}

type HirerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *HirerRepository) EXPECT() *HirerRepository_Expecter {
	return &HirerRepository_Expecter{mock: &_m.Mock}
}

// ByEmail provides a mock function for the type HirerRepository
func (_mock *HirerRepository) ByEmail(ctx context.Context, email string) (*domain.Hirer, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ByEmail")
	}

	var r0 *domain.Hirer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Hirer, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Hirer); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Hirer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HirerRepository_ByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByEmail'
type HirerRepository_ByEmail_Call struct {
	*mock.Call
}

// ByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *HirerRepository_Expecter) ByEmail(ctx interface{}, email interface{}) *HirerRepository_ByEmail_Call {
	return &HirerRepository_ByEmail_Call{Call: _e.mock.On("ByEmail", ctx, email)}
}

func (_c *HirerRepository_ByEmail_Call) Run(run func(ctx context.Context, email string)) *HirerRepository_ByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HirerRepository_ByEmail_Call) Return(hirer *domain.Hirer, err error) *HirerRepository_ByEmail_Call {
	_c.Call.Return(hirer, err)
	return _c
}

func (_c *HirerRepository_ByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*domain.Hirer, error)) *HirerRepository_ByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ByID provides a mock function for the type HirerRepository
func (_mock *HirerRepository) ByID(ctx context.Context, id domain.HirerID) (*domain.Hirer, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 *domain.Hirer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.HirerID) (*domain.Hirer, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.HirerID) *domain.Hirer); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Hirer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.HirerID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HirerRepository_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type HirerRepository_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.HirerID
func (_e *HirerRepository_Expecter) ByID(ctx interface{}, id interface{}) *HirerRepository_ByID_Call {
	return &HirerRepository_ByID_Call{Call: _e.mock.On("ByID", ctx, id)}
}

func (_c *HirerRepository_ByID_Call) Run(run func(ctx context.Context, id domain.HirerID)) *HirerRepository_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.HirerID
		if args[1] != nil {
			arg1 = args[1].(domain.HirerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HirerRepository_ByID_Call) Return(hirer *domain.Hirer, err error) *HirerRepository_ByID_Call {
	_c.Call.Return(hirer, err)
	return _c
}

func (_c *HirerRepository_ByID_Call) RunAndReturn(run func(ctx context.Context, id domain.HirerID) (*domain.Hirer, error)) *HirerRepository_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// Members provides a mock function for the type HirerRepository
func (_mock *HirerRepository) Members(ctx context.Context, id domain.OrganizationID) ([]domain.Hirer, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Members")
	}

	var r0 []domain.Hirer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) ([]domain.Hirer, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) []domain.Hirer); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Hirer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.OrganizationID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HirerRepository_Members_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Members'
type HirerRepository_Members_Call struct {
	*mock.Call
}

// Members is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.OrganizationID
func (_e *HirerRepository_Expecter) Members(ctx interface{}, id interface{}) *HirerRepository_Members_Call {
	return &HirerRepository_Members_Call{Call: _e.mock.On("Members", ctx, id)}
}

func (_c *HirerRepository_Members_Call) Run(run func(ctx context.Context, id domain.OrganizationID)) *HirerRepository_Members_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.OrganizationID
		if args[1] != nil {
			arg1 = args[1].(domain.OrganizationID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HirerRepository_Members_Call) Return(hirers []domain.Hirer, err error) *HirerRepository_Members_Call {
	_c.Call.Return(hirers, err)
	return _c
}

func (_c *HirerRepository_Members_Call) RunAndReturn(run func(ctx context.Context, id domain.OrganizationID) ([]domain.Hirer, error)) *HirerRepository_Members_Call {
	_c.Call.Return(run)
	return _c
}

// Organization provides a mock function for the type HirerRepository
func (_mock *HirerRepository) Organization(ctx context.Context, id domain.OrganizationID) (*domain.Organization, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Organization")
	}

	var r0 *domain.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) (*domain.Organization, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) *domain.Organization); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.OrganizationID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HirerRepository_Organization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Organization'
type HirerRepository_Organization_Call struct {
	*mock.Call
}

// Organization is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.OrganizationID
func (_e *HirerRepository_Expecter) Organization(ctx interface{}, id interface{}) *HirerRepository_Organization_Call {
	return &HirerRepository_Organization_Call{Call: _e.mock.On("Organization", ctx, id)}
}

func (_c *HirerRepository_Organization_Call) Run(run func(ctx context.Context, id domain.OrganizationID)) *HirerRepository_Organization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.OrganizationID
		if args[1] != nil {
			arg1 = args[1].(domain.OrganizationID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HirerRepository_Organization_Call) Return(organization *domain.Organization, err error) *HirerRepository_Organization_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *HirerRepository_Organization_Call) RunAndReturn(run func(ctx context.Context, id domain.OrganizationID) (*domain.Organization, error)) *HirerRepository_Organization_Call {
	_c.Call.Return(run)
	return _c
}

// PasswordHash provides a mock function for the type HirerRepository
func (_mock *HirerRepository) PasswordHash(ctx context.Context, id domain.HirerID) ([]byte, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for PasswordHash")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.HirerID) ([]byte, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.HirerID) []byte); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.HirerID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HirerRepository_PasswordHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasswordHash'
type HirerRepository_PasswordHash_Call struct {
	*mock.Call
}

// PasswordHash is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.HirerID
func (_e *HirerRepository_Expecter) PasswordHash(ctx interface{}, id interface{}) *HirerRepository_PasswordHash_Call {
	return &HirerRepository_PasswordHash_Call{Call: _e.mock.On("PasswordHash", ctx, id)}
}

func (_c *HirerRepository_PasswordHash_Call) Run(run func(ctx context.Context, id domain.HirerID)) *HirerRepository_PasswordHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.HirerID
		if args[1] != nil {
			arg1 = args[1].(domain.HirerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HirerRepository_PasswordHash_Call) Return(bytes []byte, err error) *HirerRepository_PasswordHash_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *HirerRepository_PasswordHash_Call) RunAndReturn(run func(ctx context.Context, id domain.HirerID) ([]byte, error)) *HirerRepository_PasswordHash_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type HirerRepository
func (_mock *HirerRepository) Register(ctx context.Context, tx port.Tx, h *domain.Hirer, org *domain.Organization, passwordHash []byte) (*domain.Hirer, error) {
	ret := _mock.Called(ctx, tx, h, org, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *domain.Hirer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, *domain.Hirer, *domain.Organization, []byte) (*domain.Hirer, error)); ok {
		return returnFunc(ctx, tx, h, org, passwordHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, *domain.Hirer, *domain.Organization, []byte) *domain.Hirer); ok {
		r0 = returnFunc(ctx, tx, h, org, passwordHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Hirer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, port.Tx, *domain.Hirer, *domain.Organization, []byte) error); ok {
		r1 = returnFunc(ctx, tx, h, org, passwordHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HirerRepository_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type HirerRepository_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - h *domain.Hirer
//   - org *domain.Organization
//   - passwordHash []byte
func (_e *HirerRepository_Expecter) Register(ctx interface{}, tx interface{}, h interface{}, org interface{}, passwordHash interface{}) *HirerRepository_Register_Call {
	return &HirerRepository_Register_Call{Call: _e.mock.On("Register", ctx, tx, h, org, passwordHash)}
}

func (_c *HirerRepository_Register_Call) Run(run func(ctx context.Context, tx port.Tx, h *domain.Hirer, org *domain.Organization, passwordHash []byte)) *HirerRepository_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 *domain.Hirer
		if args[2] != nil {
			arg2 = args[2].(*domain.Hirer)
		}
		var arg3 *domain.Organization
		if args[3] != nil {
			arg3 = args[3].(*domain.Organization)
		}
		var arg4 []byte
		if args[4] != nil {
			arg4 = args[4].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *HirerRepository_Register_Call) Return(hirer *domain.Hirer, err error) *HirerRepository_Register_Call {
	_c.Call.Return(hirer, err)
	return _c
}

func (_c *HirerRepository_Register_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, h *domain.Hirer, org *domain.Organization, passwordHash []byte) (*domain.Hirer, error)) *HirerRepository_Register_Call {
	_c.Call.Return(run)
	return _c
}

// SharesGitHubIdentity provides a mock function for the type HirerRepository
func (_mock *HirerRepository) SharesGitHubIdentity(ctx context.Context, hirer domain.HirerID, target domain.UserID) (bool, error) {
	ret := _mock.Called(ctx, hirer, target)

	if len(ret) == 0 {
		panic("no return value specified for SharesGitHubIdentity")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.HirerID, domain.UserID) (bool, error)); ok {
		return returnFunc(ctx, hirer, target)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.HirerID, domain.UserID) bool); ok {
		r0 = returnFunc(ctx, hirer, target)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.HirerID, domain.UserID) error); ok {
		r1 = returnFunc(ctx, hirer, target)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HirerRepository_SharesGitHubIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SharesGitHubIdentity'
type HirerRepository_SharesGitHubIdentity_Call struct {
	*mock.Call
}

// SharesGitHubIdentity is a helper method to define mock.On call
//   - ctx context.Context
//   - hirer domain.HirerID
//   - target domain.UserID
func (_e *HirerRepository_Expecter) SharesGitHubIdentity(ctx interface{}, hirer interface{}, target interface{}) *HirerRepository_SharesGitHubIdentity_Call {
	return &HirerRepository_SharesGitHubIdentity_Call{Call: _e.mock.On("SharesGitHubIdentity", ctx, hirer, target)}
}

func (_c *HirerRepository_SharesGitHubIdentity_Call) Run(run func(ctx context.Context, hirer domain.HirerID, target domain.UserID)) *HirerRepository_SharesGitHubIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.HirerID
		if args[1] != nil {
			arg1 = args[1].(domain.HirerID)
		}
		var arg2 domain.UserID
		if args[2] != nil {
			arg2 = args[2].(domain.UserID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *HirerRepository_SharesGitHubIdentity_Call) Return(b bool, err error) *HirerRepository_SharesGitHubIdentity_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *HirerRepository_SharesGitHubIdentity_Call) RunAndReturn(run func(ctx context.Context, hirer domain.HirerID, target domain.UserID) (bool, error)) *HirerRepository_SharesGitHubIdentity_Call {
	_c.Call.Return(run)
	return _c
}
