// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewJobService creates a new instance of JobService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobService(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobService {
	mock := &JobService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JobService is an autogenerated mock type for the JobService type
type JobService struct {
	mock.Mock
}

type JobService_Expecter struct {
	mock *mock.Mock
}

func (_m *JobService) EXPECT() *JobService_Expecter {
	return &JobService_Expecter{mock: &_m.Mock}
}

// ExpireAvailability provides a mock function for the type JobService
func (_mock *JobService) ExpireAvailability(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ExpireAvailability")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobService_ExpireAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpireAvailability'
type JobService_ExpireAvailability_Call struct {
	*mock.Call
}

// ExpireAvailability is a helper method to define mock.On call
//   - ctx context.Context
func (_e *JobService_Expecter) ExpireAvailability(ctx interface{}) *JobService_ExpireAvailability_Call {
	return &JobService_ExpireAvailability_Call{Call: _e.mock.On("ExpireAvailability", ctx)}
}

func (_c *JobService_ExpireAvailability_Call) Run(run func(ctx context.Context)) *JobService_ExpireAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JobService_ExpireAvailability_Call) Return(reminded int, err error) *JobService_ExpireAvailability_Call {
	_c.Call.Return(reminded, err)
	return _c
}

func (_c *JobService_ExpireAvailability_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *JobService_ExpireAvailability_Call {
	_c.Call.Return(run)
	return _c
}

// ExpireContactRequests provides a mock function for the type JobService
func (_mock *JobService) ExpireContactRequests(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ExpireContactRequests")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobService_ExpireContactRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpireContactRequests'
type JobService_ExpireContactRequests_Call struct {
	*mock.Call
}

// ExpireContactRequests is a helper method to define mock.On call
//   - ctx context.Context
func (_e *JobService_Expecter) ExpireContactRequests(ctx interface{}) *JobService_ExpireContactRequests_Call {
	return &JobService_ExpireContactRequests_Call{Call: _e.mock.On("ExpireContactRequests", ctx)}
}

func (_c *JobService_ExpireContactRequests_Call) Run(run func(ctx context.Context)) *JobService_ExpireContactRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JobService_ExpireContactRequests_Call) Return(expired int, err error) *JobService_ExpireContactRequests_Call {
	_c.Call.Return(expired, err)
	return _c
}

func (_c *JobService_ExpireContactRequests_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *JobService_ExpireContactRequests_Call {
	_c.Call.Return(run)
	return _c
}

// ExpireOnboarding provides a mock function for the type JobService
func (_mock *JobService) ExpireOnboarding(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ExpireOnboarding")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobService_ExpireOnboarding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpireOnboarding'
type JobService_ExpireOnboarding_Call struct {
	*mock.Call
}

// ExpireOnboarding is a helper method to define mock.On call
//   - ctx context.Context
func (_e *JobService_Expecter) ExpireOnboarding(ctx interface{}) *JobService_ExpireOnboarding_Call {
	return &JobService_ExpireOnboarding_Call{Call: _e.mock.On("ExpireOnboarding", ctx)}
}

func (_c *JobService_ExpireOnboarding_Call) Run(run func(ctx context.Context)) *JobService_ExpireOnboarding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JobService_ExpireOnboarding_Call) Return(n int, err error) *JobService_ExpireOnboarding_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *JobService_ExpireOnboarding_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *JobService_ExpireOnboarding_Call {
	_c.Call.Return(run)
	return _c
}

// FlagOverdueShortlists provides a mock function for the type JobService
func (_mock *JobService) FlagOverdueShortlists(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FlagOverdueShortlists")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobService_FlagOverdueShortlists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlagOverdueShortlists'
type JobService_FlagOverdueShortlists_Call struct {
	*mock.Call
}

// FlagOverdueShortlists is a helper method to define mock.On call
//   - ctx context.Context
func (_e *JobService_Expecter) FlagOverdueShortlists(ctx interface{}) *JobService_FlagOverdueShortlists_Call {
	return &JobService_FlagOverdueShortlists_Call{Call: _e.mock.On("FlagOverdueShortlists", ctx)}
}

func (_c *JobService_FlagOverdueShortlists_Call) Run(run func(ctx context.Context)) *JobService_FlagOverdueShortlists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JobService_FlagOverdueShortlists_Call) Return(flagged int, err error) *JobService_FlagOverdueShortlists_Call {
	_c.Call.Return(flagged, err)
	return _c
}

func (_c *JobService_FlagOverdueShortlists_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *JobService_FlagOverdueShortlists_Call {
	_c.Call.Return(run)
	return _c
}

// RecomputeNorms provides a mock function for the type JobService
func (_mock *JobService) RecomputeNorms(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RecomputeNorms")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JobService_RecomputeNorms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecomputeNorms'
type JobService_RecomputeNorms_Call struct {
	*mock.Call
}

// RecomputeNorms is a helper method to define mock.On call
//   - ctx context.Context
func (_e *JobService_Expecter) RecomputeNorms(ctx interface{}) *JobService_RecomputeNorms_Call {
	return &JobService_RecomputeNorms_Call{Call: _e.mock.On("RecomputeNorms", ctx)}
}

func (_c *JobService_RecomputeNorms_Call) Run(run func(ctx context.Context)) *JobService_RecomputeNorms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JobService_RecomputeNorms_Call) Return(err error) *JobService_RecomputeNorms_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JobService_RecomputeNorms_Call) RunAndReturn(run func(ctx context.Context) error) *JobService_RecomputeNorms_Call {
	_c.Call.Return(run)
	return _c
}
