// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMoneyService creates a new instance of MoneyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMoneyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MoneyService {
	mock := &MoneyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MoneyService is an autogenerated mock type for the MoneyService type
type MoneyService struct {
	mock.Mock
}

type MoneyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MoneyService) EXPECT() *MoneyService_Expecter {
	return &MoneyService_Expecter{mock: &_m.Mock}
}

// Currencies provides a mock function for the type MoneyService
func (_mock *MoneyService) Currencies(ctx context.Context) ([]domain.Currency, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Currencies")
	}

	var r0 []domain.Currency
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Currency, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Currency); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Currency)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MoneyService_Currencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Currencies'
type MoneyService_Currencies_Call struct {
	*mock.Call
}

// Currencies is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MoneyService_Expecter) Currencies(ctx interface{}) *MoneyService_Currencies_Call {
	return &MoneyService_Currencies_Call{Call: _e.mock.On("Currencies", ctx)}
}

func (_c *MoneyService_Currencies_Call) Run(run func(ctx context.Context)) *MoneyService_Currencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MoneyService_Currencies_Call) Return(currencys []domain.Currency, err error) *MoneyService_Currencies_Call {
	_c.Call.Return(currencys, err)
	return _c
}

func (_c *MoneyService_Currencies_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Currency, error)) *MoneyService_Currencies_Call {
	_c.Call.Return(run)
	return _c
}
