// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewNormsRepository creates a new instance of NormsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNormsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NormsRepository {
	mock := &NormsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NormsRepository is an autogenerated mock type for the NormsRepository type
type NormsRepository struct {
	mock.Mock
}

type NormsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *NormsRepository) EXPECT() *NormsRepository_Expecter {
	return &NormsRepository_Expecter{mock: &_m.Mock}
}

// Current provides a mock function for the type NormsRepository
func (_mock *NormsRepository) Current(ctx context.Context) (map[string]domain.GlobalNorms, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Current")
	}

	var r0 map[string]domain.GlobalNorms
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]domain.GlobalNorms, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]domain.GlobalNorms); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]domain.GlobalNorms)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NormsRepository_Current_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Current'
type NormsRepository_Current_Call struct {
	*mock.Call
}

// Current is a helper method to define mock.On call
//   - ctx context.Context
func (_e *NormsRepository_Expecter) Current(ctx interface{}) *NormsRepository_Current_Call {
	return &NormsRepository_Current_Call{Call: _e.mock.On("Current", ctx)}
}

func (_c *NormsRepository_Current_Call) Run(run func(ctx context.Context)) *NormsRepository_Current_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *NormsRepository_Current_Call) Return(stringToGlobalNorms map[string]domain.GlobalNorms, err error) *NormsRepository_Current_Call {
	_c.Call.Return(stringToGlobalNorms, err)
	return _c
}

func (_c *NormsRepository_Current_Call) RunAndReturn(run func(ctx context.Context) (map[string]domain.GlobalNorms, error)) *NormsRepository_Current_Call {
	_c.Call.Return(run)
	return _c
}

// Observe provides a mock function for the type NormsRepository
func (_mock *NormsRepository) Observe(ctx context.Context, tx port.Tx, metric string, value float64) error {
	ret := _mock.Called(ctx, tx, metric, value)

	if len(ret) == 0 {
		panic("no return value specified for Observe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, string, float64) error); ok {
		r0 = returnFunc(ctx, tx, metric, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NormsRepository_Observe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Observe'
type NormsRepository_Observe_Call struct {
	*mock.Call
}

// Observe is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - metric string
//   - value float64
func (_e *NormsRepository_Expecter) Observe(ctx interface{}, tx interface{}, metric interface{}, value interface{}) *NormsRepository_Observe_Call {
	return &NormsRepository_Observe_Call{Call: _e.mock.On("Observe", ctx, tx, metric, value)}
}

func (_c *NormsRepository_Observe_Call) Run(run func(ctx context.Context, tx port.Tx, metric string, value float64)) *NormsRepository_Observe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *NormsRepository_Observe_Call) Return(err error) *NormsRepository_Observe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NormsRepository_Observe_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, metric string, value float64) error) *NormsRepository_Observe_Call {
	_c.Call.Return(run)
	return _c
}

// Recompute provides a mock function for the type NormsRepository
func (_mock *NormsRepository) Recompute(ctx context.Context, generation int) error {
	ret := _mock.Called(ctx, generation)

	if len(ret) == 0 {
		panic("no return value specified for Recompute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, generation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NormsRepository_Recompute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recompute'
type NormsRepository_Recompute_Call struct {
	*mock.Call
}

// Recompute is a helper method to define mock.On call
//   - ctx context.Context
//   - generation int
func (_e *NormsRepository_Expecter) Recompute(ctx interface{}, generation interface{}) *NormsRepository_Recompute_Call {
	return &NormsRepository_Recompute_Call{Call: _e.mock.On("Recompute", ctx, generation)}
}

func (_c *NormsRepository_Recompute_Call) Run(run func(ctx context.Context, generation int)) *NormsRepository_Recompute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NormsRepository_Recompute_Call) Return(err error) *NormsRepository_Recompute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NormsRepository_Recompute_Call) RunAndReturn(run func(ctx context.Context, generation int) error) *NormsRepository_Recompute_Call {
	_c.Call.Return(run)
	return _c
}
