// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewOnboardingRepository creates a new instance of OnboardingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOnboardingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OnboardingRepository {
	mock := &OnboardingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OnboardingRepository is an autogenerated mock type for the OnboardingRepository type
type OnboardingRepository struct {
	mock.Mock
}

type OnboardingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OnboardingRepository) EXPECT() *OnboardingRepository_Expecter {
	return &OnboardingRepository_Expecter{mock: &_m.Mock}
}

// ByID provides a mock function for the type OnboardingRepository
func (_mock *OnboardingRepository) ByID(ctx context.Context, tx port.Tx, id domain.OnboardingID) (*port.OnboardingSubmission, error) {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 *port.OnboardingSubmission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.OnboardingID) (*port.OnboardingSubmission, error)); ok {
		return returnFunc(ctx, tx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.OnboardingID) *port.OnboardingSubmission); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.OnboardingSubmission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, port.Tx, domain.OnboardingID) error); ok {
		r1 = returnFunc(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OnboardingRepository_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type OnboardingRepository_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - id domain.OnboardingID
func (_e *OnboardingRepository_Expecter) ByID(ctx interface{}, tx interface{}, id interface{}) *OnboardingRepository_ByID_Call {
	return &OnboardingRepository_ByID_Call{Call: _e.mock.On("ByID", ctx, tx, id)}
}

func (_c *OnboardingRepository_ByID_Call) Run(run func(ctx context.Context, tx port.Tx, id domain.OnboardingID)) *OnboardingRepository_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 domain.OnboardingID
		if args[2] != nil {
			arg2 = args[2].(domain.OnboardingID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OnboardingRepository_ByID_Call) Return(onboardingSubmission *port.OnboardingSubmission, err error) *OnboardingRepository_ByID_Call {
	_c.Call.Return(onboardingSubmission, err)
	return _c
}

func (_c *OnboardingRepository_ByID_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, id domain.OnboardingID) (*port.OnboardingSubmission, error)) *OnboardingRepository_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// ExpireUnproven provides a mock function for the type OnboardingRepository
func (_mock *OnboardingRepository) ExpireUnproven(ctx context.Context, before time.Time) (int, error) {
	ret := _mock.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for ExpireUnproven")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (int, error)); ok {
		return returnFunc(ctx, before)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) int); ok {
		r0 = returnFunc(ctx, before)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, before)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OnboardingRepository_ExpireUnproven_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpireUnproven'
type OnboardingRepository_ExpireUnproven_Call struct {
	*mock.Call
}

// ExpireUnproven is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
func (_e *OnboardingRepository_Expecter) ExpireUnproven(ctx interface{}, before interface{}) *OnboardingRepository_ExpireUnproven_Call {
	return &OnboardingRepository_ExpireUnproven_Call{Call: _e.mock.On("ExpireUnproven", ctx, before)}
}

func (_c *OnboardingRepository_ExpireUnproven_Call) Run(run func(ctx context.Context, before time.Time)) *OnboardingRepository_ExpireUnproven_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OnboardingRepository_ExpireUnproven_Call) Return(n int, err error) *OnboardingRepository_ExpireUnproven_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *OnboardingRepository_ExpireUnproven_Call) RunAndReturn(run func(ctx context.Context, before time.Time) (int, error)) *OnboardingRepository_ExpireUnproven_Call {
	_c.Call.Return(run)
	return _c
}

// Promote provides a mock function for the type OnboardingRepository
func (_mock *OnboardingRepository) Promote(ctx context.Context, tx port.Tx, id domain.OnboardingID, slug string, by domain.AdminID, at time.Time) (*domain.Organization, error) {
	ret := _mock.Called(ctx, tx, id, slug, by, at)

	if len(ret) == 0 {
		panic("no return value specified for Promote")
	}

	var r0 *domain.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.OnboardingID, string, domain.AdminID, time.Time) (*domain.Organization, error)); ok {
		return returnFunc(ctx, tx, id, slug, by, at)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.OnboardingID, string, domain.AdminID, time.Time) *domain.Organization); ok {
		r0 = returnFunc(ctx, tx, id, slug, by, at)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, port.Tx, domain.OnboardingID, string, domain.AdminID, time.Time) error); ok {
		r1 = returnFunc(ctx, tx, id, slug, by, at)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OnboardingRepository_Promote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Promote'
type OnboardingRepository_Promote_Call struct {
	*mock.Call
}

// Promote is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - id domain.OnboardingID
//   - slug string
//   - by domain.AdminID
//   - at time.Time
func (_e *OnboardingRepository_Expecter) Promote(ctx interface{}, tx interface{}, id interface{}, slug interface{}, by interface{}, at interface{}) *OnboardingRepository_Promote_Call {
	return &OnboardingRepository_Promote_Call{Call: _e.mock.On("Promote", ctx, tx, id, slug, by, at)}
}

func (_c *OnboardingRepository_Promote_Call) Run(run func(ctx context.Context, tx port.Tx, id domain.OnboardingID, slug string, by domain.AdminID, at time.Time)) *OnboardingRepository_Promote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 domain.OnboardingID
		if args[2] != nil {
			arg2 = args[2].(domain.OnboardingID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 domain.AdminID
		if args[4] != nil {
			arg4 = args[4].(domain.AdminID)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *OnboardingRepository_Promote_Call) Return(organization *domain.Organization, err error) *OnboardingRepository_Promote_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *OnboardingRepository_Promote_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, id domain.OnboardingID, slug string, by domain.AdminID, at time.Time) (*domain.Organization, error)) *OnboardingRepository_Promote_Call {
	_c.Call.Return(run)
	return _c
}

// Prove provides a mock function for the type OnboardingRepository
func (_mock *OnboardingRepository) Prove(ctx context.Context, tx port.Tx, id domain.OnboardingID, owner port.OnboardingOwner, at time.Time) error {
	ret := _mock.Called(ctx, tx, id, owner, at)

	if len(ret) == 0 {
		panic("no return value specified for Prove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.OnboardingID, port.OnboardingOwner, time.Time) error); ok {
		r0 = returnFunc(ctx, tx, id, owner, at)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OnboardingRepository_Prove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prove'
type OnboardingRepository_Prove_Call struct {
	*mock.Call
}

// Prove is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - id domain.OnboardingID
//   - owner port.OnboardingOwner
//   - at time.Time
func (_e *OnboardingRepository_Expecter) Prove(ctx interface{}, tx interface{}, id interface{}, owner interface{}, at interface{}) *OnboardingRepository_Prove_Call {
	return &OnboardingRepository_Prove_Call{Call: _e.mock.On("Prove", ctx, tx, id, owner, at)}
}

func (_c *OnboardingRepository_Prove_Call) Run(run func(ctx context.Context, tx port.Tx, id domain.OnboardingID, owner port.OnboardingOwner, at time.Time)) *OnboardingRepository_Prove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 domain.OnboardingID
		if args[2] != nil {
			arg2 = args[2].(domain.OnboardingID)
		}
		var arg3 port.OnboardingOwner
		if args[3] != nil {
			arg3 = args[3].(port.OnboardingOwner)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *OnboardingRepository_Prove_Call) Return(err error) *OnboardingRepository_Prove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OnboardingRepository_Prove_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, id domain.OnboardingID, owner port.OnboardingOwner, at time.Time) error) *OnboardingRepository_Prove_Call {
	_c.Call.Return(run)
	return _c
}

// Queue provides a mock function for the type OnboardingRepository
func (_mock *OnboardingRepository) Queue(ctx context.Context) ([]port.OnboardingSubmission, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Queue")
	}

	var r0 []port.OnboardingSubmission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]port.OnboardingSubmission, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []port.OnboardingSubmission); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.OnboardingSubmission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OnboardingRepository_Queue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Queue'
type OnboardingRepository_Queue_Call struct {
	*mock.Call
}

// Queue is a helper method to define mock.On call
//   - ctx context.Context
func (_e *OnboardingRepository_Expecter) Queue(ctx interface{}) *OnboardingRepository_Queue_Call {
	return &OnboardingRepository_Queue_Call{Call: _e.mock.On("Queue", ctx)}
}

func (_c *OnboardingRepository_Queue_Call) Run(run func(ctx context.Context)) *OnboardingRepository_Queue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OnboardingRepository_Queue_Call) Return(onboardingSubmissions []port.OnboardingSubmission, err error) *OnboardingRepository_Queue_Call {
	_c.Call.Return(onboardingSubmissions, err)
	return _c
}

func (_c *OnboardingRepository_Queue_Call) RunAndReturn(run func(ctx context.Context) ([]port.OnboardingSubmission, error)) *OnboardingRepository_Queue_Call {
	_c.Call.Return(run)
	return _c
}

// Reject provides a mock function for the type OnboardingRepository
func (_mock *OnboardingRepository) Reject(ctx context.Context, tx port.Tx, id domain.OnboardingID, by domain.AdminID, reason string, at time.Time) error {
	ret := _mock.Called(ctx, tx, id, by, reason, at)

	if len(ret) == 0 {
		panic("no return value specified for Reject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.OnboardingID, domain.AdminID, string, time.Time) error); ok {
		r0 = returnFunc(ctx, tx, id, by, reason, at)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OnboardingRepository_Reject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reject'
type OnboardingRepository_Reject_Call struct {
	*mock.Call
}

// Reject is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - id domain.OnboardingID
//   - by domain.AdminID
//   - reason string
//   - at time.Time
func (_e *OnboardingRepository_Expecter) Reject(ctx interface{}, tx interface{}, id interface{}, by interface{}, reason interface{}, at interface{}) *OnboardingRepository_Reject_Call {
	return &OnboardingRepository_Reject_Call{Call: _e.mock.On("Reject", ctx, tx, id, by, reason, at)}
}

func (_c *OnboardingRepository_Reject_Call) Run(run func(ctx context.Context, tx port.Tx, id domain.OnboardingID, by domain.AdminID, reason string, at time.Time)) *OnboardingRepository_Reject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 domain.OnboardingID
		if args[2] != nil {
			arg2 = args[2].(domain.OnboardingID)
		}
		var arg3 domain.AdminID
		if args[3] != nil {
			arg3 = args[3].(domain.AdminID)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *OnboardingRepository_Reject_Call) Return(err error) *OnboardingRepository_Reject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OnboardingRepository_Reject_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, id domain.OnboardingID, by domain.AdminID, reason string, at time.Time) error) *OnboardingRepository_Reject_Call {
	_c.Call.Return(run)
	return _c
}

// Submit provides a mock function for the type OnboardingRepository
func (_mock *OnboardingRepository) Submit(ctx context.Context, tx port.Tx, in *port.OnboardingSubmission) (*port.OnboardingSubmission, error) {
	ret := _mock.Called(ctx, tx, in)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 *port.OnboardingSubmission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, *port.OnboardingSubmission) (*port.OnboardingSubmission, error)); ok {
		return returnFunc(ctx, tx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, *port.OnboardingSubmission) *port.OnboardingSubmission); ok {
		r0 = returnFunc(ctx, tx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.OnboardingSubmission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, port.Tx, *port.OnboardingSubmission) error); ok {
		r1 = returnFunc(ctx, tx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OnboardingRepository_Submit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Submit'
type OnboardingRepository_Submit_Call struct {
	*mock.Call
}

// Submit is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - in *port.OnboardingSubmission
func (_e *OnboardingRepository_Expecter) Submit(ctx interface{}, tx interface{}, in interface{}) *OnboardingRepository_Submit_Call {
	return &OnboardingRepository_Submit_Call{Call: _e.mock.On("Submit", ctx, tx, in)}
}

func (_c *OnboardingRepository_Submit_Call) Run(run func(ctx context.Context, tx port.Tx, in *port.OnboardingSubmission)) *OnboardingRepository_Submit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 *port.OnboardingSubmission
		if args[2] != nil {
			arg2 = args[2].(*port.OnboardingSubmission)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OnboardingRepository_Submit_Call) Return(onboardingSubmission *port.OnboardingSubmission, err error) *OnboardingRepository_Submit_Call {
	_c.Call.Return(onboardingSubmission, err)
	return _c
}

func (_c *OnboardingRepository_Submit_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, in *port.OnboardingSubmission) (*port.OnboardingSubmission, error)) *OnboardingRepository_Submit_Call {
	_c.Call.Return(run)
	return _c
}
