// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewOnboardingService creates a new instance of OnboardingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOnboardingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OnboardingService {
	mock := &OnboardingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OnboardingService is an autogenerated mock type for the OnboardingService type
type OnboardingService struct {
	mock.Mock
}

type OnboardingService_Expecter struct {
	mock *mock.Mock
}

func (_m *OnboardingService) EXPECT() *OnboardingService_Expecter {
	return &OnboardingService_Expecter{mock: &_m.Mock}
}

// Decide provides a mock function for the type OnboardingService
func (_mock *OnboardingService) Decide(ctx context.Context, p domain.Principal, id domain.OnboardingID, approve bool, reason string) error {
	ret := _mock.Called(ctx, p, id, approve, reason)

	if len(ret) == 0 {
		panic("no return value specified for Decide")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.OnboardingID, bool, string) error); ok {
		r0 = returnFunc(ctx, p, id, approve, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OnboardingService_Decide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decide'
type OnboardingService_Decide_Call struct {
	*mock.Call
}

// Decide is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - id domain.OnboardingID
//   - approve bool
//   - reason string
func (_e *OnboardingService_Expecter) Decide(ctx interface{}, p interface{}, id interface{}, approve interface{}, reason interface{}) *OnboardingService_Decide_Call {
	return &OnboardingService_Decide_Call{Call: _e.mock.On("Decide", ctx, p, id, approve, reason)}
}

func (_c *OnboardingService_Decide_Call) Run(run func(ctx context.Context, p domain.Principal, id domain.OnboardingID, approve bool, reason string)) *OnboardingService_Decide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 domain.OnboardingID
		if args[2] != nil {
			arg2 = args[2].(domain.OnboardingID)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *OnboardingService_Decide_Call) Return(err error) *OnboardingService_Decide_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OnboardingService_Decide_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, id domain.OnboardingID, approve bool, reason string) error) *OnboardingService_Decide_Call {
	_c.Call.Return(run)
	return _c
}

// ExpireUnproven provides a mock function for the type OnboardingService
func (_mock *OnboardingService) ExpireUnproven(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ExpireUnproven")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OnboardingService_ExpireUnproven_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpireUnproven'
type OnboardingService_ExpireUnproven_Call struct {
	*mock.Call
}

// ExpireUnproven is a helper method to define mock.On call
//   - ctx context.Context
func (_e *OnboardingService_Expecter) ExpireUnproven(ctx interface{}) *OnboardingService_ExpireUnproven_Call {
	return &OnboardingService_ExpireUnproven_Call{Call: _e.mock.On("ExpireUnproven", ctx)}
}

func (_c *OnboardingService_ExpireUnproven_Call) Run(run func(ctx context.Context)) *OnboardingService_ExpireUnproven_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OnboardingService_ExpireUnproven_Call) Return(n int, err error) *OnboardingService_ExpireUnproven_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *OnboardingService_ExpireUnproven_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *OnboardingService_ExpireUnproven_Call {
	_c.Call.Return(run)
	return _c
}

// Queue provides a mock function for the type OnboardingService
func (_mock *OnboardingService) Queue(ctx context.Context, p domain.Principal) ([]port.OnboardingSubmission, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Queue")
	}

	var r0 []port.OnboardingSubmission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal) ([]port.OnboardingSubmission, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal) []port.OnboardingSubmission); ok {
		r0 = returnFunc(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.OnboardingSubmission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OnboardingService_Queue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Queue'
type OnboardingService_Queue_Call struct {
	*mock.Call
}

// Queue is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
func (_e *OnboardingService_Expecter) Queue(ctx interface{}, p interface{}) *OnboardingService_Queue_Call {
	return &OnboardingService_Queue_Call{Call: _e.mock.On("Queue", ctx, p)}
}

func (_c *OnboardingService_Queue_Call) Run(run func(ctx context.Context, p domain.Principal)) *OnboardingService_Queue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OnboardingService_Queue_Call) Return(onboardingSubmissions []port.OnboardingSubmission, err error) *OnboardingService_Queue_Call {
	_c.Call.Return(onboardingSubmissions, err)
	return _c
}

func (_c *OnboardingService_Queue_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal) ([]port.OnboardingSubmission, error)) *OnboardingService_Queue_Call {
	_c.Call.Return(run)
	return _c
}

// Revise provides a mock function for the type OnboardingService
func (_mock *OnboardingService) Revise(ctx context.Context, token string, in port.OnboardingForm) error {
	ret := _mock.Called(ctx, token, in)

	if len(ret) == 0 {
		panic("no return value specified for Revise")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, port.OnboardingForm) error); ok {
		r0 = returnFunc(ctx, token, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OnboardingService_Revise_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revise'
type OnboardingService_Revise_Call struct {
	*mock.Call
}

// Revise is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - in port.OnboardingForm
func (_e *OnboardingService_Expecter) Revise(ctx interface{}, token interface{}, in interface{}) *OnboardingService_Revise_Call {
	return &OnboardingService_Revise_Call{Call: _e.mock.On("Revise", ctx, token, in)}
}

func (_c *OnboardingService_Revise_Call) Run(run func(ctx context.Context, token string, in port.OnboardingForm)) *OnboardingService_Revise_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 port.OnboardingForm
		if args[2] != nil {
			arg2 = args[2].(port.OnboardingForm)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OnboardingService_Revise_Call) Return(err error) *OnboardingService_Revise_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OnboardingService_Revise_Call) RunAndReturn(run func(ctx context.Context, token string, in port.OnboardingForm) error) *OnboardingService_Revise_Call {
	_c.Call.Return(run)
	return _c
}

// Submit provides a mock function for the type OnboardingService
func (_mock *OnboardingService) Submit(ctx context.Context, in port.OnboardingForm) error {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.OnboardingForm) error); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OnboardingService_Submit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Submit'
type OnboardingService_Submit_Call struct {
	*mock.Call
}

// Submit is a helper method to define mock.On call
//   - ctx context.Context
//   - in port.OnboardingForm
func (_e *OnboardingService_Expecter) Submit(ctx interface{}, in interface{}) *OnboardingService_Submit_Call {
	return &OnboardingService_Submit_Call{Call: _e.mock.On("Submit", ctx, in)}
}

func (_c *OnboardingService_Submit_Call) Run(run func(ctx context.Context, in port.OnboardingForm)) *OnboardingService_Submit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.OnboardingForm
		if args[1] != nil {
			arg1 = args[1].(port.OnboardingForm)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OnboardingService_Submit_Call) Return(err error) *OnboardingService_Submit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OnboardingService_Submit_Call) RunAndReturn(run func(ctx context.Context, in port.OnboardingForm) error) *OnboardingService_Submit_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type OnboardingService
func (_mock *OnboardingService) Verify(ctx context.Context, token string, owner port.OnboardingOwnerInput) error {
	ret := _mock.Called(ctx, token, owner)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, port.OnboardingOwnerInput) error); ok {
		r0 = returnFunc(ctx, token, owner)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OnboardingService_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type OnboardingService_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - owner port.OnboardingOwnerInput
func (_e *OnboardingService_Expecter) Verify(ctx interface{}, token interface{}, owner interface{}) *OnboardingService_Verify_Call {
	return &OnboardingService_Verify_Call{Call: _e.mock.On("Verify", ctx, token, owner)}
}

func (_c *OnboardingService_Verify_Call) Run(run func(ctx context.Context, token string, owner port.OnboardingOwnerInput)) *OnboardingService_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 port.OnboardingOwnerInput
		if args[2] != nil {
			arg2 = args[2].(port.OnboardingOwnerInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OnboardingService_Verify_Call) Return(err error) *OnboardingService_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OnboardingService_Verify_Call) RunAndReturn(run func(ctx context.Context, token string, owner port.OnboardingOwnerInput) error) *OnboardingService_Verify_Call {
	_c.Call.Return(run)
	return _c
}
