// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewOrganizationService creates a new instance of OrganizationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationService {
	mock := &OrganizationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrganizationService is an autogenerated mock type for the OrganizationService type
type OrganizationService struct {
	mock.Mock
}

type OrganizationService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrganizationService) EXPECT() *OrganizationService_Expecter {
	return &OrganizationService_Expecter{mock: &_m.Mock}
}

// AcceptInvitation provides a mock function for the type OrganizationService
func (_mock *OrganizationService) AcceptInvitation(ctx context.Context, token string, displayName string, password string) (*domain.Hirer, *domain.TokenPair, error) {
	ret := _mock.Called(ctx, token, displayName, password)

	if len(ret) == 0 {
		panic("no return value specified for AcceptInvitation")
	}

	var r0 *domain.Hirer
	var r1 *domain.TokenPair
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*domain.Hirer, *domain.TokenPair, error)); ok {
		return returnFunc(ctx, token, displayName, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.Hirer); ok {
		r0 = returnFunc(ctx, token, displayName, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Hirer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) *domain.TokenPair); ok {
		r1 = returnFunc(ctx, token, displayName, password)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = returnFunc(ctx, token, displayName, password)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// OrganizationService_AcceptInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptInvitation'
type OrganizationService_AcceptInvitation_Call struct {
	*mock.Call
}

// AcceptInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - displayName string
//   - password string
func (_e *OrganizationService_Expecter) AcceptInvitation(ctx interface{}, token interface{}, displayName interface{}, password interface{}) *OrganizationService_AcceptInvitation_Call {
	return &OrganizationService_AcceptInvitation_Call{Call: _e.mock.On("AcceptInvitation", ctx, token, displayName, password)}
}

func (_c *OrganizationService_AcceptInvitation_Call) Run(run func(ctx context.Context, token string, displayName string, password string)) *OrganizationService_AcceptInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *OrganizationService_AcceptInvitation_Call) Return(hirer *domain.Hirer, tokenPair *domain.TokenPair, err error) *OrganizationService_AcceptInvitation_Call {
	_c.Call.Return(hirer, tokenPair, err)
	return _c
}

func (_c *OrganizationService_AcceptInvitation_Call) RunAndReturn(run func(ctx context.Context, token string, displayName string, password string) (*domain.Hirer, *domain.TokenPair, error)) *OrganizationService_AcceptInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// Invite provides a mock function for the type OrganizationService
func (_mock *OrganizationService) Invite(ctx context.Context, p domain.Principal, orgID domain.OrganizationID, email string, role domain.OrgRole) (*port.Invitation, string, error) {
	ret := _mock.Called(ctx, p, orgID, email, role)

	if len(ret) == 0 {
		panic("no return value specified for Invite")
	}

	var r0 *port.Invitation
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.OrganizationID, string, domain.OrgRole) (*port.Invitation, string, error)); ok {
		return returnFunc(ctx, p, orgID, email, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.OrganizationID, string, domain.OrgRole) *port.Invitation); ok {
		r0 = returnFunc(ctx, p, orgID, email, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.Invitation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal, domain.OrganizationID, string, domain.OrgRole) string); ok {
		r1 = returnFunc(ctx, p, orgID, email, role)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.Principal, domain.OrganizationID, string, domain.OrgRole) error); ok {
		r2 = returnFunc(ctx, p, orgID, email, role)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// OrganizationService_Invite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invite'
type OrganizationService_Invite_Call struct {
	*mock.Call
}

// Invite is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - orgID domain.OrganizationID
//   - email string
//   - role domain.OrgRole
func (_e *OrganizationService_Expecter) Invite(ctx interface{}, p interface{}, orgID interface{}, email interface{}, role interface{}) *OrganizationService_Invite_Call {
	return &OrganizationService_Invite_Call{Call: _e.mock.On("Invite", ctx, p, orgID, email, role)}
}

func (_c *OrganizationService_Invite_Call) Run(run func(ctx context.Context, p domain.Principal, orgID domain.OrganizationID, email string, role domain.OrgRole)) *OrganizationService_Invite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 domain.OrganizationID
		if args[2] != nil {
			arg2 = args[2].(domain.OrganizationID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 domain.OrgRole
		if args[4] != nil {
			arg4 = args[4].(domain.OrgRole)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *OrganizationService_Invite_Call) Return(invitation *port.Invitation, s string, err error) *OrganizationService_Invite_Call {
	_c.Call.Return(invitation, s, err)
	return _c
}

func (_c *OrganizationService_Invite_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, orgID domain.OrganizationID, email string, role domain.OrgRole) (*port.Invitation, string, error)) *OrganizationService_Invite_Call {
	_c.Call.Return(run)
	return _c
}

// Verification provides a mock function for the type OrganizationService
func (_mock *OrganizationService) Verification(ctx context.Context, p domain.Principal) (*port.VerificationStatus, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Verification")
	}

	var r0 *port.VerificationStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal) (*port.VerificationStatus, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal) *port.VerificationStatus); ok {
		r0 = returnFunc(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.VerificationStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrganizationService_Verification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verification'
type OrganizationService_Verification_Call struct {
	*mock.Call
}

// Verification is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
func (_e *OrganizationService_Expecter) Verification(ctx interface{}, p interface{}) *OrganizationService_Verification_Call {
	return &OrganizationService_Verification_Call{Call: _e.mock.On("Verification", ctx, p)}
}

func (_c *OrganizationService_Verification_Call) Run(run func(ctx context.Context, p domain.Principal)) *OrganizationService_Verification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrganizationService_Verification_Call) Return(verificationStatus *port.VerificationStatus, err error) *OrganizationService_Verification_Call {
	_c.Call.Return(verificationStatus, err)
	return _c
}

func (_c *OrganizationService_Verification_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal) (*port.VerificationStatus, error)) *OrganizationService_Verification_Call {
	_c.Call.Return(run)
	return _c
}
