// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewOrganizationRepository creates a new instance of OrganizationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationRepository {
	mock := &OrganizationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrganizationRepository is an autogenerated mock type for the OrganizationRepository type
type OrganizationRepository struct {
	mock.Mock
}

type OrganizationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrganizationRepository) EXPECT() *OrganizationRepository_Expecter {
	return &OrganizationRepository_Expecter{mock: &_m.Mock}
}

// AcceptInvitation provides a mock function for the type OrganizationRepository
func (_mock *OrganizationRepository) AcceptInvitation(ctx context.Context, tx port.Tx, id domain.RequestID, h *domain.Hirer, passwordHash []byte) (*domain.Hirer, error) {
	ret := _mock.Called(ctx, tx, id, h, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for AcceptInvitation")
	}

	var r0 *domain.Hirer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.RequestID, *domain.Hirer, []byte) (*domain.Hirer, error)); ok {
		return returnFunc(ctx, tx, id, h, passwordHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.RequestID, *domain.Hirer, []byte) *domain.Hirer); ok {
		r0 = returnFunc(ctx, tx, id, h, passwordHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Hirer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, port.Tx, domain.RequestID, *domain.Hirer, []byte) error); ok {
		r1 = returnFunc(ctx, tx, id, h, passwordHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrganizationRepository_AcceptInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptInvitation'
type OrganizationRepository_AcceptInvitation_Call struct {
	*mock.Call
}

// AcceptInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - id domain.RequestID
//   - h *domain.Hirer
//   - passwordHash []byte
func (_e *OrganizationRepository_Expecter) AcceptInvitation(ctx interface{}, tx interface{}, id interface{}, h interface{}, passwordHash interface{}) *OrganizationRepository_AcceptInvitation_Call {
	return &OrganizationRepository_AcceptInvitation_Call{Call: _e.mock.On("AcceptInvitation", ctx, tx, id, h, passwordHash)}
}

func (_c *OrganizationRepository_AcceptInvitation_Call) Run(run func(ctx context.Context, tx port.Tx, id domain.RequestID, h *domain.Hirer, passwordHash []byte)) *OrganizationRepository_AcceptInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 domain.RequestID
		if args[2] != nil {
			arg2 = args[2].(domain.RequestID)
		}
		var arg3 *domain.Hirer
		if args[3] != nil {
			arg3 = args[3].(*domain.Hirer)
		}
		var arg4 []byte
		if args[4] != nil {
			arg4 = args[4].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *OrganizationRepository_AcceptInvitation_Call) Return(hirer *domain.Hirer, err error) *OrganizationRepository_AcceptInvitation_Call {
	_c.Call.Return(hirer, err)
	return _c
}

func (_c *OrganizationRepository_AcceptInvitation_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, id domain.RequestID, h *domain.Hirer, passwordHash []byte) (*domain.Hirer, error)) *OrganizationRepository_AcceptInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInvitation provides a mock function for the type OrganizationRepository
func (_mock *OrganizationRepository) CreateInvitation(ctx context.Context, tx port.Tx, orgID domain.OrganizationID, email string, role domain.OrgRole, invitedBy domain.HirerID, tokenHash []byte, expiresAt time.Time) (domain.RequestID, error) {
	ret := _mock.Called(ctx, tx, orgID, email, role, invitedBy, tokenHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvitation")
	}

	var r0 domain.RequestID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.OrganizationID, string, domain.OrgRole, domain.HirerID, []byte, time.Time) (domain.RequestID, error)); ok {
		return returnFunc(ctx, tx, orgID, email, role, invitedBy, tokenHash, expiresAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.OrganizationID, string, domain.OrgRole, domain.HirerID, []byte, time.Time) domain.RequestID); ok {
		r0 = returnFunc(ctx, tx, orgID, email, role, invitedBy, tokenHash, expiresAt)
	} else {
		r0 = ret.Get(0).(domain.RequestID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, port.Tx, domain.OrganizationID, string, domain.OrgRole, domain.HirerID, []byte, time.Time) error); ok {
		r1 = returnFunc(ctx, tx, orgID, email, role, invitedBy, tokenHash, expiresAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrganizationRepository_CreateInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvitation'
type OrganizationRepository_CreateInvitation_Call struct {
	*mock.Call
}

// CreateInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - orgID domain.OrganizationID
//   - email string
//   - role domain.OrgRole
//   - invitedBy domain.HirerID
//   - tokenHash []byte
//   - expiresAt time.Time
func (_e *OrganizationRepository_Expecter) CreateInvitation(ctx interface{}, tx interface{}, orgID interface{}, email interface{}, role interface{}, invitedBy interface{}, tokenHash interface{}, expiresAt interface{}) *OrganizationRepository_CreateInvitation_Call {
	return &OrganizationRepository_CreateInvitation_Call{Call: _e.mock.On("CreateInvitation", ctx, tx, orgID, email, role, invitedBy, tokenHash, expiresAt)}
}

func (_c *OrganizationRepository_CreateInvitation_Call) Run(run func(ctx context.Context, tx port.Tx, orgID domain.OrganizationID, email string, role domain.OrgRole, invitedBy domain.HirerID, tokenHash []byte, expiresAt time.Time)) *OrganizationRepository_CreateInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 domain.OrganizationID
		if args[2] != nil {
			arg2 = args[2].(domain.OrganizationID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 domain.OrgRole
		if args[4] != nil {
			arg4 = args[4].(domain.OrgRole)
		}
		var arg5 domain.HirerID
		if args[5] != nil {
			arg5 = args[5].(domain.HirerID)
		}
		var arg6 []byte
		if args[6] != nil {
			arg6 = args[6].([]byte)
		}
		var arg7 time.Time
		if args[7] != nil {
			arg7 = args[7].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *OrganizationRepository_CreateInvitation_Call) Return(requestID domain.RequestID, err error) *OrganizationRepository_CreateInvitation_Call {
	_c.Call.Return(requestID, err)
	return _c
}

func (_c *OrganizationRepository_CreateInvitation_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, orgID domain.OrganizationID, email string, role domain.OrgRole, invitedBy domain.HirerID, tokenHash []byte, expiresAt time.Time) (domain.RequestID, error)) *OrganizationRepository_CreateInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// InvitationByTokenHash provides a mock function for the type OrganizationRepository
func (_mock *OrganizationRepository) InvitationByTokenHash(ctx context.Context, tx port.Tx, hash []byte) (*port.Invitation, error) {
	ret := _mock.Called(ctx, tx, hash)

	if len(ret) == 0 {
		panic("no return value specified for InvitationByTokenHash")
	}

	var r0 *port.Invitation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, []byte) (*port.Invitation, error)); ok {
		return returnFunc(ctx, tx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, []byte) *port.Invitation); ok {
		r0 = returnFunc(ctx, tx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.Invitation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, port.Tx, []byte) error); ok {
		r1 = returnFunc(ctx, tx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrganizationRepository_InvitationByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvitationByTokenHash'
type OrganizationRepository_InvitationByTokenHash_Call struct {
	*mock.Call
}

// InvitationByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - hash []byte
func (_e *OrganizationRepository_Expecter) InvitationByTokenHash(ctx interface{}, tx interface{}, hash interface{}) *OrganizationRepository_InvitationByTokenHash_Call {
	return &OrganizationRepository_InvitationByTokenHash_Call{Call: _e.mock.On("InvitationByTokenHash", ctx, tx, hash)}
}

func (_c *OrganizationRepository_InvitationByTokenHash_Call) Run(run func(ctx context.Context, tx port.Tx, hash []byte)) *OrganizationRepository_InvitationByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrganizationRepository_InvitationByTokenHash_Call) Return(invitation *port.Invitation, err error) *OrganizationRepository_InvitationByTokenHash_Call {
	_c.Call.Return(invitation, err)
	return _c
}

func (_c *OrganizationRepository_InvitationByTokenHash_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, hash []byte) (*port.Invitation, error)) *OrganizationRepository_InvitationByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// VerificationFor provides a mock function for the type OrganizationRepository
func (_mock *OrganizationRepository) VerificationFor(ctx context.Context, hirer domain.HirerID, org domain.OrganizationID) (*port.VerificationRequest, error) {
	ret := _mock.Called(ctx, hirer, org)

	if len(ret) == 0 {
		panic("no return value specified for VerificationFor")
	}

	var r0 *port.VerificationRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.HirerID, domain.OrganizationID) (*port.VerificationRequest, error)); ok {
		return returnFunc(ctx, hirer, org)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.HirerID, domain.OrganizationID) *port.VerificationRequest); ok {
		r0 = returnFunc(ctx, hirer, org)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.VerificationRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.HirerID, domain.OrganizationID) error); ok {
		r1 = returnFunc(ctx, hirer, org)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrganizationRepository_VerificationFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerificationFor'
type OrganizationRepository_VerificationFor_Call struct {
	*mock.Call
}

// VerificationFor is a helper method to define mock.On call
//   - ctx context.Context
//   - hirer domain.HirerID
//   - org domain.OrganizationID
func (_e *OrganizationRepository_Expecter) VerificationFor(ctx interface{}, hirer interface{}, org interface{}) *OrganizationRepository_VerificationFor_Call {
	return &OrganizationRepository_VerificationFor_Call{Call: _e.mock.On("VerificationFor", ctx, hirer, org)}
}

func (_c *OrganizationRepository_VerificationFor_Call) Run(run func(ctx context.Context, hirer domain.HirerID, org domain.OrganizationID)) *OrganizationRepository_VerificationFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.HirerID
		if args[1] != nil {
			arg1 = args[1].(domain.HirerID)
		}
		var arg2 domain.OrganizationID
		if args[2] != nil {
			arg2 = args[2].(domain.OrganizationID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrganizationRepository_VerificationFor_Call) Return(verificationRequest *port.VerificationRequest, err error) *OrganizationRepository_VerificationFor_Call {
	_c.Call.Return(verificationRequest, err)
	return _c
}

func (_c *OrganizationRepository_VerificationFor_Call) RunAndReturn(run func(ctx context.Context, hirer domain.HirerID, org domain.OrganizationID) (*port.VerificationRequest, error)) *OrganizationRepository_VerificationFor_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyOrganization provides a mock function for the type OrganizationRepository
func (_mock *OrganizationRepository) VerifyOrganization(ctx context.Context, tx port.Tx, id domain.OrganizationID, by domain.AdminID, reason string) error {
	ret := _mock.Called(ctx, tx, id, by, reason)

	if len(ret) == 0 {
		panic("no return value specified for VerifyOrganization")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.OrganizationID, domain.AdminID, string) error); ok {
		r0 = returnFunc(ctx, tx, id, by, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrganizationRepository_VerifyOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyOrganization'
type OrganizationRepository_VerifyOrganization_Call struct {
	*mock.Call
}

// VerifyOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - id domain.OrganizationID
//   - by domain.AdminID
//   - reason string
func (_e *OrganizationRepository_Expecter) VerifyOrganization(ctx interface{}, tx interface{}, id interface{}, by interface{}, reason interface{}) *OrganizationRepository_VerifyOrganization_Call {
	return &OrganizationRepository_VerifyOrganization_Call{Call: _e.mock.On("VerifyOrganization", ctx, tx, id, by, reason)}
}

func (_c *OrganizationRepository_VerifyOrganization_Call) Run(run func(ctx context.Context, tx port.Tx, id domain.OrganizationID, by domain.AdminID, reason string)) *OrganizationRepository_VerifyOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 domain.OrganizationID
		if args[2] != nil {
			arg2 = args[2].(domain.OrganizationID)
		}
		var arg3 domain.AdminID
		if args[3] != nil {
			arg3 = args[3].(domain.AdminID)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *OrganizationRepository_VerifyOrganization_Call) Return(err error) *OrganizationRepository_VerifyOrganization_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrganizationRepository_VerifyOrganization_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, id domain.OrganizationID, by domain.AdminID, reason string) error) *OrganizationRepository_VerifyOrganization_Call {
	_c.Call.Return(run)
	return _c
}
