// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewPasswordHasher creates a new instance of PasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordHasher {
	mock := &PasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PasswordHasher is an autogenerated mock type for the PasswordHasher type
type PasswordHasher struct {
	mock.Mock
}

type PasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *PasswordHasher) EXPECT() *PasswordHasher_Expecter {
	return &PasswordHasher_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function for the type PasswordHasher
func (_mock *PasswordHasher) Hash(plaintext string) ([]byte, error) {
	ret := _mock.Called(plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(plaintext)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(plaintext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(plaintext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PasswordHasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type PasswordHasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - plaintext string
func (_e *PasswordHasher_Expecter) Hash(plaintext interface{}) *PasswordHasher_Hash_Call {
	return &PasswordHasher_Hash_Call{Call: _e.mock.On("Hash", plaintext)}
}

func (_c *PasswordHasher_Hash_Call) Run(run func(plaintext string)) *PasswordHasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PasswordHasher_Hash_Call) Return(bytes []byte, err error) *PasswordHasher_Hash_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *PasswordHasher_Hash_Call) RunAndReturn(run func(plaintext string) ([]byte, error)) *PasswordHasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type PasswordHasher
func (_mock *PasswordHasher) Verify(hash []byte, plaintext string) bool {
	ret := _mock.Called(hash, plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func([]byte, string) bool); ok {
		r0 = returnFunc(hash, plaintext)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// PasswordHasher_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type PasswordHasher_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - hash []byte
//   - plaintext string
func (_e *PasswordHasher_Expecter) Verify(hash interface{}, plaintext interface{}) *PasswordHasher_Verify_Call {
	return &PasswordHasher_Verify_Call{Call: _e.mock.On("Verify", hash, plaintext)}
}

func (_c *PasswordHasher_Verify_Call) Run(run func(hash []byte, plaintext string)) *PasswordHasher_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasswordHasher_Verify_Call) Return(b bool) *PasswordHasher_Verify_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *PasswordHasher_Verify_Call) RunAndReturn(run func(hash []byte, plaintext string) bool) *PasswordHasher_Verify_Call {
	_c.Call.Return(run)
	return _c
}
