// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewPrincipalResolver creates a new instance of PrincipalResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrincipalResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrincipalResolver {
	mock := &PrincipalResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PrincipalResolver is an autogenerated mock type for the PrincipalResolver type
type PrincipalResolver struct {
	mock.Mock
}

type PrincipalResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *PrincipalResolver) EXPECT() *PrincipalResolver_Expecter {
	return &PrincipalResolver_Expecter{mock: &_m.Mock}
}

// Wrap provides a mock function for the type PrincipalResolver
func (_mock *PrincipalResolver) Wrap(next http.Handler) http.Handler {
	ret := _mock.Called(next)

	if len(ret) == 0 {
		panic("no return value specified for Wrap")
	}

	var r0 http.Handler
	if returnFunc, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = returnFunc(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}
	return r0
}

// PrincipalResolver_Wrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wrap'
type PrincipalResolver_Wrap_Call struct {
	*mock.Call
}

// Wrap is a helper method to define mock.On call
//   - next http.Handler
func (_e *PrincipalResolver_Expecter) Wrap(next interface{}) *PrincipalResolver_Wrap_Call {
	return &PrincipalResolver_Wrap_Call{Call: _e.mock.On("Wrap", next)}
}

func (_c *PrincipalResolver_Wrap_Call) Run(run func(next http.Handler)) *PrincipalResolver_Wrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.Handler
		if args[0] != nil {
			arg0 = args[0].(http.Handler)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PrincipalResolver_Wrap_Call) Return(handler http.Handler) *PrincipalResolver_Wrap_Call {
	_c.Call.Return(handler)
	return _c
}

func (_c *PrincipalResolver_Wrap_Call) RunAndReturn(run func(next http.Handler) http.Handler) *PrincipalResolver_Wrap_Call {
	_c.Call.Return(run)
	return _c
}
