// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewRedemptionService creates a new instance of RedemptionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedemptionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedemptionService {
	mock := &RedemptionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RedemptionService is an autogenerated mock type for the RedemptionService type
type RedemptionService struct {
	mock.Mock
}

type RedemptionService_Expecter struct {
	mock *mock.Mock
}

func (_m *RedemptionService) EXPECT() *RedemptionService_Expecter {
	return &RedemptionService_Expecter{mock: &_m.Mock}
}

// CompleteRedemption provides a mock function for the type RedemptionService
func (_mock *RedemptionService) CompleteRedemption(ctx context.Context, token string, displayName string, password string) (*domain.Hirer, *domain.TokenPair, error) {
	ret := _mock.Called(ctx, token, displayName, password)

	if len(ret) == 0 {
		panic("no return value specified for CompleteRedemption")
	}

	var r0 *domain.Hirer
	var r1 *domain.TokenPair
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*domain.Hirer, *domain.TokenPair, error)); ok {
		return returnFunc(ctx, token, displayName, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.Hirer); ok {
		r0 = returnFunc(ctx, token, displayName, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Hirer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) *domain.TokenPair); ok {
		r1 = returnFunc(ctx, token, displayName, password)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = returnFunc(ctx, token, displayName, password)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// RedemptionService_CompleteRedemption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteRedemption'
type RedemptionService_CompleteRedemption_Call struct {
	*mock.Call
}

// CompleteRedemption is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - displayName string
//   - password string
func (_e *RedemptionService_Expecter) CompleteRedemption(ctx interface{}, token interface{}, displayName interface{}, password interface{}) *RedemptionService_CompleteRedemption_Call {
	return &RedemptionService_CompleteRedemption_Call{Call: _e.mock.On("CompleteRedemption", ctx, token, displayName, password)}
}

func (_c *RedemptionService_CompleteRedemption_Call) Run(run func(ctx context.Context, token string, displayName string, password string)) *RedemptionService_CompleteRedemption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RedemptionService_CompleteRedemption_Call) Return(hirer *domain.Hirer, tokenPair *domain.TokenPair, err error) *RedemptionService_CompleteRedemption_Call {
	_c.Call.Return(hirer, tokenPair, err)
	return _c
}

func (_c *RedemptionService_CompleteRedemption_Call) RunAndReturn(run func(ctx context.Context, token string, displayName string, password string) (*domain.Hirer, *domain.TokenPair, error)) *RedemptionService_CompleteRedemption_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrganizations provides a mock function for the type RedemptionService
func (_mock *RedemptionService) ListOrganizations(ctx context.Context) ([]domain.Organization, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListOrganizations")
	}

	var r0 []domain.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Organization, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Organization); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RedemptionService_ListOrganizations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrganizations'
type RedemptionService_ListOrganizations_Call struct {
	*mock.Call
}

// ListOrganizations is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RedemptionService_Expecter) ListOrganizations(ctx interface{}) *RedemptionService_ListOrganizations_Call {
	return &RedemptionService_ListOrganizations_Call{Call: _e.mock.On("ListOrganizations", ctx)}
}

func (_c *RedemptionService_ListOrganizations_Call) Run(run func(ctx context.Context)) *RedemptionService_ListOrganizations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RedemptionService_ListOrganizations_Call) Return(organizations []domain.Organization, err error) *RedemptionService_ListOrganizations_Call {
	_c.Call.Return(organizations, err)
	return _c
}

func (_c *RedemptionService_ListOrganizations_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Organization, error)) *RedemptionService_ListOrganizations_Call {
	_c.Call.Return(run)
	return _c
}

// ResendVerification provides a mock function for the type RedemptionService
func (_mock *RedemptionService) ResendVerification(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ResendVerification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RedemptionService_ResendVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResendVerification'
type RedemptionService_ResendVerification_Call struct {
	*mock.Call
}

// ResendVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *RedemptionService_Expecter) ResendVerification(ctx interface{}, email interface{}) *RedemptionService_ResendVerification_Call {
	return &RedemptionService_ResendVerification_Call{Call: _e.mock.On("ResendVerification", ctx, email)}
}

func (_c *RedemptionService_ResendVerification_Call) Run(run func(ctx context.Context, email string)) *RedemptionService_ResendVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RedemptionService_ResendVerification_Call) Return(err error) *RedemptionService_ResendVerification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RedemptionService_ResendVerification_Call) RunAndReturn(run func(ctx context.Context, email string) error) *RedemptionService_ResendVerification_Call {
	_c.Call.Return(run)
	return _c
}

// StartRedemption provides a mock function for the type RedemptionService
func (_mock *RedemptionService) StartRedemption(ctx context.Context, orgSlug string, email string) error {
	ret := _mock.Called(ctx, orgSlug, email)

	if len(ret) == 0 {
		panic("no return value specified for StartRedemption")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, orgSlug, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RedemptionService_StartRedemption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartRedemption'
type RedemptionService_StartRedemption_Call struct {
	*mock.Call
}

// StartRedemption is a helper method to define mock.On call
//   - ctx context.Context
//   - orgSlug string
//   - email string
func (_e *RedemptionService_Expecter) StartRedemption(ctx interface{}, orgSlug interface{}, email interface{}) *RedemptionService_StartRedemption_Call {
	return &RedemptionService_StartRedemption_Call{Call: _e.mock.On("StartRedemption", ctx, orgSlug, email)}
}

func (_c *RedemptionService_StartRedemption_Call) Run(run func(ctx context.Context, orgSlug string, email string)) *RedemptionService_StartRedemption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RedemptionService_StartRedemption_Call) Return(err error) *RedemptionService_StartRedemption_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RedemptionService_StartRedemption_Call) RunAndReturn(run func(ctx context.Context, orgSlug string, email string) error) *RedemptionService_StartRedemption_Call {
	_c.Call.Return(run)
	return _c
}
