// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewReevaluationRepository creates a new instance of ReevaluationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReevaluationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReevaluationRepository {
	mock := &ReevaluationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ReevaluationRepository is an autogenerated mock type for the ReevaluationRepository type
type ReevaluationRepository struct {
	mock.Mock
}

type ReevaluationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReevaluationRepository) EXPECT() *ReevaluationRepository_Expecter {
	return &ReevaluationRepository_Expecter{mock: &_m.Mock}
}

// ByStatus provides a mock function for the type ReevaluationRepository
func (_mock *ReevaluationRepository) ByStatus(ctx context.Context, status string) ([]domain.ReevaluationRequest, error) {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for ByStatus")
	}

	var r0 []domain.ReevaluationRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.ReevaluationRequest, error)); ok {
		return returnFunc(ctx, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.ReevaluationRequest); ok {
		r0 = returnFunc(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReevaluationRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReevaluationRepository_ByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByStatus'
type ReevaluationRepository_ByStatus_Call struct {
	*mock.Call
}

// ByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
func (_e *ReevaluationRepository_Expecter) ByStatus(ctx interface{}, status interface{}) *ReevaluationRepository_ByStatus_Call {
	return &ReevaluationRepository_ByStatus_Call{Call: _e.mock.On("ByStatus", ctx, status)}
}

func (_c *ReevaluationRepository_ByStatus_Call) Run(run func(ctx context.Context, status string)) *ReevaluationRepository_ByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ReevaluationRepository_ByStatus_Call) Return(reevaluationRequests []domain.ReevaluationRequest, err error) *ReevaluationRepository_ByStatus_Call {
	_c.Call.Return(reevaluationRequests, err)
	return _c
}

func (_c *ReevaluationRepository_ByStatus_Call) RunAndReturn(run func(ctx context.Context, status string) ([]domain.ReevaluationRequest, error)) *ReevaluationRepository_ByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Cooldown provides a mock function for the type ReevaluationRepository
func (_mock *ReevaluationRepository) Cooldown(ctx context.Context, id domain.UserID) (*domain.Cooldown, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Cooldown")
	}

	var r0 *domain.Cooldown
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) (*domain.Cooldown, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) *domain.Cooldown); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Cooldown)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReevaluationRepository_Cooldown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cooldown'
type ReevaluationRepository_Cooldown_Call struct {
	*mock.Call
}

// Cooldown is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.UserID
func (_e *ReevaluationRepository_Expecter) Cooldown(ctx interface{}, id interface{}) *ReevaluationRepository_Cooldown_Call {
	return &ReevaluationRepository_Cooldown_Call{Call: _e.mock.On("Cooldown", ctx, id)}
}

func (_c *ReevaluationRepository_Cooldown_Call) Run(run func(ctx context.Context, id domain.UserID)) *ReevaluationRepository_Cooldown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ReevaluationRepository_Cooldown_Call) Return(cooldown *domain.Cooldown, err error) *ReevaluationRepository_Cooldown_Call {
	_c.Call.Return(cooldown, err)
	return _c
}

func (_c *ReevaluationRepository_Cooldown_Call) RunAndReturn(run func(ctx context.Context, id domain.UserID) (*domain.Cooldown, error)) *ReevaluationRepository_Cooldown_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type ReevaluationRepository
func (_mock *ReevaluationRepository) Create(ctx context.Context, r *domain.ReevaluationRequest) (*domain.ReevaluationRequest, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.ReevaluationRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ReevaluationRequest) (*domain.ReevaluationRequest, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ReevaluationRequest) *domain.ReevaluationRequest); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ReevaluationRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.ReevaluationRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReevaluationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ReevaluationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - r *domain.ReevaluationRequest
func (_e *ReevaluationRepository_Expecter) Create(ctx interface{}, r interface{}) *ReevaluationRepository_Create_Call {
	return &ReevaluationRepository_Create_Call{Call: _e.mock.On("Create", ctx, r)}
}

func (_c *ReevaluationRepository_Create_Call) Run(run func(ctx context.Context, r *domain.ReevaluationRequest)) *ReevaluationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.ReevaluationRequest
		if args[1] != nil {
			arg1 = args[1].(*domain.ReevaluationRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ReevaluationRepository_Create_Call) Return(reevaluationRequest *domain.ReevaluationRequest, err error) *ReevaluationRepository_Create_Call {
	_c.Call.Return(reevaluationRequest, err)
	return _c
}

func (_c *ReevaluationRepository_Create_Call) RunAndReturn(run func(ctx context.Context, r *domain.ReevaluationRequest) (*domain.ReevaluationRequest, error)) *ReevaluationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Decide provides a mock function for the type ReevaluationRepository
func (_mock *ReevaluationRepository) Decide(ctx context.Context, tx port.Tx, id domain.RequestID, by domain.AdminID, accept bool, reason string) error {
	ret := _mock.Called(ctx, tx, id, by, accept, reason)

	if len(ret) == 0 {
		panic("no return value specified for Decide")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.RequestID, domain.AdminID, bool, string) error); ok {
		r0 = returnFunc(ctx, tx, id, by, accept, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReevaluationRepository_Decide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decide'
type ReevaluationRepository_Decide_Call struct {
	*mock.Call
}

// Decide is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - id domain.RequestID
//   - by domain.AdminID
//   - accept bool
//   - reason string
func (_e *ReevaluationRepository_Expecter) Decide(ctx interface{}, tx interface{}, id interface{}, by interface{}, accept interface{}, reason interface{}) *ReevaluationRepository_Decide_Call {
	return &ReevaluationRepository_Decide_Call{Call: _e.mock.On("Decide", ctx, tx, id, by, accept, reason)}
}

func (_c *ReevaluationRepository_Decide_Call) Run(run func(ctx context.Context, tx port.Tx, id domain.RequestID, by domain.AdminID, accept bool, reason string)) *ReevaluationRepository_Decide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 domain.RequestID
		if args[2] != nil {
			arg2 = args[2].(domain.RequestID)
		}
		var arg3 domain.AdminID
		if args[3] != nil {
			arg3 = args[3].(domain.AdminID)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *ReevaluationRepository_Decide_Call) Return(err error) *ReevaluationRepository_Decide_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReevaluationRepository_Decide_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, id domain.RequestID, by domain.AdminID, accept bool, reason string) error) *ReevaluationRepository_Decide_Call {
	_c.Call.Return(run)
	return _c
}

// OpenRequest provides a mock function for the type ReevaluationRepository
func (_mock *ReevaluationRepository) OpenRequest(ctx context.Context, id domain.UserID) (*domain.ReevaluationRequest, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for OpenRequest")
	}

	var r0 *domain.ReevaluationRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) (*domain.ReevaluationRequest, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) *domain.ReevaluationRequest); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ReevaluationRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReevaluationRepository_OpenRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenRequest'
type ReevaluationRepository_OpenRequest_Call struct {
	*mock.Call
}

// OpenRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.UserID
func (_e *ReevaluationRepository_Expecter) OpenRequest(ctx interface{}, id interface{}) *ReevaluationRepository_OpenRequest_Call {
	return &ReevaluationRepository_OpenRequest_Call{Call: _e.mock.On("OpenRequest", ctx, id)}
}

func (_c *ReevaluationRepository_OpenRequest_Call) Run(run func(ctx context.Context, id domain.UserID)) *ReevaluationRepository_OpenRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ReevaluationRepository_OpenRequest_Call) Return(reevaluationRequest *domain.ReevaluationRequest, err error) *ReevaluationRepository_OpenRequest_Call {
	_c.Call.Return(reevaluationRequest, err)
	return _c
}

func (_c *ReevaluationRepository_OpenRequest_Call) RunAndReturn(run func(ctx context.Context, id domain.UserID) (*domain.ReevaluationRequest, error)) *ReevaluationRepository_OpenRequest_Call {
	_c.Call.Return(run)
	return _c
}

// Pending provides a mock function for the type ReevaluationRepository
func (_mock *ReevaluationRepository) Pending(ctx context.Context) ([]domain.ReevaluationRequest, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Pending")
	}

	var r0 []domain.ReevaluationRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.ReevaluationRequest, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.ReevaluationRequest); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReevaluationRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReevaluationRepository_Pending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pending'
type ReevaluationRepository_Pending_Call struct {
	*mock.Call
}

// Pending is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ReevaluationRepository_Expecter) Pending(ctx interface{}) *ReevaluationRepository_Pending_Call {
	return &ReevaluationRepository_Pending_Call{Call: _e.mock.On("Pending", ctx)}
}

func (_c *ReevaluationRepository_Pending_Call) Run(run func(ctx context.Context)) *ReevaluationRepository_Pending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ReevaluationRepository_Pending_Call) Return(reevaluationRequests []domain.ReevaluationRequest, err error) *ReevaluationRepository_Pending_Call {
	_c.Call.Return(reevaluationRequests, err)
	return _c
}

func (_c *ReevaluationRepository_Pending_Call) RunAndReturn(run func(ctx context.Context) ([]domain.ReevaluationRequest, error)) *ReevaluationRepository_Pending_Call {
	_c.Call.Return(run)
	return _c
}
