// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewReevaluationService creates a new instance of ReevaluationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReevaluationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReevaluationService {
	mock := &ReevaluationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ReevaluationService is an autogenerated mock type for the ReevaluationService type
type ReevaluationService struct {
	mock.Mock
}

type ReevaluationService_Expecter struct {
	mock *mock.Mock
}

func (_m *ReevaluationService) EXPECT() *ReevaluationService_Expecter {
	return &ReevaluationService_Expecter{mock: &_m.Mock}
}

// Request provides a mock function for the type ReevaluationService
func (_mock *ReevaluationService) Request(ctx context.Context, id domain.UserID, claimID domain.ClaimID, reason string) (*domain.ReevaluationRequest, error) {
	ret := _mock.Called(ctx, id, claimID, reason)

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 *domain.ReevaluationRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, domain.ClaimID, string) (*domain.ReevaluationRequest, error)); ok {
		return returnFunc(ctx, id, claimID, reason)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, domain.ClaimID, string) *domain.ReevaluationRequest); ok {
		r0 = returnFunc(ctx, id, claimID, reason)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ReevaluationRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, domain.ClaimID, string) error); ok {
		r1 = returnFunc(ctx, id, claimID, reason)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReevaluationService_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type ReevaluationService_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.UserID
//   - claimID domain.ClaimID
//   - reason string
func (_e *ReevaluationService_Expecter) Request(ctx interface{}, id interface{}, claimID interface{}, reason interface{}) *ReevaluationService_Request_Call {
	return &ReevaluationService_Request_Call{Call: _e.mock.On("Request", ctx, id, claimID, reason)}
}

func (_c *ReevaluationService_Request_Call) Run(run func(ctx context.Context, id domain.UserID, claimID domain.ClaimID, reason string)) *ReevaluationService_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 domain.ClaimID
		if args[2] != nil {
			arg2 = args[2].(domain.ClaimID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ReevaluationService_Request_Call) Return(reevaluationRequest *domain.ReevaluationRequest, err error) *ReevaluationService_Request_Call {
	_c.Call.Return(reevaluationRequest, err)
	return _c
}

func (_c *ReevaluationService_Request_Call) RunAndReturn(run func(ctx context.Context, id domain.UserID, claimID domain.ClaimID, reason string) (*domain.ReevaluationRequest, error)) *ReevaluationService_Request_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type ReevaluationService
func (_mock *ReevaluationService) Status(ctx context.Context, id domain.UserID) (*domain.Cooldown, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *domain.Cooldown
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) (*domain.Cooldown, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) *domain.Cooldown); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Cooldown)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReevaluationService_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type ReevaluationService_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.UserID
func (_e *ReevaluationService_Expecter) Status(ctx interface{}, id interface{}) *ReevaluationService_Status_Call {
	return &ReevaluationService_Status_Call{Call: _e.mock.On("Status", ctx, id)}
}

func (_c *ReevaluationService_Status_Call) Run(run func(ctx context.Context, id domain.UserID)) *ReevaluationService_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ReevaluationService_Status_Call) Return(cooldown *domain.Cooldown, err error) *ReevaluationService_Status_Call {
	_c.Call.Return(cooldown, err)
	return _c
}

func (_c *ReevaluationService_Status_Call) RunAndReturn(run func(ctx context.Context, id domain.UserID) (*domain.Cooldown, error)) *ReevaluationService_Status_Call {
	_c.Call.Return(run)
	return _c
}
