// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewSavedSearchRepository creates a new instance of SavedSearchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSavedSearchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SavedSearchRepository {
	mock := &SavedSearchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SavedSearchRepository is an autogenerated mock type for the SavedSearchRepository type
type SavedSearchRepository struct {
	mock.Mock
}

type SavedSearchRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SavedSearchRepository) EXPECT() *SavedSearchRepository_Expecter {
	return &SavedSearchRepository_Expecter{mock: &_m.Mock}
}

// ByID provides a mock function for the type SavedSearchRepository
func (_mock *SavedSearchRepository) ByID(ctx context.Context, id domain.SavedSearchID) (*domain.SavedSearch, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 *domain.SavedSearch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SavedSearchID) (*domain.SavedSearch, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SavedSearchID) *domain.SavedSearch); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SavedSearch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SavedSearchID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SavedSearchRepository_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type SavedSearchRepository_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.SavedSearchID
func (_e *SavedSearchRepository_Expecter) ByID(ctx interface{}, id interface{}) *SavedSearchRepository_ByID_Call {
	return &SavedSearchRepository_ByID_Call{Call: _e.mock.On("ByID", ctx, id)}
}

func (_c *SavedSearchRepository_ByID_Call) Run(run func(ctx context.Context, id domain.SavedSearchID)) *SavedSearchRepository_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SavedSearchID
		if args[1] != nil {
			arg1 = args[1].(domain.SavedSearchID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SavedSearchRepository_ByID_Call) Return(savedSearch *domain.SavedSearch, err error) *SavedSearchRepository_ByID_Call {
	_c.Call.Return(savedSearch, err)
	return _c
}

func (_c *SavedSearchRepository_ByID_Call) RunAndReturn(run func(ctx context.Context, id domain.SavedSearchID) (*domain.SavedSearch, error)) *SavedSearchRepository_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type SavedSearchRepository
func (_mock *SavedSearchRepository) Create(ctx context.Context, s *domain.SavedSearch) (*domain.SavedSearch, error) {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.SavedSearch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.SavedSearch) (*domain.SavedSearch, error)); ok {
		return returnFunc(ctx, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.SavedSearch) *domain.SavedSearch); ok {
		r0 = returnFunc(ctx, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SavedSearch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.SavedSearch) error); ok {
		r1 = returnFunc(ctx, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SavedSearchRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SavedSearchRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s *domain.SavedSearch
func (_e *SavedSearchRepository_Expecter) Create(ctx interface{}, s interface{}) *SavedSearchRepository_Create_Call {
	return &SavedSearchRepository_Create_Call{Call: _e.mock.On("Create", ctx, s)}
}

func (_c *SavedSearchRepository_Create_Call) Run(run func(ctx context.Context, s *domain.SavedSearch)) *SavedSearchRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.SavedSearch
		if args[1] != nil {
			arg1 = args[1].(*domain.SavedSearch)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SavedSearchRepository_Create_Call) Return(savedSearch *domain.SavedSearch, err error) *SavedSearchRepository_Create_Call {
	_c.Call.Return(savedSearch, err)
	return _c
}

func (_c *SavedSearchRepository_Create_Call) RunAndReturn(run func(ctx context.Context, s *domain.SavedSearch) (*domain.SavedSearch, error)) *SavedSearchRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type SavedSearchRepository
func (_mock *SavedSearchRepository) Delete(ctx context.Context, id domain.SavedSearchID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SavedSearchID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SavedSearchRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SavedSearchRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.SavedSearchID
func (_e *SavedSearchRepository_Expecter) Delete(ctx interface{}, id interface{}) *SavedSearchRepository_Delete_Call {
	return &SavedSearchRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *SavedSearchRepository_Delete_Call) Run(run func(ctx context.Context, id domain.SavedSearchID)) *SavedSearchRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SavedSearchID
		if args[1] != nil {
			arg1 = args[1].(domain.SavedSearchID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SavedSearchRepository_Delete_Call) Return(err error) *SavedSearchRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SavedSearchRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id domain.SavedSearchID) error) *SavedSearchRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOrganization provides a mock function for the type SavedSearchRepository
func (_mock *SavedSearchRepository) ListByOrganization(ctx context.Context, id domain.OrganizationID) ([]domain.SavedSearch, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ListByOrganization")
	}

	var r0 []domain.SavedSearch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) ([]domain.SavedSearch, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID) []domain.SavedSearch); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SavedSearch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.OrganizationID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SavedSearchRepository_ListByOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOrganization'
type SavedSearchRepository_ListByOrganization_Call struct {
	*mock.Call
}

// ListByOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.OrganizationID
func (_e *SavedSearchRepository_Expecter) ListByOrganization(ctx interface{}, id interface{}) *SavedSearchRepository_ListByOrganization_Call {
	return &SavedSearchRepository_ListByOrganization_Call{Call: _e.mock.On("ListByOrganization", ctx, id)}
}

func (_c *SavedSearchRepository_ListByOrganization_Call) Run(run func(ctx context.Context, id domain.OrganizationID)) *SavedSearchRepository_ListByOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.OrganizationID
		if args[1] != nil {
			arg1 = args[1].(domain.OrganizationID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SavedSearchRepository_ListByOrganization_Call) Return(savedSearchs []domain.SavedSearch, err error) *SavedSearchRepository_ListByOrganization_Call {
	_c.Call.Return(savedSearchs, err)
	return _c
}

func (_c *SavedSearchRepository_ListByOrganization_Call) RunAndReturn(run func(ctx context.Context, id domain.OrganizationID) ([]domain.SavedSearch, error)) *SavedSearchRepository_ListByOrganization_Call {
	_c.Call.Return(run)
	return _c
}
