// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewServer creates a new instance of Server. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Server {
	mock := &Server{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Server is an autogenerated mock type for the Server type
type Server struct {
	mock.Mock
}

type Server_Expecter struct {
	mock *mock.Mock
}

func (_m *Server) EXPECT() *Server_Expecter {
	return &Server_Expecter{mock: &_m.Mock}
}

// ListenAndServe provides a mock function for the type Server
func (_mock *Server) ListenAndServe(addr string) error {
	ret := _mock.Called(addr)

	if len(ret) == 0 {
		panic("no return value specified for ListenAndServe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(addr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Server_ListenAndServe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListenAndServe'
type Server_ListenAndServe_Call struct {
	*mock.Call
}

// ListenAndServe is a helper method to define mock.On call
//   - addr string
func (_e *Server_Expecter) ListenAndServe(addr interface{}) *Server_ListenAndServe_Call {
	return &Server_ListenAndServe_Call{Call: _e.mock.On("ListenAndServe", addr)}
}

func (_c *Server_ListenAndServe_Call) Run(run func(addr string)) *Server_ListenAndServe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Server_ListenAndServe_Call) Return(err error) *Server_ListenAndServe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Server_ListenAndServe_Call) RunAndReturn(run func(addr string) error) *Server_ListenAndServe_Call {
	_c.Call.Return(run)
	return _c
}

// Mount provides a mock function for the type Server
func (_mock *Server) Mount(controllers ...port.Controller) {
	if len(controllers) > 0 {
		_mock.Called(controllers)
	} else {
		_mock.Called()
	}

	return
}

// Server_Mount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mount'
type Server_Mount_Call struct {
	*mock.Call
}

// Mount is a helper method to define mock.On call
//   - controllers ...port.Controller
func (_e *Server_Expecter) Mount(controllers ...interface{}) *Server_Mount_Call {
	return &Server_Mount_Call{Call: _e.mock.On("Mount",
		append([]interface{}{}, controllers...)...)}
}

func (_c *Server_Mount_Call) Run(run func(controllers ...port.Controller)) *Server_Mount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []port.Controller
		var variadicArgs []port.Controller
		if len(args) > 0 {
			variadicArgs = args[0].([]port.Controller)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Server_Mount_Call) Return() *Server_Mount_Call {
	_c.Call.Return()
	return _c
}

func (_c *Server_Mount_Call) RunAndReturn(run func(controllers ...port.Controller)) *Server_Mount_Call {
	_c.Run(run)
	return _c
}

// Shutdown provides a mock function for the type Server
func (_mock *Server) Shutdown() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Server_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type Server_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *Server_Expecter) Shutdown() *Server_Shutdown_Call {
	return &Server_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *Server_Shutdown_Call) Run(run func()) *Server_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Server_Shutdown_Call) Return(err error) *Server_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Server_Shutdown_Call) RunAndReturn(run func() error) *Server_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}
