// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewShortlistService creates a new instance of ShortlistService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortlistService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortlistService {
	mock := &ShortlistService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ShortlistService is an autogenerated mock type for the ShortlistService type
type ShortlistService struct {
	mock.Mock
}

type ShortlistService_Expecter struct {
	mock *mock.Mock
}

func (_m *ShortlistService) EXPECT() *ShortlistService_Expecter {
	return &ShortlistService_Expecter{mock: &_m.Mock}
}

// AddEntry provides a mock function for the type ShortlistService
func (_mock *ShortlistService) AddEntry(ctx context.Context, p domain.Principal, id domain.ShortlistID, target domain.UserID, note string) (*domain.ShortlistEntry, error) {
	ret := _mock.Called(ctx, p, id, target, note)

	if len(ret) == 0 {
		panic("no return value specified for AddEntry")
	}

	var r0 *domain.ShortlistEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.ShortlistID, domain.UserID, string) (*domain.ShortlistEntry, error)); ok {
		return returnFunc(ctx, p, id, target, note)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.ShortlistID, domain.UserID, string) *domain.ShortlistEntry); ok {
		r0 = returnFunc(ctx, p, id, target, note)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ShortlistEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal, domain.ShortlistID, domain.UserID, string) error); ok {
		r1 = returnFunc(ctx, p, id, target, note)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShortlistService_AddEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEntry'
type ShortlistService_AddEntry_Call struct {
	*mock.Call
}

// AddEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - id domain.ShortlistID
//   - target domain.UserID
//   - note string
func (_e *ShortlistService_Expecter) AddEntry(ctx interface{}, p interface{}, id interface{}, target interface{}, note interface{}) *ShortlistService_AddEntry_Call {
	return &ShortlistService_AddEntry_Call{Call: _e.mock.On("AddEntry", ctx, p, id, target, note)}
}

func (_c *ShortlistService_AddEntry_Call) Run(run func(ctx context.Context, p domain.Principal, id domain.ShortlistID, target domain.UserID, note string)) *ShortlistService_AddEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 domain.ShortlistID
		if args[2] != nil {
			arg2 = args[2].(domain.ShortlistID)
		}
		var arg3 domain.UserID
		if args[3] != nil {
			arg3 = args[3].(domain.UserID)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ShortlistService_AddEntry_Call) Return(shortlistEntry *domain.ShortlistEntry, err error) *ShortlistService_AddEntry_Call {
	_c.Call.Return(shortlistEntry, err)
	return _c
}

func (_c *ShortlistService_AddEntry_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, id domain.ShortlistID, target domain.UserID, note string) (*domain.ShortlistEntry, error)) *ShortlistService_AddEntry_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type ShortlistService
func (_mock *ShortlistService) Close(ctx context.Context, p domain.Principal, id domain.ShortlistID) (*domain.Shortlist, error) {
	ret := _mock.Called(ctx, p, id)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 *domain.Shortlist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.ShortlistID) (*domain.Shortlist, error)); ok {
		return returnFunc(ctx, p, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.ShortlistID) *domain.Shortlist); ok {
		r0 = returnFunc(ctx, p, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Shortlist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal, domain.ShortlistID) error); ok {
		r1 = returnFunc(ctx, p, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShortlistService_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ShortlistService_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - id domain.ShortlistID
func (_e *ShortlistService_Expecter) Close(ctx interface{}, p interface{}, id interface{}) *ShortlistService_Close_Call {
	return &ShortlistService_Close_Call{Call: _e.mock.On("Close", ctx, p, id)}
}

func (_c *ShortlistService_Close_Call) Run(run func(ctx context.Context, p domain.Principal, id domain.ShortlistID)) *ShortlistService_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 domain.ShortlistID
		if args[2] != nil {
			arg2 = args[2].(domain.ShortlistID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ShortlistService_Close_Call) Return(shortlist *domain.Shortlist, err error) *ShortlistService_Close_Call {
	_c.Call.Return(shortlist, err)
	return _c
}

func (_c *ShortlistService_Close_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, id domain.ShortlistID) (*domain.Shortlist, error)) *ShortlistService_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Confirm provides a mock function for the type ShortlistService
func (_mock *ShortlistService) Confirm(ctx context.Context, p domain.Principal, id domain.ShortlistID) (*port.ConfirmResult, error) {
	ret := _mock.Called(ctx, p, id)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 *port.ConfirmResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.ShortlistID) (*port.ConfirmResult, error)); ok {
		return returnFunc(ctx, p, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.ShortlistID) *port.ConfirmResult); ok {
		r0 = returnFunc(ctx, p, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.ConfirmResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal, domain.ShortlistID) error); ok {
		r1 = returnFunc(ctx, p, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShortlistService_Confirm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Confirm'
type ShortlistService_Confirm_Call struct {
	*mock.Call
}

// Confirm is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - id domain.ShortlistID
func (_e *ShortlistService_Expecter) Confirm(ctx interface{}, p interface{}, id interface{}) *ShortlistService_Confirm_Call {
	return &ShortlistService_Confirm_Call{Call: _e.mock.On("Confirm", ctx, p, id)}
}

func (_c *ShortlistService_Confirm_Call) Run(run func(ctx context.Context, p domain.Principal, id domain.ShortlistID)) *ShortlistService_Confirm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 domain.ShortlistID
		if args[2] != nil {
			arg2 = args[2].(domain.ShortlistID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ShortlistService_Confirm_Call) Return(confirmResult *port.ConfirmResult, err error) *ShortlistService_Confirm_Call {
	_c.Call.Return(confirmResult, err)
	return _c
}

func (_c *ShortlistService_Confirm_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, id domain.ShortlistID) (*port.ConfirmResult, error)) *ShortlistService_Confirm_Call {
	_c.Call.Return(run)
	return _c
}

// ContactRequests provides a mock function for the type ShortlistService
func (_mock *ShortlistService) ContactRequests(ctx context.Context, p domain.Principal, id domain.ShortlistID) ([]domain.ContactRequest, error) {
	ret := _mock.Called(ctx, p, id)

	if len(ret) == 0 {
		panic("no return value specified for ContactRequests")
	}

	var r0 []domain.ContactRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.ShortlistID) ([]domain.ContactRequest, error)); ok {
		return returnFunc(ctx, p, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.ShortlistID) []domain.ContactRequest); ok {
		r0 = returnFunc(ctx, p, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ContactRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal, domain.ShortlistID) error); ok {
		r1 = returnFunc(ctx, p, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShortlistService_ContactRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContactRequests'
type ShortlistService_ContactRequests_Call struct {
	*mock.Call
}

// ContactRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - id domain.ShortlistID
func (_e *ShortlistService_Expecter) ContactRequests(ctx interface{}, p interface{}, id interface{}) *ShortlistService_ContactRequests_Call {
	return &ShortlistService_ContactRequests_Call{Call: _e.mock.On("ContactRequests", ctx, p, id)}
}

func (_c *ShortlistService_ContactRequests_Call) Run(run func(ctx context.Context, p domain.Principal, id domain.ShortlistID)) *ShortlistService_ContactRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 domain.ShortlistID
		if args[2] != nil {
			arg2 = args[2].(domain.ShortlistID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ShortlistService_ContactRequests_Call) Return(contactRequests []domain.ContactRequest, err error) *ShortlistService_ContactRequests_Call {
	_c.Call.Return(contactRequests, err)
	return _c
}

func (_c *ShortlistService_ContactRequests_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, id domain.ShortlistID) ([]domain.ContactRequest, error)) *ShortlistService_ContactRequests_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type ShortlistService
func (_mock *ShortlistService) Create(ctx context.Context, p domain.Principal, role domain.RoleID, name string, description string, date time.Time) (*domain.Shortlist, error) {
	ret := _mock.Called(ctx, p, role, name, description, date)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Shortlist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.RoleID, string, string, time.Time) (*domain.Shortlist, error)); ok {
		return returnFunc(ctx, p, role, name, description, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.RoleID, string, string, time.Time) *domain.Shortlist); ok {
		r0 = returnFunc(ctx, p, role, name, description, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Shortlist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal, domain.RoleID, string, string, time.Time) error); ok {
		r1 = returnFunc(ctx, p, role, name, description, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShortlistService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ShortlistService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - role domain.RoleID
//   - name string
//   - description string
//   - date time.Time
func (_e *ShortlistService_Expecter) Create(ctx interface{}, p interface{}, role interface{}, name interface{}, description interface{}, date interface{}) *ShortlistService_Create_Call {
	return &ShortlistService_Create_Call{Call: _e.mock.On("Create", ctx, p, role, name, description, date)}
}

func (_c *ShortlistService_Create_Call) Run(run func(ctx context.Context, p domain.Principal, role domain.RoleID, name string, description string, date time.Time)) *ShortlistService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 domain.RoleID
		if args[2] != nil {
			arg2 = args[2].(domain.RoleID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *ShortlistService_Create_Call) Return(shortlist *domain.Shortlist, err error) *ShortlistService_Create_Call {
	_c.Call.Return(shortlist, err)
	return _c
}

func (_c *ShortlistService_Create_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, role domain.RoleID, name string, description string, date time.Time) (*domain.Shortlist, error)) *ShortlistService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type ShortlistService
func (_mock *ShortlistService) Get(ctx context.Context, p domain.Principal, id domain.ShortlistID) (*domain.Shortlist, error) {
	ret := _mock.Called(ctx, p, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Shortlist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.ShortlistID) (*domain.Shortlist, error)); ok {
		return returnFunc(ctx, p, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.ShortlistID) *domain.Shortlist); ok {
		r0 = returnFunc(ctx, p, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Shortlist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal, domain.ShortlistID) error); ok {
		r1 = returnFunc(ctx, p, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShortlistService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ShortlistService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - id domain.ShortlistID
func (_e *ShortlistService_Expecter) Get(ctx interface{}, p interface{}, id interface{}) *ShortlistService_Get_Call {
	return &ShortlistService_Get_Call{Call: _e.mock.On("Get", ctx, p, id)}
}

func (_c *ShortlistService_Get_Call) Run(run func(ctx context.Context, p domain.Principal, id domain.ShortlistID)) *ShortlistService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 domain.ShortlistID
		if args[2] != nil {
			arg2 = args[2].(domain.ShortlistID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ShortlistService_Get_Call) Return(shortlist *domain.Shortlist, err error) *ShortlistService_Get_Call {
	_c.Call.Return(shortlist, err)
	return _c
}

func (_c *ShortlistService_Get_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, id domain.ShortlistID) (*domain.Shortlist, error)) *ShortlistService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type ShortlistService
func (_mock *ShortlistService) List(ctx context.Context, p domain.Principal, status *domain.ShortlistStatus) ([]domain.Shortlist, error) {
	ret := _mock.Called(ctx, p, status)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Shortlist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, *domain.ShortlistStatus) ([]domain.Shortlist, error)); ok {
		return returnFunc(ctx, p, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, *domain.ShortlistStatus) []domain.Shortlist); ok {
		r0 = returnFunc(ctx, p, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Shortlist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal, *domain.ShortlistStatus) error); ok {
		r1 = returnFunc(ctx, p, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShortlistService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ShortlistService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - status *domain.ShortlistStatus
func (_e *ShortlistService_Expecter) List(ctx interface{}, p interface{}, status interface{}) *ShortlistService_List_Call {
	return &ShortlistService_List_Call{Call: _e.mock.On("List", ctx, p, status)}
}

func (_c *ShortlistService_List_Call) Run(run func(ctx context.Context, p domain.Principal, status *domain.ShortlistStatus)) *ShortlistService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 *domain.ShortlistStatus
		if args[2] != nil {
			arg2 = args[2].(*domain.ShortlistStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ShortlistService_List_Call) Return(shortlists []domain.Shortlist, err error) *ShortlistService_List_Call {
	_c.Call.Return(shortlists, err)
	return _c
}

func (_c *ShortlistService_List_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, status *domain.ShortlistStatus) ([]domain.Shortlist, error)) *ShortlistService_List_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveEntry provides a mock function for the type ShortlistService
func (_mock *ShortlistService) RemoveEntry(ctx context.Context, p domain.Principal, id domain.ShortlistID, target domain.UserID) error {
	ret := _mock.Called(ctx, p, id, target)

	if len(ret) == 0 {
		panic("no return value specified for RemoveEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.ShortlistID, domain.UserID) error); ok {
		r0 = returnFunc(ctx, p, id, target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ShortlistService_RemoveEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveEntry'
type ShortlistService_RemoveEntry_Call struct {
	*mock.Call
}

// RemoveEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - id domain.ShortlistID
//   - target domain.UserID
func (_e *ShortlistService_Expecter) RemoveEntry(ctx interface{}, p interface{}, id interface{}, target interface{}) *ShortlistService_RemoveEntry_Call {
	return &ShortlistService_RemoveEntry_Call{Call: _e.mock.On("RemoveEntry", ctx, p, id, target)}
}

func (_c *ShortlistService_RemoveEntry_Call) Run(run func(ctx context.Context, p domain.Principal, id domain.ShortlistID, target domain.UserID)) *ShortlistService_RemoveEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 domain.ShortlistID
		if args[2] != nil {
			arg2 = args[2].(domain.ShortlistID)
		}
		var arg3 domain.UserID
		if args[3] != nil {
			arg3 = args[3].(domain.UserID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ShortlistService_RemoveEntry_Call) Return(err error) *ShortlistService_RemoveEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ShortlistService_RemoveEntry_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, id domain.ShortlistID, target domain.UserID) error) *ShortlistService_RemoveEntry_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ShortlistService
func (_mock *ShortlistService) Update(ctx context.Context, p domain.Principal, id domain.ShortlistID, name *string, description *string, date *time.Time) (*domain.Shortlist, error) {
	ret := _mock.Called(ctx, p, id, name, description, date)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Shortlist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.ShortlistID, *string, *string, *time.Time) (*domain.Shortlist, error)); ok {
		return returnFunc(ctx, p, id, name, description, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, domain.ShortlistID, *string, *string, *time.Time) *domain.Shortlist); ok {
		r0 = returnFunc(ctx, p, id, name, description, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Shortlist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal, domain.ShortlistID, *string, *string, *time.Time) error); ok {
		r1 = returnFunc(ctx, p, id, name, description, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShortlistService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ShortlistService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - id domain.ShortlistID
//   - name *string
//   - description *string
//   - date *time.Time
func (_e *ShortlistService_Expecter) Update(ctx interface{}, p interface{}, id interface{}, name interface{}, description interface{}, date interface{}) *ShortlistService_Update_Call {
	return &ShortlistService_Update_Call{Call: _e.mock.On("Update", ctx, p, id, name, description, date)}
}

func (_c *ShortlistService_Update_Call) Run(run func(ctx context.Context, p domain.Principal, id domain.ShortlistID, name *string, description *string, date *time.Time)) *ShortlistService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 domain.ShortlistID
		if args[2] != nil {
			arg2 = args[2].(domain.ShortlistID)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		var arg5 *time.Time
		if args[5] != nil {
			arg5 = args[5].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *ShortlistService_Update_Call) Return(shortlist *domain.Shortlist, err error) *ShortlistService_Update_Call {
	_c.Call.Return(shortlist, err)
	return _c
}

func (_c *ShortlistService_Update_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, id domain.ShortlistID, name *string, description *string, date *time.Time) (*domain.Shortlist, error)) *ShortlistService_Update_Call {
	_c.Call.Return(run)
	return _c
}
