// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewShortlistRepository creates a new instance of ShortlistRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortlistRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortlistRepository {
	mock := &ShortlistRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ShortlistRepository is an autogenerated mock type for the ShortlistRepository type
type ShortlistRepository struct {
	mock.Mock
}

type ShortlistRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ShortlistRepository) EXPECT() *ShortlistRepository_Expecter {
	return &ShortlistRepository_Expecter{mock: &_m.Mock}
}

// AddEntry provides a mock function for the type ShortlistRepository
func (_mock *ShortlistRepository) AddEntry(ctx context.Context, e *domain.ShortlistEntry) (*domain.ShortlistEntry, error) {
	ret := _mock.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for AddEntry")
	}

	var r0 *domain.ShortlistEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ShortlistEntry) (*domain.ShortlistEntry, error)); ok {
		return returnFunc(ctx, e)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ShortlistEntry) *domain.ShortlistEntry); ok {
		r0 = returnFunc(ctx, e)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ShortlistEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.ShortlistEntry) error); ok {
		r1 = returnFunc(ctx, e)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShortlistRepository_AddEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEntry'
type ShortlistRepository_AddEntry_Call struct {
	*mock.Call
}

// AddEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - e *domain.ShortlistEntry
func (_e *ShortlistRepository_Expecter) AddEntry(ctx interface{}, e interface{}) *ShortlistRepository_AddEntry_Call {
	return &ShortlistRepository_AddEntry_Call{Call: _e.mock.On("AddEntry", ctx, e)}
}

func (_c *ShortlistRepository_AddEntry_Call) Run(run func(ctx context.Context, e *domain.ShortlistEntry)) *ShortlistRepository_AddEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.ShortlistEntry
		if args[1] != nil {
			arg1 = args[1].(*domain.ShortlistEntry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ShortlistRepository_AddEntry_Call) Return(shortlistEntry *domain.ShortlistEntry, err error) *ShortlistRepository_AddEntry_Call {
	_c.Call.Return(shortlistEntry, err)
	return _c
}

func (_c *ShortlistRepository_AddEntry_Call) RunAndReturn(run func(ctx context.Context, e *domain.ShortlistEntry) (*domain.ShortlistEntry, error)) *ShortlistRepository_AddEntry_Call {
	_c.Call.Return(run)
	return _c
}

// ByID provides a mock function for the type ShortlistRepository
func (_mock *ShortlistRepository) ByID(ctx context.Context, id domain.ShortlistID) (*domain.Shortlist, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 *domain.Shortlist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ShortlistID) (*domain.Shortlist, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ShortlistID) *domain.Shortlist); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Shortlist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ShortlistID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShortlistRepository_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type ShortlistRepository_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ShortlistID
func (_e *ShortlistRepository_Expecter) ByID(ctx interface{}, id interface{}) *ShortlistRepository_ByID_Call {
	return &ShortlistRepository_ByID_Call{Call: _e.mock.On("ByID", ctx, id)}
}

func (_c *ShortlistRepository_ByID_Call) Run(run func(ctx context.Context, id domain.ShortlistID)) *ShortlistRepository_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ShortlistID
		if args[1] != nil {
			arg1 = args[1].(domain.ShortlistID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ShortlistRepository_ByID_Call) Return(shortlist *domain.Shortlist, err error) *ShortlistRepository_ByID_Call {
	_c.Call.Return(shortlist, err)
	return _c
}

func (_c *ShortlistRepository_ByID_Call) RunAndReturn(run func(ctx context.Context, id domain.ShortlistID) (*domain.Shortlist, error)) *ShortlistRepository_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type ShortlistRepository
func (_mock *ShortlistRepository) Close(ctx context.Context, id domain.ShortlistID) (*domain.Shortlist, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 *domain.Shortlist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ShortlistID) (*domain.Shortlist, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ShortlistID) *domain.Shortlist); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Shortlist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ShortlistID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShortlistRepository_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ShortlistRepository_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ShortlistID
func (_e *ShortlistRepository_Expecter) Close(ctx interface{}, id interface{}) *ShortlistRepository_Close_Call {
	return &ShortlistRepository_Close_Call{Call: _e.mock.On("Close", ctx, id)}
}

func (_c *ShortlistRepository_Close_Call) Run(run func(ctx context.Context, id domain.ShortlistID)) *ShortlistRepository_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ShortlistID
		if args[1] != nil {
			arg1 = args[1].(domain.ShortlistID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ShortlistRepository_Close_Call) Return(shortlist *domain.Shortlist, err error) *ShortlistRepository_Close_Call {
	_c.Call.Return(shortlist, err)
	return _c
}

func (_c *ShortlistRepository_Close_Call) RunAndReturn(run func(ctx context.Context, id domain.ShortlistID) (*domain.Shortlist, error)) *ShortlistRepository_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Confirm provides a mock function for the type ShortlistRepository
func (_mock *ShortlistRepository) Confirm(ctx context.Context, tx port.Tx, id domain.ShortlistID) ([]domain.ContactRequest, error) {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 []domain.ContactRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.ShortlistID) ([]domain.ContactRequest, error)); ok {
		return returnFunc(ctx, tx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.ShortlistID) []domain.ContactRequest); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ContactRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, port.Tx, domain.ShortlistID) error); ok {
		r1 = returnFunc(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShortlistRepository_Confirm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Confirm'
type ShortlistRepository_Confirm_Call struct {
	*mock.Call
}

// Confirm is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - id domain.ShortlistID
func (_e *ShortlistRepository_Expecter) Confirm(ctx interface{}, tx interface{}, id interface{}) *ShortlistRepository_Confirm_Call {
	return &ShortlistRepository_Confirm_Call{Call: _e.mock.On("Confirm", ctx, tx, id)}
}

func (_c *ShortlistRepository_Confirm_Call) Run(run func(ctx context.Context, tx port.Tx, id domain.ShortlistID)) *ShortlistRepository_Confirm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 domain.ShortlistID
		if args[2] != nil {
			arg2 = args[2].(domain.ShortlistID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ShortlistRepository_Confirm_Call) Return(contactRequests []domain.ContactRequest, err error) *ShortlistRepository_Confirm_Call {
	_c.Call.Return(contactRequests, err)
	return _c
}

func (_c *ShortlistRepository_Confirm_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, id domain.ShortlistID) ([]domain.ContactRequest, error)) *ShortlistRepository_Confirm_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type ShortlistRepository
func (_mock *ShortlistRepository) Create(ctx context.Context, s *domain.Shortlist) (*domain.Shortlist, error) {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Shortlist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Shortlist) (*domain.Shortlist, error)); ok {
		return returnFunc(ctx, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Shortlist) *domain.Shortlist); ok {
		r0 = returnFunc(ctx, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Shortlist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Shortlist) error); ok {
		r1 = returnFunc(ctx, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShortlistRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ShortlistRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s *domain.Shortlist
func (_e *ShortlistRepository_Expecter) Create(ctx interface{}, s interface{}) *ShortlistRepository_Create_Call {
	return &ShortlistRepository_Create_Call{Call: _e.mock.On("Create", ctx, s)}
}

func (_c *ShortlistRepository_Create_Call) Run(run func(ctx context.Context, s *domain.Shortlist)) *ShortlistRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Shortlist
		if args[1] != nil {
			arg1 = args[1].(*domain.Shortlist)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ShortlistRepository_Create_Call) Return(shortlist *domain.Shortlist, err error) *ShortlistRepository_Create_Call {
	_c.Call.Return(shortlist, err)
	return _c
}

func (_c *ShortlistRepository_Create_Call) RunAndReturn(run func(ctx context.Context, s *domain.Shortlist) (*domain.Shortlist, error)) *ShortlistRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOrganization provides a mock function for the type ShortlistRepository
func (_mock *ShortlistRepository) ListByOrganization(ctx context.Context, id domain.OrganizationID, status *domain.ShortlistStatus) ([]domain.Shortlist, error) {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for ListByOrganization")
	}

	var r0 []domain.Shortlist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID, *domain.ShortlistStatus) ([]domain.Shortlist, error)); ok {
		return returnFunc(ctx, id, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrganizationID, *domain.ShortlistStatus) []domain.Shortlist); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Shortlist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.OrganizationID, *domain.ShortlistStatus) error); ok {
		r1 = returnFunc(ctx, id, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShortlistRepository_ListByOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOrganization'
type ShortlistRepository_ListByOrganization_Call struct {
	*mock.Call
}

// ListByOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.OrganizationID
//   - status *domain.ShortlistStatus
func (_e *ShortlistRepository_Expecter) ListByOrganization(ctx interface{}, id interface{}, status interface{}) *ShortlistRepository_ListByOrganization_Call {
	return &ShortlistRepository_ListByOrganization_Call{Call: _e.mock.On("ListByOrganization", ctx, id, status)}
}

func (_c *ShortlistRepository_ListByOrganization_Call) Run(run func(ctx context.Context, id domain.OrganizationID, status *domain.ShortlistStatus)) *ShortlistRepository_ListByOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.OrganizationID
		if args[1] != nil {
			arg1 = args[1].(domain.OrganizationID)
		}
		var arg2 *domain.ShortlistStatus
		if args[2] != nil {
			arg2 = args[2].(*domain.ShortlistStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ShortlistRepository_ListByOrganization_Call) Return(shortlists []domain.Shortlist, err error) *ShortlistRepository_ListByOrganization_Call {
	_c.Call.Return(shortlists, err)
	return _c
}

func (_c *ShortlistRepository_ListByOrganization_Call) RunAndReturn(run func(ctx context.Context, id domain.OrganizationID, status *domain.ShortlistStatus) ([]domain.Shortlist, error)) *ShortlistRepository_ListByOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// OverdueRatios provides a mock function for the type ShortlistRepository
func (_mock *ShortlistRepository) OverdueRatios(ctx context.Context, now time.Time) ([]port.OverdueOrg, error) {
	ret := _mock.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for OverdueRatios")
	}

	var r0 []port.OverdueOrg
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) ([]port.OverdueOrg, error)); ok {
		return returnFunc(ctx, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) []port.OverdueOrg); ok {
		r0 = returnFunc(ctx, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.OverdueOrg)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShortlistRepository_OverdueRatios_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OverdueRatios'
type ShortlistRepository_OverdueRatios_Call struct {
	*mock.Call
}

// OverdueRatios is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
func (_e *ShortlistRepository_Expecter) OverdueRatios(ctx interface{}, now interface{}) *ShortlistRepository_OverdueRatios_Call {
	return &ShortlistRepository_OverdueRatios_Call{Call: _e.mock.On("OverdueRatios", ctx, now)}
}

func (_c *ShortlistRepository_OverdueRatios_Call) Run(run func(ctx context.Context, now time.Time)) *ShortlistRepository_OverdueRatios_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ShortlistRepository_OverdueRatios_Call) Return(overdueOrgs []port.OverdueOrg, err error) *ShortlistRepository_OverdueRatios_Call {
	_c.Call.Return(overdueOrgs, err)
	return _c
}

func (_c *ShortlistRepository_OverdueRatios_Call) RunAndReturn(run func(ctx context.Context, now time.Time) ([]port.OverdueOrg, error)) *ShortlistRepository_OverdueRatios_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveEntry provides a mock function for the type ShortlistRepository
func (_mock *ShortlistRepository) RemoveEntry(ctx context.Context, id domain.ShortlistID, user domain.UserID) error {
	ret := _mock.Called(ctx, id, user)

	if len(ret) == 0 {
		panic("no return value specified for RemoveEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ShortlistID, domain.UserID) error); ok {
		r0 = returnFunc(ctx, id, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ShortlistRepository_RemoveEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveEntry'
type ShortlistRepository_RemoveEntry_Call struct {
	*mock.Call
}

// RemoveEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ShortlistID
//   - user domain.UserID
func (_e *ShortlistRepository_Expecter) RemoveEntry(ctx interface{}, id interface{}, user interface{}) *ShortlistRepository_RemoveEntry_Call {
	return &ShortlistRepository_RemoveEntry_Call{Call: _e.mock.On("RemoveEntry", ctx, id, user)}
}

func (_c *ShortlistRepository_RemoveEntry_Call) Run(run func(ctx context.Context, id domain.ShortlistID, user domain.UserID)) *ShortlistRepository_RemoveEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ShortlistID
		if args[1] != nil {
			arg1 = args[1].(domain.ShortlistID)
		}
		var arg2 domain.UserID
		if args[2] != nil {
			arg2 = args[2].(domain.UserID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ShortlistRepository_RemoveEntry_Call) Return(err error) *ShortlistRepository_RemoveEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ShortlistRepository_RemoveEntry_Call) RunAndReturn(run func(ctx context.Context, id domain.ShortlistID, user domain.UserID) error) *ShortlistRepository_RemoveEntry_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ShortlistRepository
func (_mock *ShortlistRepository) Update(ctx context.Context, id domain.ShortlistID, name *string, description *string, date *time.Time) (*domain.Shortlist, error) {
	ret := _mock.Called(ctx, id, name, description, date)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Shortlist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ShortlistID, *string, *string, *time.Time) (*domain.Shortlist, error)); ok {
		return returnFunc(ctx, id, name, description, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ShortlistID, *string, *string, *time.Time) *domain.Shortlist); ok {
		r0 = returnFunc(ctx, id, name, description, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Shortlist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ShortlistID, *string, *string, *time.Time) error); ok {
		r1 = returnFunc(ctx, id, name, description, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShortlistRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ShortlistRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ShortlistID
//   - name *string
//   - description *string
//   - date *time.Time
func (_e *ShortlistRepository_Expecter) Update(ctx interface{}, id interface{}, name interface{}, description interface{}, date interface{}) *ShortlistRepository_Update_Call {
	return &ShortlistRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, name, description, date)}
}

func (_c *ShortlistRepository_Update_Call) Run(run func(ctx context.Context, id domain.ShortlistID, name *string, description *string, date *time.Time)) *ShortlistRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ShortlistID
		if args[1] != nil {
			arg1 = args[1].(domain.ShortlistID)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ShortlistRepository_Update_Call) Return(shortlist *domain.Shortlist, err error) *ShortlistRepository_Update_Call {
	_c.Call.Return(shortlist, err)
	return _c
}

func (_c *ShortlistRepository_Update_Call) RunAndReturn(run func(ctx context.Context, id domain.ShortlistID, name *string, description *string, date *time.Time) (*domain.Shortlist, error)) *ShortlistRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
