// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewSkillRepository creates a new instance of SkillRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSkillRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SkillRepository {
	mock := &SkillRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SkillRepository is an autogenerated mock type for the SkillRepository type
type SkillRepository struct {
	mock.Mock
}

type SkillRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SkillRepository) EXPECT() *SkillRepository_Expecter {
	return &SkillRepository_Expecter{mock: &_m.Mock}
}

// BySlug provides a mock function for the type SkillRepository
func (_mock *SkillRepository) BySlug(ctx context.Context, slug string) (*domain.Skill, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for BySlug")
	}

	var r0 *domain.Skill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Skill, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Skill); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Skill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SkillRepository_BySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BySlug'
type SkillRepository_BySlug_Call struct {
	*mock.Call
}

// BySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *SkillRepository_Expecter) BySlug(ctx interface{}, slug interface{}) *SkillRepository_BySlug_Call {
	return &SkillRepository_BySlug_Call{Call: _e.mock.On("BySlug", ctx, slug)}
}

func (_c *SkillRepository_BySlug_Call) Run(run func(ctx context.Context, slug string)) *SkillRepository_BySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SkillRepository_BySlug_Call) Return(skill *domain.Skill, err error) *SkillRepository_BySlug_Call {
	_c.Call.Return(skill, err)
	return _c
}

func (_c *SkillRepository_BySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*domain.Skill, error)) *SkillRepository_BySlug_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type SkillRepository
func (_mock *SkillRepository) Create(ctx context.Context, tx port.Tx, s *domain.Skill) (*domain.Skill, error) {
	ret := _mock.Called(ctx, tx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Skill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, *domain.Skill) (*domain.Skill, error)); ok {
		return returnFunc(ctx, tx, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, *domain.Skill) *domain.Skill); ok {
		r0 = returnFunc(ctx, tx, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Skill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, port.Tx, *domain.Skill) error); ok {
		r1 = returnFunc(ctx, tx, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SkillRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SkillRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - s *domain.Skill
func (_e *SkillRepository_Expecter) Create(ctx interface{}, tx interface{}, s interface{}) *SkillRepository_Create_Call {
	return &SkillRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, s)}
}

func (_c *SkillRepository_Create_Call) Run(run func(ctx context.Context, tx port.Tx, s *domain.Skill)) *SkillRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 *domain.Skill
		if args[2] != nil {
			arg2 = args[2].(*domain.Skill)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SkillRepository_Create_Call) Return(skill *domain.Skill, err error) *SkillRepository_Create_Call {
	_c.Call.Return(skill, err)
	return _c
}

func (_c *SkillRepository_Create_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, s *domain.Skill) (*domain.Skill, error)) *SkillRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRequest provides a mock function for the type SkillRepository
func (_mock *SkillRepository) CreateRequest(ctx context.Context, userID domain.UserID, proposedName string, rationale string) (domain.RequestID, error) {
	ret := _mock.Called(ctx, userID, proposedName, rationale)

	if len(ret) == 0 {
		panic("no return value specified for CreateRequest")
	}

	var r0 domain.RequestID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, string, string) (domain.RequestID, error)); ok {
		return returnFunc(ctx, userID, proposedName, rationale)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, string, string) domain.RequestID); ok {
		r0 = returnFunc(ctx, userID, proposedName, rationale)
	} else {
		r0 = ret.Get(0).(domain.RequestID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, string, string) error); ok {
		r1 = returnFunc(ctx, userID, proposedName, rationale)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SkillRepository_CreateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRequest'
type SkillRepository_CreateRequest_Call struct {
	*mock.Call
}

// CreateRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - proposedName string
//   - rationale string
func (_e *SkillRepository_Expecter) CreateRequest(ctx interface{}, userID interface{}, proposedName interface{}, rationale interface{}) *SkillRepository_CreateRequest_Call {
	return &SkillRepository_CreateRequest_Call{Call: _e.mock.On("CreateRequest", ctx, userID, proposedName, rationale)}
}

func (_c *SkillRepository_CreateRequest_Call) Run(run func(ctx context.Context, userID domain.UserID, proposedName string, rationale string)) *SkillRepository_CreateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SkillRepository_CreateRequest_Call) Return(requestID domain.RequestID, err error) *SkillRepository_CreateRequest_Call {
	_c.Call.Return(requestID, err)
	return _c
}

func (_c *SkillRepository_CreateRequest_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, proposedName string, rationale string) (domain.RequestID, error)) *SkillRepository_CreateRequest_Call {
	_c.Call.Return(run)
	return _c
}

// DecideRequest provides a mock function for the type SkillRepository
func (_mock *SkillRepository) DecideRequest(ctx context.Context, tx port.Tx, id domain.RequestID, by domain.AdminID, approve bool, reason string, created *domain.Skill) error {
	ret := _mock.Called(ctx, tx, id, by, approve, reason, created)

	if len(ret) == 0 {
		panic("no return value specified for DecideRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.RequestID, domain.AdminID, bool, string, *domain.Skill) error); ok {
		r0 = returnFunc(ctx, tx, id, by, approve, reason, created)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SkillRepository_DecideRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecideRequest'
type SkillRepository_DecideRequest_Call struct {
	*mock.Call
}

// DecideRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - id domain.RequestID
//   - by domain.AdminID
//   - approve bool
//   - reason string
//   - created *domain.Skill
func (_e *SkillRepository_Expecter) DecideRequest(ctx interface{}, tx interface{}, id interface{}, by interface{}, approve interface{}, reason interface{}, created interface{}) *SkillRepository_DecideRequest_Call {
	return &SkillRepository_DecideRequest_Call{Call: _e.mock.On("DecideRequest", ctx, tx, id, by, approve, reason, created)}
}

func (_c *SkillRepository_DecideRequest_Call) Run(run func(ctx context.Context, tx port.Tx, id domain.RequestID, by domain.AdminID, approve bool, reason string, created *domain.Skill)) *SkillRepository_DecideRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 domain.RequestID
		if args[2] != nil {
			arg2 = args[2].(domain.RequestID)
		}
		var arg3 domain.AdminID
		if args[3] != nil {
			arg3 = args[3].(domain.AdminID)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 *domain.Skill
		if args[6] != nil {
			arg6 = args[6].(*domain.Skill)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *SkillRepository_DecideRequest_Call) Return(err error) *SkillRepository_DecideRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SkillRepository_DecideRequest_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, id domain.RequestID, by domain.AdminID, approve bool, reason string, created *domain.Skill) error) *SkillRepository_DecideRequest_Call {
	_c.Call.Return(run)
	return _c
}

// LinkPairs provides a mock function for the type SkillRepository
func (_mock *SkillRepository) LinkPairs(ctx context.Context, tx port.Tx, links []port.PRLink) error {
	ret := _mock.Called(ctx, tx, links)

	if len(ret) == 0 {
		panic("no return value specified for LinkPairs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, []port.PRLink) error); ok {
		r0 = returnFunc(ctx, tx, links)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SkillRepository_LinkPairs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkPairs'
type SkillRepository_LinkPairs_Call struct {
	*mock.Call
}

// LinkPairs is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - links []port.PRLink
func (_e *SkillRepository_Expecter) LinkPairs(ctx interface{}, tx interface{}, links interface{}) *SkillRepository_LinkPairs_Call {
	return &SkillRepository_LinkPairs_Call{Call: _e.mock.On("LinkPairs", ctx, tx, links)}
}

func (_c *SkillRepository_LinkPairs_Call) Run(run func(ctx context.Context, tx port.Tx, links []port.PRLink)) *SkillRepository_LinkPairs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 []port.PRLink
		if args[2] != nil {
			arg2 = args[2].([]port.PRLink)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SkillRepository_LinkPairs_Call) Return(err error) *SkillRepository_LinkPairs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SkillRepository_LinkPairs_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, links []port.PRLink) error) *SkillRepository_LinkPairs_Call {
	_c.Call.Return(run)
	return _c
}

// MatchSkill provides a mock function for the type SkillRepository
func (_mock *SkillRepository) MatchSkill(ctx context.Context, proposedName string) (*domain.Skill, error) {
	ret := _mock.Called(ctx, proposedName)

	if len(ret) == 0 {
		panic("no return value specified for MatchSkill")
	}

	var r0 *domain.Skill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Skill, error)); ok {
		return returnFunc(ctx, proposedName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Skill); ok {
		r0 = returnFunc(ctx, proposedName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Skill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, proposedName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SkillRepository_MatchSkill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MatchSkill'
type SkillRepository_MatchSkill_Call struct {
	*mock.Call
}

// MatchSkill is a helper method to define mock.On call
//   - ctx context.Context
//   - proposedName string
func (_e *SkillRepository_Expecter) MatchSkill(ctx interface{}, proposedName interface{}) *SkillRepository_MatchSkill_Call {
	return &SkillRepository_MatchSkill_Call{Call: _e.mock.On("MatchSkill", ctx, proposedName)}
}

func (_c *SkillRepository_MatchSkill_Call) Run(run func(ctx context.Context, proposedName string)) *SkillRepository_MatchSkill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SkillRepository_MatchSkill_Call) Return(skill *domain.Skill, err error) *SkillRepository_MatchSkill_Call {
	_c.Call.Return(skill, err)
	return _c
}

func (_c *SkillRepository_MatchSkill_Call) RunAndReturn(run func(ctx context.Context, proposedName string) (*domain.Skill, error)) *SkillRepository_MatchSkill_Call {
	_c.Call.Return(run)
	return _c
}

// PendingRequests provides a mock function for the type SkillRepository
func (_mock *SkillRepository) PendingRequests(ctx context.Context, status string) ([]port.SkillRequest, error) {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for PendingRequests")
	}

	var r0 []port.SkillRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]port.SkillRequest, error)); ok {
		return returnFunc(ctx, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []port.SkillRequest); ok {
		r0 = returnFunc(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.SkillRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SkillRepository_PendingRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PendingRequests'
type SkillRepository_PendingRequests_Call struct {
	*mock.Call
}

// PendingRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
func (_e *SkillRepository_Expecter) PendingRequests(ctx interface{}, status interface{}) *SkillRepository_PendingRequests_Call {
	return &SkillRepository_PendingRequests_Call{Call: _e.mock.On("PendingRequests", ctx, status)}
}

func (_c *SkillRepository_PendingRequests_Call) Run(run func(ctx context.Context, status string)) *SkillRepository_PendingRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SkillRepository_PendingRequests_Call) Return(skillRequests []port.SkillRequest, err error) *SkillRepository_PendingRequests_Call {
	_c.Call.Return(skillRequests, err)
	return _c
}

func (_c *SkillRepository_PendingRequests_Call) RunAndReturn(run func(ctx context.Context, status string) ([]port.SkillRequest, error)) *SkillRepository_PendingRequests_Call {
	_c.Call.Return(run)
	return _c
}

// RecomputeStanding provides a mock function for the type SkillRepository
func (_mock *SkillRepository) RecomputeStanding(ctx context.Context, tx port.Tx, id domain.UserID, skillID domain.SkillID) (*domain.UserSkill, error) {
	ret := _mock.Called(ctx, tx, id, skillID)

	if len(ret) == 0 {
		panic("no return value specified for RecomputeStanding")
	}

	var r0 *domain.UserSkill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.UserID, domain.SkillID) (*domain.UserSkill, error)); ok {
		return returnFunc(ctx, tx, id, skillID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, domain.UserID, domain.SkillID) *domain.UserSkill); ok {
		r0 = returnFunc(ctx, tx, id, skillID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserSkill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, port.Tx, domain.UserID, domain.SkillID) error); ok {
		r1 = returnFunc(ctx, tx, id, skillID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SkillRepository_RecomputeStanding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecomputeStanding'
type SkillRepository_RecomputeStanding_Call struct {
	*mock.Call
}

// RecomputeStanding is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - id domain.UserID
//   - skillID domain.SkillID
func (_e *SkillRepository_Expecter) RecomputeStanding(ctx interface{}, tx interface{}, id interface{}, skillID interface{}) *SkillRepository_RecomputeStanding_Call {
	return &SkillRepository_RecomputeStanding_Call{Call: _e.mock.On("RecomputeStanding", ctx, tx, id, skillID)}
}

func (_c *SkillRepository_RecomputeStanding_Call) Run(run func(ctx context.Context, tx port.Tx, id domain.UserID, skillID domain.SkillID)) *SkillRepository_RecomputeStanding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 domain.UserID
		if args[2] != nil {
			arg2 = args[2].(domain.UserID)
		}
		var arg3 domain.SkillID
		if args[3] != nil {
			arg3 = args[3].(domain.SkillID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SkillRepository_RecomputeStanding_Call) Return(userSkill *domain.UserSkill, err error) *SkillRepository_RecomputeStanding_Call {
	_c.Call.Return(userSkill, err)
	return _c
}

func (_c *SkillRepository_RecomputeStanding_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, id domain.UserID, skillID domain.SkillID) (*domain.UserSkill, error)) *SkillRepository_RecomputeStanding_Call {
	_c.Call.Return(run)
	return _c
}

// RequestsSince provides a mock function for the type SkillRepository
func (_mock *SkillRepository) RequestsSince(ctx context.Context, userID domain.UserID, since time.Time) ([]port.SkillRequest, error) {
	ret := _mock.Called(ctx, userID, since)

	if len(ret) == 0 {
		panic("no return value specified for RequestsSince")
	}

	var r0 []port.SkillRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, time.Time) ([]port.SkillRequest, error)); ok {
		return returnFunc(ctx, userID, since)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, time.Time) []port.SkillRequest); ok {
		r0 = returnFunc(ctx, userID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.SkillRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, since)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SkillRepository_RequestsSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestsSince'
type SkillRepository_RequestsSince_Call struct {
	*mock.Call
}

// RequestsSince is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - since time.Time
func (_e *SkillRepository_Expecter) RequestsSince(ctx interface{}, userID interface{}, since interface{}) *SkillRepository_RequestsSince_Call {
	return &SkillRepository_RequestsSince_Call{Call: _e.mock.On("RequestsSince", ctx, userID, since)}
}

func (_c *SkillRepository_RequestsSince_Call) Run(run func(ctx context.Context, userID domain.UserID, since time.Time)) *SkillRepository_RequestsSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SkillRepository_RequestsSince_Call) Return(skillRequests []port.SkillRequest, err error) *SkillRepository_RequestsSince_Call {
	_c.Call.Return(skillRequests, err)
	return _c
}

func (_c *SkillRepository_RequestsSince_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, since time.Time) ([]port.SkillRequest, error)) *SkillRepository_RequestsSince_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type SkillRepository
func (_mock *SkillRepository) Search(ctx context.Context, query string) ([]port.SkillMatch, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []port.SkillMatch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]port.SkillMatch, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []port.SkillMatch); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.SkillMatch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SkillRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type SkillRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *SkillRepository_Expecter) Search(ctx interface{}, query interface{}) *SkillRepository_Search_Call {
	return &SkillRepository_Search_Call{Call: _e.mock.On("Search", ctx, query)}
}

func (_c *SkillRepository_Search_Call) Run(run func(ctx context.Context, query string)) *SkillRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SkillRepository_Search_Call) Return(skillMatchs []port.SkillMatch, err error) *SkillRepository_Search_Call {
	_c.Call.Return(skillMatchs, err)
	return _c
}

func (_c *SkillRepository_Search_Call) RunAndReturn(run func(ctx context.Context, query string) ([]port.SkillMatch, error)) *SkillRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SetLinkStatus provides a mock function for the type SkillRepository
func (_mock *SkillRepository) SetLinkStatus(ctx context.Context, tx port.Tx, links []port.PRLink, status domain.PRLinkStatus) error {
	ret := _mock.Called(ctx, tx, links, status)

	if len(ret) == 0 {
		panic("no return value specified for SetLinkStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.Tx, []port.PRLink, domain.PRLinkStatus) error); ok {
		r0 = returnFunc(ctx, tx, links, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SkillRepository_SetLinkStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLinkStatus'
type SkillRepository_SetLinkStatus_Call struct {
	*mock.Call
}

// SetLinkStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - tx port.Tx
//   - links []port.PRLink
//   - status domain.PRLinkStatus
func (_e *SkillRepository_Expecter) SetLinkStatus(ctx interface{}, tx interface{}, links interface{}, status interface{}) *SkillRepository_SetLinkStatus_Call {
	return &SkillRepository_SetLinkStatus_Call{Call: _e.mock.On("SetLinkStatus", ctx, tx, links, status)}
}

func (_c *SkillRepository_SetLinkStatus_Call) Run(run func(ctx context.Context, tx port.Tx, links []port.PRLink, status domain.PRLinkStatus)) *SkillRepository_SetLinkStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.Tx
		if args[1] != nil {
			arg1 = args[1].(port.Tx)
		}
		var arg2 []port.PRLink
		if args[2] != nil {
			arg2 = args[2].([]port.PRLink)
		}
		var arg3 domain.PRLinkStatus
		if args[3] != nil {
			arg3 = args[3].(domain.PRLinkStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SkillRepository_SetLinkStatus_Call) Return(err error) *SkillRepository_SetLinkStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SkillRepository_SetLinkStatus_Call) RunAndReturn(run func(ctx context.Context, tx port.Tx, links []port.PRLink, status domain.PRLinkStatus) error) *SkillRepository_SetLinkStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UserSkills provides a mock function for the type SkillRepository
func (_mock *SkillRepository) UserSkills(ctx context.Context, id domain.UserID) ([]domain.UserSkill, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UserSkills")
	}

	var r0 []domain.UserSkill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) ([]domain.UserSkill, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) []domain.UserSkill); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserSkill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SkillRepository_UserSkills_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserSkills'
type SkillRepository_UserSkills_Call struct {
	*mock.Call
}

// UserSkills is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.UserID
func (_e *SkillRepository_Expecter) UserSkills(ctx interface{}, id interface{}) *SkillRepository_UserSkills_Call {
	return &SkillRepository_UserSkills_Call{Call: _e.mock.On("UserSkills", ctx, id)}
}

func (_c *SkillRepository_UserSkills_Call) Run(run func(ctx context.Context, id domain.UserID)) *SkillRepository_UserSkills_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SkillRepository_UserSkills_Call) Return(userSkills []domain.UserSkill, err error) *SkillRepository_UserSkills_Call {
	_c.Call.Return(userSkills, err)
	return _c
}

func (_c *SkillRepository_UserSkills_Call) RunAndReturn(run func(ctx context.Context, id domain.UserID) ([]domain.UserSkill, error)) *SkillRepository_UserSkills_Call {
	_c.Call.Return(run)
	return _c
}
