// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/Manik2708/gitcherrypick/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenIssuer creates a new instance of TokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenIssuer {
	mock := &TokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenIssuer is an autogenerated mock type for the TokenIssuer type
type TokenIssuer struct {
	mock.Mock
}

type TokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenIssuer) EXPECT() *TokenIssuer_Expecter {
	return &TokenIssuer_Expecter{mock: &_m.Mock}
}

// HashRefreshToken provides a mock function for the type TokenIssuer
func (_mock *TokenIssuer) HashRefreshToken(plaintext string) []byte {
	ret := _mock.Called(plaintext)

	if len(ret) == 0 {
		panic("no return value specified for HashRefreshToken")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(plaintext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// TokenIssuer_HashRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashRefreshToken'
type TokenIssuer_HashRefreshToken_Call struct {
	*mock.Call
}

// HashRefreshToken is a helper method to define mock.On call
//   - plaintext string
func (_e *TokenIssuer_Expecter) HashRefreshToken(plaintext interface{}) *TokenIssuer_HashRefreshToken_Call {
	return &TokenIssuer_HashRefreshToken_Call{Call: _e.mock.On("HashRefreshToken", plaintext)}
}

func (_c *TokenIssuer_HashRefreshToken_Call) Run(run func(plaintext string)) *TokenIssuer_HashRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenIssuer_HashRefreshToken_Call) Return(bytes []byte) *TokenIssuer_HashRefreshToken_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *TokenIssuer_HashRefreshToken_Call) RunAndReturn(run func(plaintext string) []byte) *TokenIssuer_HashRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Issue provides a mock function for the type TokenIssuer
func (_mock *TokenIssuer) Issue(ctx context.Context, p domain.Principal, ttl time.Duration) (string, error) {
	ret := _mock.Called(ctx, p, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, time.Duration) (string, error)); ok {
		return returnFunc(ctx, p, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Principal, time.Duration) string); ok {
		r0 = returnFunc(ctx, p, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Principal, time.Duration) error); ok {
		r1 = returnFunc(ctx, p, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenIssuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type TokenIssuer_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - ctx context.Context
//   - p domain.Principal
//   - ttl time.Duration
func (_e *TokenIssuer_Expecter) Issue(ctx interface{}, p interface{}, ttl interface{}) *TokenIssuer_Issue_Call {
	return &TokenIssuer_Issue_Call{Call: _e.mock.On("Issue", ctx, p, ttl)}
}

func (_c *TokenIssuer_Issue_Call) Run(run func(ctx context.Context, p domain.Principal, ttl time.Duration)) *TokenIssuer_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Principal
		if args[1] != nil {
			arg1 = args[1].(domain.Principal)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TokenIssuer_Issue_Call) Return(s string, err error) *TokenIssuer_Issue_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TokenIssuer_Issue_Call) RunAndReturn(run func(ctx context.Context, p domain.Principal, ttl time.Duration) (string, error)) *TokenIssuer_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// NewRefreshToken provides a mock function for the type TokenIssuer
func (_mock *TokenIssuer) NewRefreshToken() (string, []byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewRefreshToken")
	}

	var r0 string
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (string, []byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() []byte); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// TokenIssuer_NewRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewRefreshToken'
type TokenIssuer_NewRefreshToken_Call struct {
	*mock.Call
}

// NewRefreshToken is a helper method to define mock.On call
func (_e *TokenIssuer_Expecter) NewRefreshToken() *TokenIssuer_NewRefreshToken_Call {
	return &TokenIssuer_NewRefreshToken_Call{Call: _e.mock.On("NewRefreshToken")}
}

func (_c *TokenIssuer_NewRefreshToken_Call) Run(run func()) *TokenIssuer_NewRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TokenIssuer_NewRefreshToken_Call) Return(plaintext string, hash []byte, err error) *TokenIssuer_NewRefreshToken_Call {
	_c.Call.Return(plaintext, hash, err)
	return _c
}

func (_c *TokenIssuer_NewRefreshToken_Call) RunAndReturn(run func() (string, []byte, error)) *TokenIssuer_NewRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type TokenIssuer
func (_mock *TokenIssuer) Verify(ctx context.Context, token string) (*domain.Principal, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *domain.Principal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Principal, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Principal); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Principal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenIssuer_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type TokenIssuer_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *TokenIssuer_Expecter) Verify(ctx interface{}, token interface{}) *TokenIssuer_Verify_Call {
	return &TokenIssuer_Verify_Call{Call: _e.mock.On("Verify", ctx, token)}
}

func (_c *TokenIssuer_Verify_Call) Run(run func(ctx context.Context, token string)) *TokenIssuer_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenIssuer_Verify_Call) Return(principal *domain.Principal, err error) *TokenIssuer_Verify_Call {
	_c.Call.Return(principal, err)
	return _c
}

func (_c *TokenIssuer_Verify_Call) RunAndReturn(run func(ctx context.Context, token string) (*domain.Principal, error)) *TokenIssuer_Verify_Call {
	_c.Call.Return(run)
	return _c
}
