// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/Manik2708/gitcherrypick/backend/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenIssuer creates a new instance of TokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenIssuer {
	mock := &TokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenIssuer is an autogenerated mock type for the TokenIssuer type
type TokenIssuer struct {
	mock.Mock
}

type TokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenIssuer) EXPECT() *TokenIssuer_Expecter {
	return &TokenIssuer_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function for the type TokenIssuer
func (_mock *TokenIssuer) Issue(ctx context.Context, c port.AccessClaims, ttl time.Duration) (string, error) {
	ret := _mock.Called(ctx, c, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.AccessClaims, time.Duration) (string, error)); ok {
		return returnFunc(ctx, c, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.AccessClaims, time.Duration) string); ok {
		r0 = returnFunc(ctx, c, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, port.AccessClaims, time.Duration) error); ok {
		r1 = returnFunc(ctx, c, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenIssuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type TokenIssuer_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - ctx context.Context
//   - c port.AccessClaims
//   - ttl time.Duration
func (_e *TokenIssuer_Expecter) Issue(ctx interface{}, c interface{}, ttl interface{}) *TokenIssuer_Issue_Call {
	return &TokenIssuer_Issue_Call{Call: _e.mock.On("Issue", ctx, c, ttl)}
}

func (_c *TokenIssuer_Issue_Call) Run(run func(ctx context.Context, c port.AccessClaims, ttl time.Duration)) *TokenIssuer_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 port.AccessClaims
		if args[1] != nil {
			arg1 = args[1].(port.AccessClaims)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TokenIssuer_Issue_Call) Return(s string, err error) *TokenIssuer_Issue_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TokenIssuer_Issue_Call) RunAndReturn(run func(ctx context.Context, c port.AccessClaims, ttl time.Duration) (string, error)) *TokenIssuer_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type TokenIssuer
func (_mock *TokenIssuer) Verify(ctx context.Context, token string) (*port.AccessClaims, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *port.AccessClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*port.AccessClaims, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *port.AccessClaims); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.AccessClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenIssuer_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type TokenIssuer_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *TokenIssuer_Expecter) Verify(ctx interface{}, token interface{}) *TokenIssuer_Verify_Call {
	return &TokenIssuer_Verify_Call{Call: _e.mock.On("Verify", ctx, token)}
}

func (_c *TokenIssuer_Verify_Call) Run(run func(ctx context.Context, token string)) *TokenIssuer_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenIssuer_Verify_Call) Return(accessClaims *port.AccessClaims, err error) *TokenIssuer_Verify_Call {
	_c.Call.Return(accessClaims, err)
	return _c
}

func (_c *TokenIssuer_Verify_Call) RunAndReturn(run func(ctx context.Context, token string) (*port.AccessClaims, error)) *TokenIssuer_Verify_Call {
	_c.Call.Return(run)
	return _c
}
