// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewTx creates a new instance of Tx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *Tx {
	mock := &Tx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Tx is an autogenerated mock type for the Tx type
type Tx struct {
	mock.Mock
}

type Tx_Expecter struct {
	mock *mock.Mock
}

func (_m *Tx) EXPECT() *Tx_Expecter {
	return &Tx_Expecter{mock: &_m.Mock}
}

// TxHandle provides a mock function for the type Tx
func (_mock *Tx) TxHandle() {
	_mock.Called()
	return
}

// Tx_TxHandle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TxHandle'
type Tx_TxHandle_Call struct {
	*mock.Call
}

// TxHandle is a helper method to define mock.On call
func (_e *Tx_Expecter) TxHandle() *Tx_TxHandle_Call {
	return &Tx_TxHandle_Call{Call: _e.mock.On("TxHandle")}
}

func (_c *Tx_TxHandle_Call) Run(run func()) *Tx_TxHandle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Tx_TxHandle_Call) Return() *Tx_TxHandle_Call {
	_c.Call.Return()
	return _c
}

func (_c *Tx_TxHandle_Call) RunAndReturn(run func()) *Tx_TxHandle_Call {
	_c.Run(run)
	return _c
}
